In [21]:
import pandas as pd

In [22]:
DATA_PRINCIPAL = ['2021-03-31', '2021-06-30', '2021-09-30']

## BPA --------- FEITO

In [23]:
df = pd.read_csv('itr_cia_aberta_BPA_ind_2021.csv', sep=';', encoding='latin-1')
df=df[df['ORDEM_EXERC'] == 'ÚLTIMO']

In [24]:
df

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
1,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2021-03-31,1,Ativo Total,1.891609e+09,S
3,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2021-03-31,1.01,Caixa e Equivalentes de Caixa,6.257823e+07,S
5,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2021-03-31,1.01.01,Caixa,2.856016e+07,S
7,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2021-03-31,1.01.02,Aplicações de Liquidez,3.401807e+07,S
9,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2021-03-31,1.02,Ativos Financeiros,1.689094e+09,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285859,97.837.181/0001-47,2021-09-30,1,DEXCO S.A.,21091,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2021-09-30,1.02.04.01.04,Goodwill na aquisição da Satipel em 2009,4.550300e+04,N
285861,97.837.181/0001-47,2021-09-30,1,DEXCO S.A.,21091,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2021-09-30,1.02.04.01.05,Goodwill de empresa incorporada em 2010,0.000000e+00,N
285863,97.837.181/0001-47,2021-09-30,1,DEXCO S.A.,21091,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2021-09-30,1.02.04.01.06,Goodwill de empresa incorporada em 2011,0.000000e+00,N
285865,97.837.181/0001-47,2021-09-30,1,DEXCO S.A.,21091,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2021-09-30,1.02.04.01.07,Goodwill de empresa incorporada em 2012,2.402000e+03,N
285867,97.837.181/0001-47,2021-09-30,1,DEXCO S.A.,21091,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2021-09-30,1.02.04.01.08,Goodwill de empresa incorporada em 2014,0.000000e+00,N

In [25]:
df['DT_REFER'].unique().tolist()

['2021-03-31',
 '2021-06-30',
 '2021-09-30',
 '2021-12-31',
 '2021-05-31',
 '2021-08-31',
 '2021-11-30']

In [26]:
lista_ativos = df['DENOM_CIA'].unique().tolist()
lista_final = []
data_refer = df['DT_REFER'].unique().tolist()
datas = df['DT_FIM_EXERC'].unique().tolist()
for ativo in lista_ativos:
    dfativo = df[df['DENOM_CIA']==ativo]
    
    caixa = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="1.01.01"')['VL_CONTA'].values
    ativo_total = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="1"')['VL_CONTA'].values
    

    if len(caixa) == 3 and len(ativo_total) == 3:
        dicio = {
            'ativo': ativo,
            
            f'caixa_{DATA_PRINCIPAL[0]}': caixa[0],
            f'caixa_{DATA_PRINCIPAL[1]}': caixa[1],
            f'caixa_{DATA_PRINCIPAL[2]}': caixa[2],
            
           

            f'ativo_total_{DATA_PRINCIPAL[0]}': ativo_total[0],
            f'ativo_total_{DATA_PRINCIPAL[1]}': ativo_total[1],
            f'ativo_total_{DATA_PRINCIPAL[2]}': ativo_total[2],
            

        
        }    
        lista_final.append(dicio)

In [27]:
df_bpa = pd.DataFrame(lista_final)
print(df_bpa.shape)
df_bpa.head()

(713, 7)

,ativo,caixa_2021-03-31,caixa_2021-06-30,caixa_2021-09-30,ativo_total_2021-03-31,ativo_total_2021-06-30,ativo_total_2021-09-30
0,BCO BRASIL S.A.,28560165.0,22906388.0,18950192.0,1.891609e+09,1.912107e+09,2.033137e+09
1,BRB BANCO DE BRASILIA S.A.,181652.0,208934.0,166842.0,2.772367e+07,2.704359e+07,2.797788e+07
2,CENTRAIS ELET BRAS S.A. - ELETROBRAS,3786870.0,4472390.0,5598933.0,1.305432e+08,1.344126e+08,1.426974e+08
3,COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB,2410432.0,1300452.0,1333849.0,3.022368e+06,1.901896e+06,1.933012e+06
4,CARAMURU ALIMENTOS S.A.,445155.0,179243.0,414702.0,6.652438e+06,6.130584e+06,6.507947e+06

## BPP ------------ Fazendo

In [28]:
df2 = pd.read_csv('itr_cia_aberta_BPP_ind_2021.csv', sep=';', encoding='latin-1')
df2=df2[df2['ORDEM_EXERC'] == 'ÚLTIMO']
df2.head(60)

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
1,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2,Passivo Total,1.891609e+09,S
3,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.01,Passivos Financeiros Avaliados ao Valor Justo ...,4.494772e+06,S
5,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.01.01,Instrumentos financeiros derivativos,4.494772e+06,N
7,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.02,Passivos Financeiros ao Custo Amortizado,1.678043e+09,S
9,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.02.01,Depósitos,1.678043e+09,S
11,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.02.01.01,Recursos de instituições financeiras,7.721072e+08,N
13,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.02.01.02,Recursos de clientes,5.995790e+08,N
15,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.02.01.03,Recursos de emissões de títulos e valores mobi...,2.022012e+08,N
17,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.02.01.06,Outros passivos financeiros,1.041553e+08,N
19,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.02.02,Captações no Mercado Aberto,0.000000e+00,S
21,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.02.03,Recursos Mercado Interfinanceiro,0.000000e+00,S
23,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.02.04,Outras Captações,0.000000e+00,S
25,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.03,Provisões,3.476783e+07,S
27,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.04,Passivos Fiscais,1.731500e+07,S
29,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.05,Outros Passivos,2.940014e+07,S
31,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.05.01,Capital Social Realizado,0.000000e+00,N
33,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.05.02,Reservas de Capital,0.000000e+00,N
35,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.05.03,Reservas de Reavaliação,0.000000e+00,N
37,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.05.04,Reservas de Lucro,0.000000e+00,N
39,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.05.05,Ajustes de Avaliação Patrimonial,0.000000e+00,N
41,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.05.06,Lucros/Prejuízos Acumulados,0.000000e+00,N
43,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.06,Passivos sobre Ativos Não Correntes a Venda e ...,0.000000e+00,S
45,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.06.01,Passivos sobre Ativos Não Correntes a Venda,0.000000e+00,S
47,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.06.02,Passivos sobre Ativos de Operações Descontinuadas,0.000000e+00,S
49,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.07,Patrimônio Líquido,1.275889e+08,S
51,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.07.01,Capital Social Realizado,9.000002e+07,S
53,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.07.02,Reservas de Capital,1.399364e+06,S
55,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.07.02.01,Ágio na Emissão de Ações,1.399364e+06,S
57,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.07.02.02,Reserva Especial de Ágio na Incorporação,0.000000e+00,S
59,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.07.02.03,Alienação de Bônus de Subscrição,0.000000e+00,S
61,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.07.02.04,Opções Outorgadas,0.000000e+00,S
63,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.07.02.05,Ações em Tesouraria,0.000000e+00,S
65,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.07.03,Reservas de Reavaliação,2.022000e+03,S
67,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.07.04,Reservas de Lucros,3.757971e+07,S
69,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.07.04.01,Reserva Legal,9.259072e+06,S
71,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.07.04.02,Reserva Estatutária,2.859663e+07,S
73,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.07.04.03,Reserva para Contingências,0.000000e+00,S
75,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.07.04.04,Reserva de Lucros a Realizar,0.000000e+00,S
77,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.07.04.05,Reserva de Retenção de Lucros,0.000000e+00,S
79,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.07.04.06,Reserva Especial para Dividendos Não Distribuídos,0.000000e+00,S
81,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.07.04.07,Reserva de Incentivos Fiscais,0.000000e+00,S
83,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.07.04.08,Dividendo Adicional Proposto,0.000000e+00,S
85,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.07.04.09,Ações em Tesouraria,-2.759870e+05,S
87,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.07.05,Lucros/Prejuízos Acumulados,4.158835e+06,S
89,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.07.06,Ajustes de Avaliação Patrimonial,0.000000e+00,S
91,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.07.07,Ajustes Acumulados de Conversão,0.000000e+00,S
93,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-03-31,2.07.08,Outros Resultados Abrangentes,-5.551025e+06,S
95,00.000.000/0001-91,2021-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-06-30,2,Passivo Total,1.912107e+09,S
97,00.000.000/0001-91,2021-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-06-30,2.01,Passivos Financeiros Avaliados ao Valor Justo ...,4.363260e+06,S
99,00.000.000/0001-91,2021-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-06-30,2.01.01,Instrumentos financeiros derivativos,4.363260e+06,N
101,00.000.000/0001-91,2021-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-06-30,2.02,Passivos Financeiros ao Custo Amortizado,1.683183e+09,S
103,00.000.000/0001-91,2021-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-06-30,2.02.01,Depósitos,1.683183e+09,S
105,00.000.000/0001-91,2021-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-06-30,2.02.01.01,Recursos de instituições financeiras,7.572345e+08,N
107,00.000.000/0001-91,2021-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-06-30,2.02.01.02,Recursos de clientes,6.405409e+08,N
109,00.000.000/0001-91,2021-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-06-30,2.02.01.03,Recursos de emissões de títulos e valores mobi...,1.886840e+08,N
111,00.000.000/0001-91,2021-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-06-30,2.02.01.06,Outros passivos financeiros,9.672370e+07,N
113,00.000.000/0001-91,2021-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-06-30,2.02.02,Captações no Mercado Aberto,0.000000e+00,S
115,00.000.000/0001-91,2021-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-06-30,2.02.03,Recursos Mercado Interfinanceiro,0.000000e+00,S
117,00.000.000/0001-91,2021-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-06-30,2.02.04,Outras Captações,0.000000e+00,S
119,00.000.000/0001-91,2021-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2021-06-30,2.03,Provisões,3.490098e+07,S

In [29]:
lista_ativos = df2['DENOM_CIA'].unique().tolist()
lista_final = []
data_refer = df2['DT_REFER'].unique().tolist()
datas = df2['DT_FIM_EXERC'].unique().tolist()
for ativo in lista_ativos:
    dfativo = df2[df2['DENOM_CIA']==ativo]
    # datas = dfativo['DT_REFER'].unique().tolist() 
    divida_cp = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="2.01.04"')['VL_CONTA'].values
    divida_lp = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="2.02.01"')['VL_CONTA'].values
    pl = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="2.03"')['VL_CONTA'].values

    if len(divida_cp) == 3 and len(divida_lp) == 3 and len(pl) == 3:
        dicio = {
            'ativo': ativo,
            
            f'divida_cp_{DATA_PRINCIPAL[0]}': divida_cp[0],
            f'divida_cp_{DATA_PRINCIPAL[1]}': divida_cp[1],
            f'divida_cp_{DATA_PRINCIPAL[2]}': divida_cp[2],
            
            
            f'divida_lp_{DATA_PRINCIPAL[0]}': divida_lp[0],
            f'divida_lp_{DATA_PRINCIPAL[1]}': divida_lp[1],
            f'divida_lp_{DATA_PRINCIPAL[2]}': divida_lp[2],
        
            
            f'pl_{DATA_PRINCIPAL[0]}': pl[0],
            f'pl_{DATA_PRINCIPAL[1]}': pl[1],
            f'pl_{DATA_PRINCIPAL[2]}': pl[2]
        
        }    
        lista_final.append(dicio)

In [30]:
df_bpp = pd.DataFrame(lista_final)
print(df_bpp.shape)
df_bpp.head()

(699, 10)

,ativo,divida_cp_2021-03-31,divida_cp_2021-06-30,divida_cp_2021-09-30,divida_lp_2021-03-31,divida_lp_2021-06-30,divida_lp_2021-09-30,pl_2021-03-31,pl_2021-06-30,pl_2021-09-30
0,BRB BANCO DE BRASILIA S.A.,235.0,38539.0,36532.0,15022004.0,14447214.0,14918808.0,638859.0,635366.0,687437.0
1,CENTRAIS ELET BRAS S.A. - ELETROBRAS,8183024.0,8634114.0,9017426.0,19893470.0,19825543.0,19682340.0,72815673.0,75253579.0,76128510.0
2,COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB,0.0,0.0,0.0,0.0,0.0,0.0,1855709.0,1872530.0,1903815.0
3,CARAMURU ALIMENTOS S.A.,2134180.0,2671465.0,2547451.0,953157.0,460942.0,708440.0,1255431.0,1401829.0,1491990.0
4,NEUMARKT TRADE AND FINANCIAL CENTER S/A,0.0,0.0,0.0,64447.0,68562.0,69107.0,-59727.0,-63912.0,-64411.0

## DRE ------------ Fazendo

In [31]:
df3 = pd.read_csv('itr_cia_aberta_DRE_ind_2021.csv', sep=';', encoding='latin-1')
df3=df3[df3['ORDEM_EXERC'] == 'ÚLTIMO']

In [32]:
print(df3.shape)
df3.head(200)

(119772, 15)

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
1,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-03-31,3.01,Receitas de Intermediação Financeira,31186377.00,S
3,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-03-31,3.01.01,Operações de Crédito,22608968.00,N
5,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-03-31,3.01.02,Operações de Arrendamento Mercantil,0.00,N
7,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-03-31,3.01.03,Resultado de Operações com TVM,6707236.00,N
9,00.000.000/0001-91,2021-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-03-31,3.01.04,Resultado de IFD,1805559.00,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,00.000.000/0001-91,2021-09-30,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-07-01,2021-09-30,3.11,Lucro ou Prejuízo Líquido do Período,4541499.00,S
394,00.000.000/0001-91,2021-09-30,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-09-30,3.99,Lucro por Ação (R$/Ação),5.00,N
395,00.000.000/0001-91,2021-09-30,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-07-01,2021-09-30,3.99,Lucro por Ação (R$/Ação),1.59,N
398,00.000.000/0001-91,2021-09-30,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-01-01,2021-09-30,3.99.01,Lucro Básico por Ação,0.00,N
399,00.000.000/0001-91,2021-09-30,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2021-07-01,2021-09-30,3.99.01,Lucro Básico por Ação,0.00,N

In [33]:
lista_ativos = df3['DENOM_CIA'].unique().tolist()
lista_final = []
for ativo in lista_ativos:
    dfativo = df3[df3['DENOM_CIA']==ativo]

    # RECEITA LIQUIDA 3.01

    dfativo_3_01 = dfativo[dfativo['CD_CONTA']=='3.01']
    datas_unicas_ini = dfativo_3_01['DT_INI_EXERC'].unique().tolist()
    datas_unicas_fim = dfativo_3_01['DT_FIM_EXERC'].unique().tolist()

    receita_liquida_total = []
    if len(datas_unicas_ini) == 3 and len(datas_unicas_fim) == 3:
        for i in range(len(datas_unicas_ini)):
            data_ini = datas_unicas_ini[i]
            data_fim = datas_unicas_fim[i]
            # print(f'Para o ativo {ativo}, a Data de início é {data_ini} e a data de fim é {data_fim}.')
            receita_liquida = dfativo_3_01.query('DT_INI_EXERC==@data_ini and DT_FIM_EXERC==@data_fim')['VL_CONTA'].values
            receita_liquida_total.extend(receita_liquida)
    
    # EBIT 3.05

    dfativo_3_05 = dfativo[dfativo['CD_CONTA']=='3.05']
    datas_unicas_ini_3_05 = dfativo_3_05['DT_INI_EXERC'].unique().tolist()
    datas_unicas_fim_3_05 = dfativo_3_05['DT_FIM_EXERC'].unique().tolist() 
    ebit_total = []
    if len(datas_unicas_ini_3_05) == 3 and len(datas_unicas_fim_3_05) == 3:
        for i in range(len(datas_unicas_ini_3_05)):
            data_ini = datas_unicas_ini_3_05[i]
            data_fim = datas_unicas_fim_3_05[i]
            # print(f'Para o ativo {ativo}, a Data de início é {data_ini} e a data de fim é {data_fim}.')
            ebit = dfativo_3_05.query('DT_INI_EXERC==@data_ini and DT_FIM_EXERC==@data_fim')['VL_CONTA'].values
            ebit_total.extend(ebit)

    #  LUCRO LIQUIDO 3.11

    dfativo_3_11 = dfativo[dfativo['CD_CONTA']=='3.11']
    datas_unicas_ini_3_11 = dfativo_3_11['DT_INI_EXERC'].unique().tolist()
    datas_unicas_fim_3_11 = dfativo_3_11['DT_FIM_EXERC'].unique().tolist() 
    lucro_liquido_total = []
    if len(datas_unicas_ini_3_11) == 3  and len(datas_unicas_fim_3_11) == 3:
        for i in range(len(datas_unicas_ini_3_11)):
            data_ini = datas_unicas_ini_3_11[i]
            data_fim = datas_unicas_fim_3_11[i]
            # print(f'Para o ativo {ativo}, a Data de início é {data_ini} e a data de fim é {data_fim}.')
            lucro_liquido = dfativo_3_11.query('DT_INI_EXERC==@data_ini and DT_FIM_EXERC==@data_fim')['VL_CONTA'].values
            lucro_liquido_total.extend(lucro_liquido)

    # print(f'Ativo: {ativo}')
    # print(f'Receita Líquida: {receita_liquida_total}')
    # print(f'EBIT: {ebit_total}')
    # print(f'Lucro Líquido: {lucro_liquido_total}')
    # print('-----------------------------')

    # PIETROSKI F_SCORE
    # ROA = lucro_liquido_total / ativo_total  3.11 / 1 
    # Margem liq = lucro_liquido_total / receita_liquida_total 3.11 / 3.01
    # Giro do ativo = receita_liquida_total / ativo_total 3.01 / 1
    # Alavancagem financeira = divida_total(bruta) / ativo total  (2.01.04 + 2.02.01) / 2.03


    # 3 é DRE, vamo buscar
    #ll ja tenho e ativo total tb, entao ROA ok
    # Margem liq tb ja tenho, so fazer conta
    #giro do ativo tb ja tenho, so fazer conta

    if len(receita_liquida_total) == 3 and len(ebit_total) == 3 and len(lucro_liquido_total) == 3:  
        dicio ={
            'ativo': ativo,
            f'receita_liquida_{DATA_PRINCIPAL[0]}': receita_liquida_total[0],
            f'receita_liquida_{DATA_PRINCIPAL[1]}': receita_liquida_total[1],
            f'receita_liquida_{DATA_PRINCIPAL[2]}': receita_liquida_total[2],

            f'ebit_{DATA_PRINCIPAL[0]}': ebit_total[0],
            f'ebit_{DATA_PRINCIPAL[1]}': ebit_total[1],
            f'ebit_{DATA_PRINCIPAL[2]}': ebit_total[2],

            f'lucro_liquido_{DATA_PRINCIPAL[0]}': lucro_liquido_total[0],
            f'lucro_liquido_{DATA_PRINCIPAL[1]}': lucro_liquido_total[1],
            f'lucro_liquido_{DATA_PRINCIPAL[2]}': lucro_liquido_total[2]
        }
        lista_final.append(dicio)

In [34]:
df_dre = pd.DataFrame(lista_final)
print(df_dre.shape)
df_dre.head()

(689, 10)

,ativo,receita_liquida_2021-03-31,receita_liquida_2021-06-30,receita_liquida_2021-09-30,ebit_2021-03-31,ebit_2021-06-30,ebit_2021-09-30,lucro_liquido_2021-03-31,lucro_liquido_2021-06-30,lucro_liquido_2021-09-30
0,BCO BRASIL S.A.,31186377.0,16135564.0,40147901.0,4008444.0,6559492.0,5881368.0,4157202.0,5567231.0,4541499.0
1,BRB BANCO DE BRASILIA S.A.,623694.0,698413.0,772302.0,151892.0,174968.0,329527.0,117241.0,124519.0,191553.0
2,CENTRAIS ELET BRAS S.A. - ELETROBRAS,90281.0,98128.0,283936.0,2012747.0,1884346.0,1737168.0,1601068.0,2518871.0,923845.0
3,COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB,13403.0,17127.0,12850.0,1727377.0,8401.0,20044.0,1142200.0,16758.0,31286.0
4,CARAMURU ALIMENTOS S.A.,1166363.0,2096642.0,2247987.0,256509.0,-6830.0,232497.0,49994.0,146398.0,90160.0

In [35]:
print(df_bpa.info())
print(df_bpp.info())
print(df_dre.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 713 entries, 0 to 712
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ativo                   713 non-null    object
 1   caixa_2021-03-31        713 non-null    float64
 2   caixa_2021-06-30        713 non-null    float64
 3   caixa_2021-09-30        713 non-null    float64
 4   ativo_total_2021-03-31  713 non-null    float64
 5   ativo_total_2021-06-30  713 non-null    float64
 6   ativo_total_2021-09-30  713 non-null    float64
dtypes: float64(6), object(1)
memory usage: 39.1+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ativo                 699 non-null    object
 1   divida_cp_2021-03-31  699 non-null    float64
 2   divida_cp_2021-06-30  699 non-null    float64
 3   divida_cp_2021-09-30  699 non-null    float64
 4   divida_lp_2021-03-31  699 non-null    float64
 5   divida_lp_2021-06-30  699 non-null    float64
 6   divida_lp_2021-09-30  699 non-null    float64
 7   pl_2021-03-31         699 non-null    float64
 8   pl_2021-06-30         699 non-null    float64
 9   pl_2021-09-30         699 non-null    float64
dtypes: float64(9), object(1)
memory usage: 54.7+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 689 entries, 0 to 688
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ativo                       689 non-null    object
 1   receita_liquida_2021-03-31  689 non-null    float64
 2   receita_liquida_2021-06-30  689 non-null    float64
 3   receita_liquida_2021-09-30  689 non-null    float64
 4   ebit_2021-03-31             689 non-null    float64
 5   ebit_2021-06-30             689 non-null    float64
 6   ebit_2021-09-30             689 non-null    float64
 7   lucro_liquido_2021-03-31    689 non-null    float64
 8   lucro_liquido_2021-06-30    689 non-null    float64
 9   lucro_liquido_2021-09-30    689 non-null    float64
dtypes: float64(9), object(1)
memory usage: 54.0+ KB
None

In [36]:
df_final = df_bpa.merge(df_bpp, on="ativo", how="inner") \
           .merge(df_dre, on="ativo", how="inner")

print(df_bpa.shape)
print(df_bpp.shape)
print(df_dre.shape)
print('----')
print(df_final.shape)

(713, 7)
(699, 10)
(689, 10)
----
(667, 25)

In [37]:
df_final.to_excel('resultado/dados_final_2021.xlsx', index=False)

## ------ FIMM DA RASPAGEM

## _____________________________

## -------- INICIO DAS FORMULAS (MAGIC FORMULA E PIOTROSKI)

In [38]:
print(df_final.shape)
df_final.head()

(667, 25)

,ativo,caixa_2021-03-31,caixa_2021-06-30,caixa_2021-09-30,ativo_total_2021-03-31,ativo_total_2021-06-30,ativo_total_2021-09-30,divida_cp_2021-03-31,divida_cp_2021-06-30,divida_cp_2021-09-30,...,pl_2021-09-30,receita_liquida_2021-03-31,receita_liquida_2021-06-30,receita_liquida_2021-09-30,ebit_2021-03-31,ebit_2021-06-30,ebit_2021-09-30,lucro_liquido_2021-03-31,lucro_liquido_2021-06-30,lucro_liquido_2021-09-30
0,BRB BANCO DE BRASILIA S.A.,181652.0,208934.0,166842.0,27723672.0,27043588.0,27977883.0,235.0,38539.0,36532.0,...,687437.0,623694.0,698413.0,772302.0,151892.0,174968.0,329527.0,117241.0,124519.0,191553.0
1,CENTRAIS ELET BRAS S.A. - ELETROBRAS,3786870.0,4472390.0,5598933.0,130543182.0,134412580.0,142697356.0,8183024.0,8634114.0,9017426.0,...,76128510.0,90281.0,98128.0,283936.0,2012747.0,1884346.0,1737168.0,1601068.0,2518871.0,923845.0
2,COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB,2410432.0,1300452.0,1333849.0,3022368.0,1901896.0,1933012.0,0.0,0.0,0.0,...,1903815.0,13403.0,17127.0,12850.0,1727377.0,8401.0,20044.0,1142200.0,16758.0,31286.0
3,CARAMURU ALIMENTOS S.A.,445155.0,179243.0,414702.0,6652438.0,6130584.0,6507947.0,2134180.0,2671465.0,2547451.0,...,1491990.0,1166363.0,2096642.0,2247987.0,256509.0,-6830.0,232497.0,49994.0,146398.0,90160.0
4,NEUMARKT TRADE AND FINANCIAL CENTER S/A,75.0,2.0,2.0,21065.0,20993.0,21039.0,0.0,0.0,0.0,...,-64411.0,90.0,61.0,152.0,31.0,-52.0,65.0,-4864.0,-4184.0,-499.0

## ------------

In [39]:
import pandas as pd
import numpy as np
import yfinance as yf

def normalizar_cnpj(cnpj):
    if pd.isna(cnpj):
        return None
    return str(cnpj).replace('.','').replace('-','').replace('/','').strip().zfill(14)

# ================================================================
# CONFIGURAÇÃO
# ================================================================

DATAS = DATA_PRINCIPAL

TICKERS_IBOV = [
    "VALE3", "ITUB4", "PETR4", "PETR3", "AXIA3", "BBDC4", "SBSP3", "B3SA3",
    "ITSA4", "BPAC11", "WEGE3", "BBAS3", "EMBJ3", "ABEV3", "EQTL3", "RENT3",
    "RDOR3", "ENEV3", "PRIO3", "VBBR3", "SUZB3", "RADL3", "AXIA7", "VIVT3",
    "UGPA3", "BBDC3", "GGBR4", "CPLE3", "CMIG4", "TIMS3", "TOTS3", "BBSE3",
    "RAIL3", "ENGI11", "AXIA6", "MOTV3", "KLBN11", "LREN3", "ALOS3", "MBRF3",
    "SANB11", "ASAI3", "EGIE3", "ISAE4", "CSAN3", "CSMG3", "MULT3", "CXSE3",
    "SMFT3", "TAEE11", "PSSA3", "CPFE3", "CMIN3", "BRAV3", "CYRE3", "GOAU4",
    "FLRY3", "NATU3", "HYPE3", "COGN3", "CURY3", "CSNA3", "IGTI11", "BRAP4",
    "DIRR3", "IRBR3", "POMO4", "MGLU3", "MRVE3", "VIVA3", "AURE3", "SLCE3",
    "YDUQ3", "AZZA3", "RECV3", "USIM5", "HAPV3", "CEAB3", "BRKM5", "BEEF3",
    "RENT4", "VAMO3", "CYRE4", "PCAR3", "RAIZ4",
]

# ================================================================
# 1) CARREGA dados_final_2025.xlsx e transforma em formato longo
# ================================================================

# df_wide = pd.read_excel('resultado/dados_final_2024.xlsx')
df_wide = df_final
print(f"Empresas no arquivo: {len(df_wide)}")

# Transforma de wide para long (uma linha por empresa por data)
rows = []
for _, row in df_wide.iterrows():
    for data in DATAS:
        rows.append({
            'ativo':         row['ativo'],
            'dt_refer':      data,
            'caixa':         row[f'caixa_{data}'],
            'ativo_total':   row[f'ativo_total_{data}'],
            'divida_cp':     row[f'divida_cp_{data}'],
            'divida_lp':     row[f'divida_lp_{data}'],
            'pl':            row[f'pl_{data}'],
            'receita':       row[f'receita_liquida_{data}'],
            'ebit':          row[f'ebit_{data}'],
            'lucro':         row[f'lucro_liquido_{data}'],
        })

df = pd.DataFrame(rows)
print(f"Total linhas (empresa × data): {len(df)}")

# ================================================================
# 2) MAPEIA ticker → nome da empresa
# ================================================================

# Carrega mapeamento B3
df_mapa = pd.read_excel('../mapeamento_ticker.xlsx')

def empresa_tem_ticker(todos_tickers: str, ticker: str) -> bool:
    if pd.isna(todos_tickers):
        return False
    return ticker in [t.strip() for t in str(todos_tickers).split(',')]

# Para cada ticker do Ibovespa, busca o nome da empresa
ticker_para_nome = {}
for ticker in TICKERS_IBOV:
    match = df_mapa[df_mapa['todos_tickers'].apply(
        lambda x: empresa_tem_ticker(x, ticker)
    )]
    if not match.empty:
        ticker_para_nome[ticker] = match.iloc[0]['nome']

print(f"\nTickers mapeados: {len(ticker_para_nome)}/{len(TICKERS_IBOV)}")

# Inverte: nome → ticker
nome_para_ticker = {v: k for k, v in ticker_para_nome.items()}

# ================================================================
# 3) CRUZA nome do ITR com nome do mapeamento B3
# ================================================================

# Carrega CNPJ do ITR
df_itr = pd.read_csv('itr_cia_aberta_BPP_ind_2021.csv', sep=';', encoding='latin1')
cnpj_empresa = df_itr[['CNPJ_CIA','DENOM_CIA']].drop_duplicates()
cnpj_empresa.columns = ['cnpj','nome_itr']
cnpj_empresa['cnpj_norm'] = cnpj_empresa['cnpj'].apply(normalizar_cnpj)

# CNPJ do mapeamento B3
df_mapa['cnpj_norm'] = df_mapa['cnpj'].apply(normalizar_cnpj)
cnpj_b3 = df_mapa[['cnpj_norm','nome']].drop_duplicates()
cnpj_b3.columns = ['cnpj_norm','nome_b3']

# Cruza: cnpj → nome_itr + nome_b3
mapa_completo = cnpj_empresa.merge(cnpj_b3, on='cnpj_norm', how='inner')

# Para cada nome_b3 do Ibovespa, pega o nome_itr correspondente
ibov_nomes = {}
for ticker in TICKERS_IBOV:
    if ticker in ticker_para_nome:
        nome_b3 = ticker_para_nome[ticker]
        match = mapa_completo[mapa_completo['nome_b3'] == nome_b3]
        if not match.empty:
            ibov_nomes[ticker] = match.iloc[0]['nome_itr']

print(f"Empresas encontradas no ITR: {len(ibov_nomes)}/{len(TICKERS_IBOV)}")

# ================================================================
# 4) FILTRA df só para empresas do Ibovespa
# ================================================================

nomes_itr_ibov = list(ibov_nomes.values())
df = df[df['ativo'].isin(nomes_itr_ibov)].copy()
print(f"\nLinhas após filtro Ibovespa: {len(df)}")
print(f"Empresas únicas: {df['ativo'].nunique()}")

# Adiciona ticker
nome_itr_para_ticker = {v: k for k, v in ibov_nomes.items()}
df['ticker'] = df['ativo'].map(nome_itr_para_ticker)

# ================================================================
# 5) CALCULA indicadores
# ================================================================

df['divida_bruta']   = df['divida_cp'] + df['divida_lp']
df['divida_liquida'] = df['divida_bruta'] - df['caixa']
df['cap_investido']  = df['pl'] + df['divida_liquida']

df['ROIC']        = df['ebit'] / df['cap_investido']
df['ROE']         = df['lucro'] / df['pl']
df['margem_liq']  = df['lucro'] / df['receita']
df['div_ebitda']  = df['divida_bruta'] / df['ebit']  # proxy EBITDA≈EBIT
df['ROA']         = df['lucro'] / df['ativo_total']

df['giro_ativo'] = df['receita'] / df['ativo_total']
df['alavancagem'] = df['divida_bruta'] / df['ativo_total']

# Remove cap_investido negativo
df = df[df['cap_investido'] > 0].reset_index(drop=True)

print(f"\nApós remover cap_investido ≤ 0: {len(df)} linhas")

# ================================================================
# 6) BUSCA preço histórico
# ================================================================

def get_preco(ticker: str, dt_refer: str):
    try:
        data_fim = pd.Timestamp(dt_refer)
        data_ini = data_fim - pd.Timedelta(days=7)
        hist = yf.download(
            ticker + ".SA",
            start=data_ini,
            end=data_fim + pd.Timedelta(days=1),
            progress=False,
            auto_adjust=True
        )
        if hist.empty:
            return None
        return float(hist["Close"].iloc[-1])
    except Exception:
        return None

combos = df[['ticker','dt_refer']].drop_duplicates()
print(f"\nBuscando preços para {len(combos)} combinações ticker+data...")

precos = {}
for i, row in combos.iterrows():
    key = (row['ticker'], row['dt_refer'])
    precos[key] = get_preco(row['ticker'], row['dt_refer'])
    if (i+1) % 20 == 0:
        print(f"  {i+1}/{len(combos)}...")

df['preco'] = df.apply(lambda r: precos.get((r['ticker'], r['dt_refer'])), axis=1)
print(f"Com preço: {df['preco'].notna().sum()}/{len(df)}")

# ================================================================
# 7) BUSCA número de ações
# ================================================================

df_cap = pd.read_csv(
    'itr_cia_aberta_composicao_capital_2021.csv',
    sep=';', encoding='latin1', dtype={'CNPJ_CIA': str}
)
df_cap['cnpj_norm']  = df_cap['CNPJ_CIA'].apply(normalizar_cnpj)
df_cap['acoes_circ'] = df_cap['QT_ACAO_TOTAL_CAP_INTEGR'] - df_cap['QT_ACAO_TOTAL_TESOURO']
df_cap['dt_refer']   = pd.to_datetime(df_cap['DT_REFER'], dayfirst=True).dt.strftime('%Y-%m-%d')
df_cap = df_cap.sort_values('VERSAO', ascending=False).drop_duplicates(subset=['cnpj_norm','dt_refer'])
df_cap = df_cap[['cnpj_norm','dt_refer','acoes_circ']]

# Adiciona cnpj_norm no df
df = df.merge(
    cnpj_empresa[['nome_itr','cnpj_norm']].rename(columns={'nome_itr':'ativo'}),
    on='ativo',
    how='left'
)

# Junta ações
df = df.merge(df_cap, on=['cnpj_norm','dt_refer'], how='left')
print(f"Com ações: {df['acoes_circ'].notna().sum()}/{len(df)}")

# ================================================================
# 8) CALCULA EV e Earnings Yield
# ================================================================

df['valor_mercado']   = df['preco'] * df['acoes_circ']
df['EV']              = df['valor_mercado'] + df['cap_investido'] - df['pl']
df['earnings_yield']  = df['ebit'] / df['EV']

# ================================================================
# RESULTADO FINAL
# ================================================================

# df_final = df[[
#     'ativo', 'ticker', 'dt_refer', 
#     'preco', 'acoes_circ', 'valor_mercado',
#     'ebit', 'cap_investido', 'pl', 'EV',
#     'ROIC', 'earnings_yield', 'ROE', 'margem_liq', 'div_ebitda', 'ROA', 'giro_ativo', 'alavancagem'
# ]].copy()
print("COLUNAS DF")
print(df.columns.tolist())
df_final=df

print("\n" + "="*70)
print("RESULTADO FINAL")
print("="*70)
print(f"Total linhas:  {len(df_final)}")
print(f"Empresas:      {df_final['ativo'].nunique()}")
print(f"Tickers:       {df_final['ticker'].nunique()}")
print(f"Com EV:        {df_final['EV'].notna().sum()}")
print(f"Com EY:        {df_final['earnings_yield'].notna().sum()}")
print()
print(df_final.head(12).to_string(index=False))
print()

# Salva
df_final.to_excel('ibovespa_magic_formula_2021.xlsx', index=False)
print("Salvo: ibovespa_magic_formula_2021.xlsx")

Empresas no arquivo: 667
Total linhas (empresa × data): 2001

Tickers mapeados: 83/85
Empresas encontradas no ITR: 78/85

Linhas após filtro Ibovespa: 201
Empresas únicas: 67

Após remover cap_investido ≤ 0: 197 linhas

Buscando preços para 197 combinações ticker+data...

C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  20/197...

C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
$MOTV3.SA: possibly delisted; no price data found  (1d 2021-03-24 00:00:00 -> 2021-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1616554800, endDate = 1617246000")

1 Failed download:
['MOTV3.SA']: possibly delisted; no price data found  (1d 2021-03-24 00:00:00 -> 2021-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1616554800, endDate = 1617246000")
$MOTV3.SA: possibly delisted; no price data found  (1d 2021-06-23 00:00:00 -> 2021-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1624417200, endDate = 1625108400")

1 Failed download:
['MOTV3.SA']: possibly delisted; no price data found  (1d 2021-06-23 00:00:00 -> 2021-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1624417200, endDate = 1625108400")
$MOTV3.SA: possibly delisted; no price data found  (1d 2021-09-23 00:00:00 -> 2021-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1632366000, endDate = 1633057200")

1 Failed download:
['MOTV3.SA']: possibly delisted; no price data found  (1d 2021-09-23 00:00:00 -> 2021-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1632366000, endDate = 1633057200")
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  40/197...

C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  60/197...

C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
$SMFT3.SA: possibly delisted; no price data found  (1d 2021-03-24 00:00:00 -> 2021-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1616554800, endDate = 1617246000")

1 Failed download:
['SMFT3.SA']: possibly delisted; no price data found  (1d 2021-03-24 00:00:00 -> 2021-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1616554800, endDate = 1617246000")
$SMFT3.SA: possibly delisted; no price data found  (1d 2021-06-23 00:00:00 -> 2021-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1624417200, endDate = 1625108400")

1 Failed download:
['SMFT3.SA']: possibly delisted; no price data found  (1d 2021-06-23 00:00:00 -> 2021-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1624417200, endDate = 1625108400")
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
$EMBJ3.SA: possibly delisted; no price data found  (1d 2021-03-24 00:00:00 -> 2021-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1616554800, endDate = 1617246000")

1 Failed download:
['EMBJ3.SA']: possibly delisted; no price data found  (1d 2021-03-24 00:00:00 -> 2021-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1616554800, endDate = 1617246000")
$EMBJ3.SA: possibly delisted; no price data found  (1d 2021-06-23 00:00:00 -> 2021-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1624417200, endDate = 1625108400")

1 Failed download:
['EMBJ3.SA']: possibly delisted; no price data found  (1d 2021-06-23 00:00:00 -> 2021-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1624417200, endDate = 1625108400")
$EMBJ3.SA: possibly delisted; no price data found  (1d 2021-09-23 00:00:00 -> 2021-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1632366000, endDate = 1633057200")

1 Failed download:
['EMBJ3.SA']: possibly delisted; no price data found  (1d 2021-09-23 00:00:00 -> 2021-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1632366000, endDate = 1633057200")
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  80/197...

C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
$RENT4.SA: possibly delisted; no price data found  (1d 2021-03-24 00:00:00 -> 2021-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1616554800, endDate = 1617246000")

1 Failed download:
['RENT4.SA']: possibly delisted; no price data found  (1d 2021-03-24 00:00:00 -> 2021-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1616554800, endDate = 1617246000")
$RENT4.SA: possibly delisted; no price data found  (1d 2021-06-23 00:00:00 -> 2021-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1624417200, endDate = 1625108400")

1 Failed download:
['RENT4.SA']: possibly delisted; no price data found  (1d 2021-06-23 00:00:00 -> 2021-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1624417200, endDate = 1625108400")
$RENT4.SA: possibly delisted; no price data found  (1d 2021-09-23 00:00:00 -> 2021-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1632366000, endDate = 1633057200")

1 Failed download:
['RENT4.SA']: possibly delisted; no price data found  (1d 2021-09-23 00:00:00 -> 2021-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1632366000, endDate = 1633057200")
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  100/197...

C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
$AURE3.SA: possibly delisted; no price data found  (1d 2021-03-24 00:00:00 -> 2021-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1616554800, endDate = 1617246000")

1 Failed download:
['AURE3.SA']: possibly delisted; no price data found  (1d 2021-03-24 00:00:00 -> 2021-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1616554800, endDate = 1617246000")
$AURE3.SA: possibly delisted; no price data found  (1d 2021-06-23 00:00:00 -> 2021-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1624417200, endDate = 1625108400")

1 Failed download:
['AURE3.SA']: possibly delisted; no price data found  (1d 2021-06-23 00:00:00 -> 2021-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1624417200, endDate = 1625108400")
$AURE3.SA: possibly delisted; no price data found  (1d 2021-09-23 00:00:00 -> 2021-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1632366000, endDate = 1633057200")

1 Failed download:
['AURE3.SA']: possibly delisted; no price data found  (1d 2021-09-23 00:00:00 -> 2021-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1632366000, endDate = 1633057200")
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  120/197...

C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  140/197...

C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
$IGTI11.SA: possibly delisted; no price data found  (1d 2021-03-24 00:00:00 -> 2021-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1616554800, endDate = 1617246000")

1 Failed download:
['IGTI11.SA']: possibly delisted; no price data found  (1d 2021-03-24 00:00:00 -> 2021-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1616554800, endDate = 1617246000")
$IGTI11.SA: possibly delisted; no price data found  (1d 2021-06-23 00:00:00 -> 2021-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1624417200, endDate = 1625108400")

1 Failed download:
['IGTI11.SA']: possibly delisted; no price data found  (1d 2021-06-23 00:00:00 -> 2021-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1624417200, endDate = 1625108400")
$IGTI11.SA: possibly delisted; no price data found  (1d 2021-09-23 00:00:00 -> 2021-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1632366000, endDate = 1633057200")

1 Failed download:
['IGTI11.SA']: possibly delisted; no price data found  (1d 2021-09-23 00:00:00 -> 2021-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1632366000, endDate = 1633057200")
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  160/197...

C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
$NATU3.SA: possibly delisted; no price data found  (1d 2021-03-24 00:00:00 -> 2021-04-01 00:00:00)

1 Failed download:
['NATU3.SA']: possibly delisted; no price data found  (1d 2021-03-24 00:00:00 -> 2021-04-01 00:00:00)
$NATU3.SA: possibly delisted; no price data found  (1d 2021-06-23 00:00:00 -> 2021-07-01 00:00:00)

1 Failed download:
['NATU3.SA']: possibly delisted; no price data found  (1d 2021-06-23 00:00:00 -> 2021-07-01 00:00:00)
$NATU3.SA: possibly delisted; no price data found  (1d 2021-09-23 00:00:00 -> 2021-10-01 00:00:00)

1 Failed download:
['NATU3.SA']: possibly delisted; no price data found  (1d 2021-09-23 00:00:00 -> 2021-10-01 00:00:00)
$CYRE4.SA: possibly delisted; no price data found  (1d 2021-03-24 00:00:00 -> 2021-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1616554800, endDate = 1617246000")

1 Failed download:
['CYRE4.SA']: possibly delisted; no price data found  (1d 2021-03-24 00:00:00 -> 2021-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1616554800, endDate = 1617246000")
$CYRE4.SA: possibly delisted; no price data found  (1d 2021-06-23 00:00:00 -> 2021-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1624417200, endDate = 1625108400")

1 Failed download:
['CYRE4.SA']: possibly delisted; no price data found  (1d 2021-06-23 00:00:00 -> 2021-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1624417200, endDate = 1625108400")
$CYRE4.SA: possibly delisted; no price data found  (1d 2021-09-23 00:00:00 -> 2021-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1632366000, endDate = 1633057200")

1 Failed download:
['CYRE4.SA']: possibly delisted; no price data found  (1d 2021-09-23 00:00:00 -> 2021-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1632366000, endDate = 1633057200")
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  180/197...

C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

Com preço: 174/197
Com ações: 197/197
COLUNAS DF
['ativo', 'dt_refer', 'caixa', 'ativo_total', 'divida_cp', 'divida_lp', 'pl', 'receita', 'ebit', 'lucro', 'ticker', 'divida_bruta', 'divida_liquida', 'cap_investido', 'ROIC', 'ROE', 'margem_liq', 'div_ebitda', 'ROA', 'giro_ativo', 'alavancagem', 'preco', 'cnpj_norm', 'acoes_circ', 'valor_mercado', 'EV', 'earnings_yield']

======================================================================
RESULTADO FINAL
======================================================================
Total linhas:  197
Empresas:      66
Tickers:       66
Com EV:        174
Com EY:        174

                               ativo   dt_refer     caixa  ativo_total  divida_cp  divida_lp         pl  receita      ebit     lucro ticker  divida_bruta  divida_liquida  cap_investido     ROIC      ROE  margem_liq  div_ebitda      ROA  giro_ativo  alavancagem     preco      cnpj_norm  acoes_circ  valor_mercado           EV  earnings_yield
CENTRAIS ELET BRAS S.A. - ELETROBRAS 2021-03-31 3786870.0  130543182.0  8183024.0 19893470.0 72815673.0  90281.0 2012747.0 1601068.0  AXIA6    28076494.0      24289624.0     97105297.0 0.020727 0.021988   17.734274   13.949341 0.012265    0.000692     0.215074 19.405319 00001180000126  1568930910   3.044561e+10 3.046989e+10        0.000066
CENTRAIS ELET BRAS S.A. - ELETROBRAS 2021-06-30 4472390.0  134412580.0  8634114.0 19825543.0 75253579.0  98128.0 1884346.0 2518871.0  AXIA6    28459657.0      23987267.0     99240846.0 0.018988 0.033472   25.669238   15.103201 0.018740    0.000730     0.211734 25.034348 00001180000126  1568930910   3.927716e+10 3.930115e+10        0.000048
CENTRAIS ELET BRAS S.A. - ELETROBRAS 2021-09-30 5598933.0  142697356.0  9017426.0 19682340.0 76128510.0 283936.0 1737168.0  923845.0  AXIA6    28699766.0      23100833.0     99229343.0 0.017507 0.012135    3.253709   16.521008 0.006474    0.001990     0.201123 22.401897 00001180000126     1568931   3.514703e+07 5.824786e+07        0.029824
                       ENERGISA S.A. 2021-03-31  221049.0   14292662.0  1785055.0  3452920.0  7459190.0  54461.0  597502.0  819763.0 ENGI11     5237975.0       5016926.0     12476116.0 0.047892 0.109900   15.052294    8.766456 0.057356    0.003810     0.366480 32.068058 00864214000106  1814561910   5.818948e+10 5.819449e+10        0.000010
                       ENERGISA S.A. 2021-06-30  196775.0   15073463.0  1062298.0  3618092.0  8190540.0  59392.0  635463.0  679833.0 ENGI11     4680390.0       4483615.0     12674155.0 0.050138 0.083002   11.446542    7.365323 0.045101    0.003940     0.310505 32.869228 00864214000106  1814561910   5.964325e+10 5.964773e+10        0.000011
                       ENERGISA S.A. 2021-09-30   68550.0   15996688.0  1075169.0  3923279.0  8748262.0  61191.0  741834.0  796450.0 ENGI11     4998448.0       4929898.0     13678160.0 0.054235 0.091041   13.015803    6.737960 0.049788    0.003825     0.312468 31.692347 00864214000106  1809942725   5.736133e+10 5.736626e+10        0.000013
                   PORTO SEGURO S.A. 2021-03-31   28101.0    9818717.0        0.0        0.0  8682598.0      0.0  276565.0  294669.0  PSSA3           0.0        -28101.0      8654497.0 0.031956 0.033938         inf    0.000000 0.030011    0.000000     0.000000 17.682730 02149205000169      319924   5.657130e+06 5.629029e+06        0.049132
                   PORTO SEGURO S.A. 2021-06-30  113174.0    9886972.0        0.0        0.0  9333191.0      0.0  604821.0  656670.0  PSSA3           0.0       -113174.0      9220017.0 0.065599 0.070359         inf    0.000000 0.066418    0.000000     0.000000 20.854942 02149205000169      319924   6.671997e+06 6.558823e+06        0.092215
                   PORTO SEGURO S.A. 2021-09-30  101716.0    9874375.0        0.0        0.0  9069148.0      0.0   95480.0   60104.0  PSSA3           0.0       -101716.0      8967432.0 0.010647 0.006627         inf    0.000000 0.006087    0.000000     0.000000 19.550764 02149205000169      319924   6.254759e+06 6.153043e+06        0.015518
                           RUMO S.A. 2021-03-31  127343.0   22642533.0   310088.0  4975425.0 15133216.0 149642.0  224911.0  172248.0  RAIL3     5285513.0       5158170.0     20291386.0 0.011084 0.011382    1.151067   23.500465 0.007607    0.006609     0.233433 19.097769 02387241000160  1852071791   3.537044e+10 3.537560e+10        0.000006
                           RUMO S.A. 2021-06-30  103685.0   22607615.0   280464.0  4562641.0 15449257.0 226912.0  378517.0  312137.0  RAIL3     4843105.0       4739420.0     20188677.0 0.018749 0.020204    1.375586   12.794947 0.013807    0.010037     0.214224 18.060358 02387241000160  1852435179   3.345564e+10 3.346038e+10        0.000011
                           RUMO S.A. 2021-09-30  970192.0   23269767.0   309758.0  5418470.0 15208901.0 190916.0  123788.0   51039.0  RAIL3     5728228.0       4758036.0     19966937.0 0.006200 0.003356    0.267337   46.274502 0.002193    0.008204     0.246166 15.834647 02387241000160  1853282576   2.934608e+10 2.935083e+10        0.000004

Salvo: ibovespa_magic_formula_2021.xlsx

C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_13204\2903193754.py:192: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df_cap['dt_refer']   = pd.to_datetime(df_cap['DT_REFER'], dayfirst=True).dt.strftime('%Y-%m-%d')

Como a Magic Formula Original Funciona

Rankeia todas as ações pelo Earnings Yield (maior → melhor → ranking 1, 2, 3...)
Rankeia todas as ações pelo ROIC (maior → melhor → ranking 1, 2, 3...)
Soma os rankings (não os valores)
Seleciona as top 20-30 com menor ranking combinado