In [143]:
import pandas as pd
import numpy as np
import random
import pyomo.environ as pyo
from pyomo.environ import *
from pyomo.environ import SolverFactory
import yfinance as yf
import matplotlib.pyplot as plt

In [144]:
custo_transporte = pd.read_excel('exerc8.xlsx', sheet_name='custo_transporte')
quantidade_produzida = pd.read_excel('exerc8.xlsx', sheet_name='quantidade_produzida')
demanda_consumidor = pd.read_excel('exerc8.xlsx', sheet_name='demanda_consumidor')

In [145]:
custo_transporte = custo_transporte.drop(columns=['Unidade']).set_index('Produtor')
print(custo_transporte.columns)
custo_transporte.head()

Index(['Mercosul', 'Chile', 'UE', 'Japão', 'Ásia/Pacífico'], dtype='object')

          Mercosul  Chile   UE  Japão  Ásia/Pacífico
Produtor
SP I            52     77  145    280            267
SP II           60     85  150    285            272
NE             110    135  115    301            287

In [146]:
quantidade_produzida=quantidade_produzida.set_index('Produtor')
quantidade_produzida.head()

          Produção
Produtor
SP I           771
SP II          964
NE             193

In [147]:
demanda_consumidor=demanda_consumidor.T
demanda_consumidor = demanda_consumidor[0][2:-1]

## APRENDER A TRANSFORMAR DF IN DICIO

In [148]:
dicio_custo = custo_transporte.T.to_dict()
dicio_quantidade_produzida = quantidade_produzida.T.to_dict()
dicio_demanda_consumidor = demanda_consumidor.to_dict()

In [149]:
lista_produtor = custo_transporte.index
lista_consumidores = custo_transporte.columns

In [150]:
dicio_demanda_consumidor['UE']

1680

In [151]:
model = pyo.ConcreteModel()

model.lista_produtor = pyo.Set(initialize=lista_produtor)
model.lista_consumidores = pyo.Set(initialize=lista_consumidores)

model.x = pyo.Var(model.lista_produtor, model.lista_consumidores, bounds=(0, None), domain=pyo.NonNegativeIntegers)

#objetivo
def objetivo(model):

    return sum(model.x[p,c] * dicio_custo[p][c] for p in model.lista_produtor for c in model.lista_consumidores )
model.objetivo = pyo.Objective(rule=objetivo, sense=pyo.minimize)

#Restrição
def maxima_producao_por_produtora(model,p):
    
    return sum(model.x[p,c] for c in lista_consumidores) == dicio_quantidade_produzida[p]['Produção']
model.maxima_producao_por_produtora = pyo.Constraint(model.lista_produtor, rule=maxima_producao_por_produtora)

def demanda_consumidor(model, c):
   
    return  sum(model.x[p,c] for p in model.lista_produtor) == dicio_demanda_consumidor[c]
model.demanda_consumidor = pyo.Constraint(model.lista_consumidores, rule=demanda_consumidor)

In [152]:
model.pprint()

2 Set Declarations
    lista_consumidores : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :    5 : {'Mercosul', 'Chile', 'UE', 'Japão', 'Ásia/Pacífico'}
    lista_produtor : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :    3 : {'SP I', 'SP II', 'NE'}

1 Var Declarations
    x : Size=15, Index=lista_produtor*lista_consumidores
        Key                        : Lower : Value : Upper : Fixed : Stale : Domain
                   ('NE', 'Chile') :     0 :  None :  None : False :  True : NonNegativeIntegers
                   ('NE', 'Japão') :     0 :  None :  None : False :  True : NonNegativeIntegers
                ('NE', 'Mercosul') :     0 :  None :  None : False :  True : NonNegativeIntegers
                      ('NE', 'UE') :     0 :  None :  None : False :  True : NonNegativeIntegers
           ('NE', 'Ásia/Pacífico') :     0 :  None :  None : False :  True : NonNegativeIntegers
                 ('SP I', 'Chile') :     0 :  None :  None : False :  True : NonNegativeIntegers
                 ('SP I', 'Japão') :     0 :  None :  None : False :  True : NonNegativeIntegers
              ('SP I', 'Mercosul') :     0 :  None :  None : False :  True : NonNegativeIntegers
                    ('SP I', 'UE') :     0 :  None :  None : False :  True : NonNegativeIntegers
         ('SP I', 'Ásia/Pacífico') :     0 :  None :  None : False :  True : NonNegativeIntegers
                ('SP II', 'Chile') :     0 :  None :  None : False :  True : NonNegativeIntegers
                ('SP II', 'Japão') :     0 :  None :  None : False :  True : NonNegativeIntegers
             ('SP II', 'Mercosul') :     0 :  None :  None : False :  True : NonNegativeIntegers
                   ('SP II', 'UE') :     0 :  None :  None : False :  True : NonNegativeIntegers
        ('SP II', 'Ásia/Pacífico') :     0 :  None :  None : False :  True : NonNegativeIntegers

1 Objective Declarations
    objetivo : Size=1, Index=None, Active=True
        Key  : Active : Sense    : Expression
        None :   True : minimize : 52*x[SP I,Mercosul] + 77*x[SP I,Chile] + 145*x[SP I,UE] + 280*x[SP I,Japão] + 267*x[SP I,Ásia/Pacífico] + 60*x[SP II,Mercosul] + 85*x[SP II,Chile] + 150*x[SP II,UE] + 285*x[SP II,Japão] + 272*x[SP II,Ásia/Pacífico] + 110*x[NE,Mercosul] + 135*x[NE,Chile] + 115*x[NE,UE] + 301*x[NE,Japão] + 287*x[NE,Ásia/Pacífico]

2 Constraint Declarations
    demanda_consumidor : Size=5, Index=lista_consumidores, Active=True
        Key           : Lower  : Body                                                                 : Upper  : Active
                Chile :    7.0 :                         x[SP I,Chile] + x[SP II,Chile] + x[NE,Chile] :    7.0 :   True
                Japão :  159.0 :                         x[SP I,Japão] + x[SP II,Japão] + x[NE,Japão] :  159.0 :   True
             Mercosul :   18.0 :                x[SP I,Mercosul] + x[SP II,Mercosul] + x[NE,Mercosul] :   18.0 :   True
                   UE : 1680.0 :                                  x[SP I,UE] + x[SP II,UE] + x[NE,UE] : 1680.0 :   True
        Ásia/Pacífico :   64.0 : x[SP I,Ásia/Pacífico] + x[SP II,Ásia/Pacífico] + x[NE,Ásia/Pacífico] :   64.0 :   True
    maxima_producao_por_produtora : Size=3, Index=lista_produtor, Active=True
        Key   : Lower : Body                                                                                       : Upper : Active
           NE : 193.0 :                x[NE,Mercosul] + x[NE,Chile] + x[NE,UE] + x[NE,Japão] + x[NE,Ásia/Pacífico] : 193.0 :   True
         SP I : 771.0 :      x[SP I,Mercosul] + x[SP I,Chile] + x[SP I,UE] + x[SP I,Japão] + x[SP I,Ásia/Pacífico] : 771.0 :   True
        SP II : 964.0 : x[SP II,Mercosul] + x[SP II,Chile] + x[SP II,UE] + x[SP II,Japão] + x[SP II,Ásia/Pacífico] : 964.0 :   True

6 Declarations: lista_produtor lista_consumidores x objetivo maxima_producao_por_produtora demanda_consumidor

In [153]:
opt = SolverFactory('cplex')
resultado = opt.solve(model)

In [154]:
for p in model.lista_produtor:
    for c in model.lista_consumidores:
        print(f'{p,c}: ',pyo.value(model.x[p,c]))

('SP I', 'Mercosul'):  18.0
('SP I', 'Chile'):  7.0
('SP I', 'UE'):  746.0
('SP I', 'Japão'):  0.0
('SP I', 'Ásia/Pacífico'):  0.0
('SP II', 'Mercosul'):  0.0
('SP II', 'Chile'):  0.0
('SP II', 'UE'):  741.0
('SP II', 'Japão'):  159.0
('SP II', 'Ásia/Pacífico'):  64.0
('NE', 'Mercosul'):  0.0
('NE', 'Chile'):  0.0
('NE', 'UE'):  193.0
('NE', 'Japão'):  0.0
('NE', 'Ásia/Pacífico'):  0.0