In [13]:
import os
from brapi import Brapi
from dotenv import load_dotenv
import pandas as pd
import requests
import json

from pathlib import Path

In [14]:
# DRE
#   - lucro liq = netIncome
#   - depreciacao = otherOperatingExpenses + costOfRevenue
#   - Margem bruta = grossProfit / totalRevenue
#   - Giro ativos = totalRevenue / ativo total(bp)

# Bp
#   - Ativo total = Cash + shortTermInvestments
#   - Clientes = netReceivables
#   - Estoques = inventory
#   - Fornecedores = providers
#   - Dívida = longTermLoansAndFinancing
#   - Liquidez Corrente  = totalCurrentAssets / currentLiabilities
#   - Giro ativos = totalrevenue(dre) / totalAssets


# Estatística
#   - Diluição = sharesOutstanding

In [15]:


lista_df = []
for filename in os.listdir('dre'):
    
    # 2. Reconstruct the full absolute or relative path to the file
    try:
        full_path_balanco = os.path.join('balanco', filename)
        full_path_dre = os.path.join('dre', filename)
        full_path_estatistica = os.path.join('estatistica', filename)
        full_path_caixa = os.path.join('caixa', filename)
        full_path_financeiros = os.path.join('financeiros', filename)


        df_balanco = pd.read_csv(full_path_balanco)
        df_dre = pd.read_csv(full_path_dre)
        df_estatistica = pd.read_csv(full_path_estatistica)
        df_caixa = pd.read_csv(full_path_caixa)
        df_financeiro = pd.read_csv(full_path_financeiros)


        df_dre = df_dre[['endDate','netIncome','otherOperatingExpenses','costOfRevenue','grossProfit','totalRevenue']]
        df_balanco= df_balanco[['endDate','cash','shortTermInvestments','netReceivables','inventory','providers','longTermLoansAndFinancing','totalCurrentAssets','currentLiabilities','totalAssets']]
        df_estatistica= df_estatistica[['endDate','sharesOutstanding']]
        df_caixa = df_caixa[['endDate','operatingCashFlow']]
        df_financeiro = df_financeiro[['endDate','returnOnAssets','currentRatio','grossMargins']]

        df_merge = df_balanco.merge(df_dre, on='endDate').merge(df_estatistica, on='endDate').merge(df_caixa, on='endDate').merge(df_financeiro, on='endDate').copy()

        # df_merge['capital_investido'] = df_merge['totalCurrentAssets'].fillna(0) - df_merge['currentLiabilities'].fillna(0) + df_merge['propertyPlantEquipment'].fillna(0)
        # df_merge['ROC'] = df_merge['ebit'] / df_merge['capital_investido']
        # df_merge['EY']  = df_merge['ebit'] / df_merge['enterpriseValue'] # 
        
        dicio_merge = {
            'ativo':filename,
            'data':df_merge
        }
        lista_df.append(dicio_merge)
    except Exception as e:
        print(e)
        continue

In [16]:
lista_df[60]['data']

,endDate,cash,shortTermInvestments,netReceivables,inventory,providers,longTermLoansAndFinancing,totalCurrentAssets,currentLiabilities,totalAssets,netIncome,otherOperatingExpenses,costOfRevenue,grossProfit,totalRevenue,sharesOutstanding,operatingCashFlow,returnOnAssets,currentRatio,grossMargins
0,2025-12-31,1322044000,2799536100,1989613000,0,5872330000,17607242000,7053343700,12686994000,34925260000,318364000,-125828000,-9909816000,4762238000,14672054000,152068530,1390409000,0.009116,0.555951,0.324579
1,2024-12-31,677895000,3613468000,1441650000,0,5348501000,18114908000,6950874000,9252585000,30573857000,231492990,-153019010,-9465403000,4015867000,13481270000,343109900,-2514109000,0.007572,0.751236,0.297885
2,2023-12-31,133394000,2865358000,1343672100,0,4813621000,14017987000,5429325000,7455025000,25119492000,-650851000,-205330000,-7573494000,2768521000,10342015000,362302080,3227151900,-0.025910,0.728277,0.267696
3,2022-12-31,551765000,6275771000,1173853000,0,2306508000,15680659000,9440252000,5896026000,26248880000,556406000,-165003010,-5994481000,3605548000,9600029000,362302080,-4171865000,0.021197,1.601121,0.375577
4,2021-12-31,146030000,7640423000,879885000,0,2316751900,14007574000,9146959000,3751193000,21715853000,819439000,-99216000,-2946075000,2386548000,5332623000,362302080,-8269520000,0.037735,2.438413,0.447537
5,2020-12-31,68647000,1623860000,455421000,0,1321967000,3459396000,2380202000,2448236000,8502627000,109027000,-79808000,-3219781000,865478000,4085259000,298921020,-634250000,0.012823,0.972211,0.211854
6,2019-12-31,72233000,974872000,539263000,0,1404469000,2496973000,1949183000,2239379000,7242817000,227815010,-11305000,-2896435000,939609000,3836044000,298921020,-1132708000,0.031454,0.870412,0.244942
7,2018-12-31,259482000,552669000,351896000,0,972671000,1782552100,1435941000,1642881000,5192301000,159754000,0,-1731963000,806636030,2538599000,263421010,-1018773000,0.030767,0.874038,0.317749
8,2017-12-31,411381000,372228000,157920990,0,716062000,1037411970,1161338000,1615777000,4006470000,66466000,0,-1823113000,644870000,2467983000,213491580,-1020472000,0.016590,0.718749,0.261294
9,2016-12-31,53576000,69935000,215516000,0,848919000,529029000,565338000,1497200000,2789713000,39697000,-161000,-1448915000,444265000,1893180000,213491580,-204447010,0.014230,0.377597,0.234666
10,2015-12-31,460579000,23337000,179542000,0,335761000,557379970,777773000,1117336100,2618609000,67050000,-837000,-948187000,265315010,1213502000,0,208632990,0.025605,0.696096,0.218636
11,2014-12-31,15544000,47771000,94092000,0,474117000,155911010,240432000,572083000,1373003000,4766000,-29000,-39252000,21011000,60263000,152068530,146652990,0.003471,0.420275,0.348655

In [17]:
lista_df[60]['data']

,endDate,cash,shortTermInvestments,netReceivables,inventory,providers,longTermLoansAndFinancing,totalCurrentAssets,currentLiabilities,totalAssets,netIncome,otherOperatingExpenses,costOfRevenue,grossProfit,totalRevenue,sharesOutstanding,operatingCashFlow,returnOnAssets,currentRatio,grossMargins
0,2025-12-31,1322044000,2799536100,1989613000,0,5872330000,17607242000,7053343700,12686994000,34925260000,318364000,-125828000,-9909816000,4762238000,14672054000,152068530,1390409000,0.009116,0.555951,0.324579
1,2024-12-31,677895000,3613468000,1441650000,0,5348501000,18114908000,6950874000,9252585000,30573857000,231492990,-153019010,-9465403000,4015867000,13481270000,343109900,-2514109000,0.007572,0.751236,0.297885
2,2023-12-31,133394000,2865358000,1343672100,0,4813621000,14017987000,5429325000,7455025000,25119492000,-650851000,-205330000,-7573494000,2768521000,10342015000,362302080,3227151900,-0.025910,0.728277,0.267696
3,2022-12-31,551765000,6275771000,1173853000,0,2306508000,15680659000,9440252000,5896026000,26248880000,556406000,-165003010,-5994481000,3605548000,9600029000,362302080,-4171865000,0.021197,1.601121,0.375577
4,2021-12-31,146030000,7640423000,879885000,0,2316751900,14007574000,9146959000,3751193000,21715853000,819439000,-99216000,-2946075000,2386548000,5332623000,362302080,-8269520000,0.037735,2.438413,0.447537
5,2020-12-31,68647000,1623860000,455421000,0,1321967000,3459396000,2380202000,2448236000,8502627000,109027000,-79808000,-3219781000,865478000,4085259000,298921020,-634250000,0.012823,0.972211,0.211854
6,2019-12-31,72233000,974872000,539263000,0,1404469000,2496973000,1949183000,2239379000,7242817000,227815010,-11305000,-2896435000,939609000,3836044000,298921020,-1132708000,0.031454,0.870412,0.244942
7,2018-12-31,259482000,552669000,351896000,0,972671000,1782552100,1435941000,1642881000,5192301000,159754000,0,-1731963000,806636030,2538599000,263421010,-1018773000,0.030767,0.874038,0.317749
8,2017-12-31,411381000,372228000,157920990,0,716062000,1037411970,1161338000,1615777000,4006470000,66466000,0,-1823113000,644870000,2467983000,213491580,-1020472000,0.016590,0.718749,0.261294
9,2016-12-31,53576000,69935000,215516000,0,848919000,529029000,565338000,1497200000,2789713000,39697000,-161000,-1448915000,444265000,1893180000,213491580,-204447010,0.014230,0.377597,0.234666
10,2015-12-31,460579000,23337000,179542000,0,335761000,557379970,777773000,1117336100,2618609000,67050000,-837000,-948187000,265315010,1213502000,0,208632990,0.025605,0.696096,0.218636
11,2014-12-31,15544000,47771000,94092000,0,474117000,155911010,240432000,572083000,1373003000,4766000,-29000,-39252000,21011000,60263000,152068530,146652990,0.003471,0.420275,0.348655

In [18]:
lista_df[0]['data'].columns

Index(['endDate', 'cash', 'shortTermInvestments', 'netReceivables',
       'inventory', 'providers', 'longTermLoansAndFinancing',
       'totalCurrentAssets', 'currentLiabilities', 'totalAssets', 'netIncome',
       'otherOperatingExpenses', 'costOfRevenue', 'grossProfit',
       'totalRevenue', 'sharesOutstanding', 'operatingCashFlow',
       'returnOnAssets', 'currentRatio', 'grossMargins'],
      dtype='str')

In [19]:
from matplotlib import axis
from scipy.datasets import ascent


for i in range(len(lista_df)):
    # print(lista_df[i]['ativo'])
    ativo = lista_df[i]['ativo']
    df = lista_df[i]['data']
    # df = df.sort_index(axis=0, ascending=False)
    df = df[::-1]
    #   grupo 1 - Rentabilidade - Lucratividade
    df['ROA'] = (df['returnOnAssets']>0).astype(int)
    df['Qualidade_ROA'] = (df['returnOnAssets'].diff(1)>0).astype(int)
    df['FCO'] = (df['operatingCashFlow']>0).astype(int)
    df['Qualidade_FCO'] = (df['operatingCashFlow'].diff(1)>0).astype(int)

    #   grupo 2 - Alavancagem, Liquidez e Financiamento
    df['Reducao_DIVIDA'] = (df['longTermLoansAndFinancing'].diff(1)>0).astype(int)
    df['Liquidez_CORRENTE'] = (df['currentRatio'].diff(1)>0).astype(int)
    df['Diluicao'] = (df['sharesOutstanding'].diff(1)>0).astype(int)

    #   grupo 3 - Eficiência Operacional (Margem bruta, Giro de Ativos)
    df['Margem_BRUTA'] = (df['grossMargins'].diff(1)>0).astype(int)
    df['Giro_ATIVOS_conta'] = df['totalRevenue'] / df['totalAssets'] 
    df['Giro_ATIVOS'] = (df['Giro_ATIVOS_conta'].diff(1)>0).astype(int)

    #   TOTAL 9 
    
    df[ativo] = df[['ROA','Qualidade_ROA','FCO','Qualidade_FCO','Reducao_DIVIDA','Liquidez_CORRENTE','Diluicao','Margem_BRUTA','Giro_ATIVOS']].sum(axis=1)

    df = df[['endDate',ativo]]
    df=df[::-1]

    if len(df)>=10:
        df.to_csv(f'piotroski/{ativo}')

In [20]:
lista_df = []

for filename in os.listdir('piotroski'):
    # 2. Reconstruct the full absolute or relative path to the file
    full_path = os.path.join('piotroski', filename)
    
    # 3. Check if the current item is actually a file (and not a subfolder)
    # if os.path.isfile(full_path):
        
    #     # 4. Open and process the file safely
    #     with open(full_path, "r", encoding="utf-8") as file:
    #         content = file.read()
    #         print(f"--- Content of {filename} ---")
    #         print(pd.read_csv(full_path))
    dicio = {
        'ativo':filename,
        'data':pd.read_csv(full_path)
    }

    lista_df.append(dicio)

In [21]:
len(lista_df)

76

In [23]:
lista_df[0]['data']

    Unnamed: 0     endDate  ABEV3
0            0  2025-12-31      6
1            1  2024-12-31      6
2            2  2023-12-31      7
3            3  2022-12-31      6
4            4  2021-12-31      7
5            5  2020-12-31      4
6            6  2019-12-31      6
7            7  2018-12-31      6
8            8  2017-12-31      6
9            9  2016-12-31      4
10          10  2015-12-31      4
11          11  2014-12-31      6
12          12  2013-12-31      6
13          13  2012-12-31      2