In [2]:
import pandas as pd

In [3]:
DATA_PRINCIPAL = ['2025-03-31', '2025-06-30', '2025-09-30']

## BPA --------- FEITO

In [4]:
df = pd.read_csv('bpa-2025.csv', sep=';', encoding='latin-1')
df=df[df['ORDEM_EXERC'] == 'ÚLTIMO']

In [5]:
df

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
1,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2025-03-31,1,Ativo Total,2.427052e+09,S
3,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2025-03-31,1.01,Caixa e Equivalentes de Caixa,7.151083e+07,S
5,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2025-03-31,1.01.01,Caixa,2.836636e+07,S
7,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2025-03-31,1.01.02,Aplicações de Liquidez,4.314448e+07,S
9,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2025-03-31,1.02,Ativos Financeiros,2.160717e+09,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181025,97.837.181/0001-47,2025-09-30,1,DEXCO S.A.,21091,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2025-09-30,1.02.04.02.09,Goodwill na aquisição da Massima Revestimentos...,6.110000e+03,N
181027,97.837.181/0001-47,2025-09-30,1,DEXCO S.A.,21091,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2025-09-30,1.02.04.02.10,Goodwill na aquisição da Cecrisa Revestimentos...,1.684300e+05,N
181029,97.837.181/0001-47,2025-09-30,1,DEXCO S.A.,21091,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2025-09-30,1.02.04.02.11,Goodwill Viva Decora,0.000000e+00,N
181031,97.837.181/0001-47,2025-09-30,1,DEXCO S.A.,21091,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2025-09-30,1.02.04.02.12,Goodwill na aquisição da Castelatto 2022,4.667000e+04,N
181033,97.837.181/0001-47,2025-09-30,1,DEXCO S.A.,21091,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2025-09-30,1.02.04.02.13,Goodwill na aquisição da Guarani Florestal 2025,2.446000e+04,N

In [6]:
df['DT_REFER'].unique().tolist()

['2025-03-31',
 '2025-06-30',
 '2025-09-30',
 '2025-12-31',
 '2025-05-31',
 '2025-08-31',
 '2025-11-30']

In [5]:
lista_ativos = df['DENOM_CIA'].unique().tolist()
lista_final = []
data_refer = df['DT_REFER'].unique().tolist()
datas = df['DT_FIM_EXERC'].unique().tolist()
for ativo in lista_ativos:
    dfativo = df[df['DENOM_CIA']==ativo]
    
    caixa = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="1.01.01"')['VL_CONTA'].values
    ativo_total = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="1"')['VL_CONTA'].values
    

    if len(caixa) == 3 and len(ativo_total) == 3:
        dicio = {
            'ativo': ativo,
            
            f'caixa_{DATA_PRINCIPAL[0]}': caixa[0],
            f'caixa_{DATA_PRINCIPAL[1]}': caixa[1],
            f'caixa_{DATA_PRINCIPAL[2]}': caixa[2],
           

            f'ativo_total_{DATA_PRINCIPAL[0]}': ativo_total[0],
            f'ativo_total_{DATA_PRINCIPAL[1]}': ativo_total[1],
            f'ativo_total_{DATA_PRINCIPAL[2]}': ativo_total[2],
          

        
        }    
        lista_final.append(dicio)

In [6]:
df_bpa = pd.DataFrame(lista_final)
print(df_bpa.shape)
df_bpa.head()

(423, 7)

,ativo,caixa_2025-03-31,caixa_2025-06-30,caixa_2025-09-30,ativo_total_2025-03-31,ativo_total_2025-06-30,ativo_total_2025-09-30
0,BCO BRASIL S.A.,28366355.0,24468455.0,23732657.0,2.427052e+09,2.441421e+09,2.540770e+09
1,AXIA ENERGIA S.A.,23235009.0,22980254.0,18501361.0,2.820161e+08,2.749601e+08,2.665024e+08
2,COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB,681925.0,577724.0,486199.0,1.529712e+06,1.480516e+06,1.433244e+06
3,CARAMURU ALIMENTOS S.A.,1504595.0,760429.0,1846418.0,7.415662e+06,7.002071e+06,7.655100e+06
4,AUREN OPERAÇÕES S.A.,742038.0,1082926.0,977125.0,1.041356e+07,1.052999e+07,1.064951e+07

## BPP ------------ Fazendo

In [7]:
df2 = pd.read_csv('bpp-2025.csv', sep=';', encoding='latin-1')
df2=df2[df2['ORDEM_EXERC'] == 'ÚLTIMO']
df2.head()

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
1,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2025-03-31,2,Passivo Total,2.427052e+09,S
3,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2025-03-31,2.01,Passivos Financeiros Avaliados ao Valor Justo ...,5.098161e+06,S
5,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2025-03-31,2.02,Passivos Financeiros ao Custo Amortizado,2.135864e+09,S
7,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2025-03-31,2.02.01,Depósitos,8.649724e+08,S
9,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2025-03-31,2.02.02,Captações no Mercado Aberto,7.495654e+08,S

In [8]:
lista_ativos = df2['DENOM_CIA'].unique().tolist()
lista_final = []
data_refer = df2['DT_REFER'].unique().tolist()
datas = df2['DT_FIM_EXERC'].unique().tolist()
for ativo in lista_ativos:
    dfativo = df2[df2['DENOM_CIA']==ativo]
    # datas = dfativo['DT_REFER'].unique().tolist() 
    divida_cp = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="2.01.04"')['VL_CONTA'].values
    divida_lp = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="2.02.01"')['VL_CONTA'].values
    pl = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="2.03"')['VL_CONTA'].values

    if len(divida_cp) == 3 and len(divida_lp) == 3 and len(pl) == 3:
        dicio = {
            'ativo': ativo,
            
            f'divida_cp_{DATA_PRINCIPAL[0]}': divida_cp[0],
            f'divida_cp_{DATA_PRINCIPAL[1]}': divida_cp[1],
            f'divida_cp_{DATA_PRINCIPAL[2]}': divida_cp[2],
            
            
            f'divida_lp_{DATA_PRINCIPAL[0]}': divida_lp[0],
            f'divida_lp_{DATA_PRINCIPAL[1]}': divida_lp[1],
            f'divida_lp_{DATA_PRINCIPAL[2]}': divida_lp[2],
        
            
            f'pl_{DATA_PRINCIPAL[0]}': pl[0],
            f'pl_{DATA_PRINCIPAL[1]}': pl[1],
            f'pl_{DATA_PRINCIPAL[2]}': pl[2]
        
        }    
        lista_final.append(dicio)

In [9]:
df_bpp = pd.DataFrame(lista_final)
print(df_bpp.shape)
df_bpp.head()

(412, 10)

,ativo,divida_cp_2025-03-31,divida_cp_2025-06-30,divida_cp_2025-09-30,divida_lp_2025-03-31,divida_lp_2025-06-30,divida_lp_2025-09-30,pl_2025-03-31,pl_2025-06-30,pl_2025-09-30
0,AXIA ENERGIA S.A.,8750047.0,10944211.0,11210908.0,62313538.0,59345657.0,59625045.0,121577682.0,118754822.0,109340402.0
1,COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB,0.0,0.0,0.0,0.0,0.0,0.0,1377898.0,1318912.0,1247545.0
2,CARAMURU ALIMENTOS S.A.,1816453.0,1887354.0,1796545.0,1521246.0,1378235.0,1859507.0,2352745.0,2526941.0,2709193.0
3,AUREN OPERAÇÕES S.A.,1406119.0,1411244.0,1327750.0,3703186.0,3768827.0,3019375.0,3888873.0,3922687.0,4692809.0
4,"ARMAC LOCAÇÃO, LOGÍSTICA E SERVIÇOS S.A.",60100.0,95393.0,61861.0,2410424.0,2434294.0,2436423.0,1312437.0,1281222.0,1319396.0

## DRE ------------ Fazendo

In [10]:
df3 = pd.read_csv('dre-2025.csv', sep=';', encoding='latin-1')
df3=df3[df3['ORDEM_EXERC'] == 'ÚLTIMO']

In [11]:
print(df3.shape)
df3.head(200)

(78185, 15)

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
1,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-03-31,3.01,Receitas de Intermediação Financeira,71720089.0,S
3,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-03-31,3.01.01,Receita de Juros,71720089.0,N
5,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-03-31,3.02,Despesas de Intermediação Financeira,-47952209.0,S
7,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-03-31,3.02.01,Despesa de Juros,-47952209.0,N
9,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-03-31,3.03,Resultado Bruto de Intermediação Financeira,23767880.0,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,00.000.208/0001-00,2025-03-31,2,BRB BANCO DE BRASILIA S.A.,14206,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-03-31,3.04.03,Despesas com Pessoal,-383826.0,S
393,00.000.208/0001-00,2025-03-31,2,BRB BANCO DE BRASILIA S.A.,14206,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-03-31,3.04.04,Outras Despesas de Administrativas,-188478.0,S
395,00.000.208/0001-00,2025-03-31,2,BRB BANCO DE BRASILIA S.A.,14206,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-03-31,3.04.05,Despesas Tributárias,-86269.0,S
397,00.000.208/0001-00,2025-03-31,2,BRB BANCO DE BRASILIA S.A.,14206,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-03-31,3.04.06,Outras Receitas Operacionais,0.0,S
399,00.000.208/0001-00,2025-03-31,2,BRB BANCO DE BRASILIA S.A.,14206,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-03-31,3.04.07,Outras Despesas Operacionais,-111029.0,S

In [12]:
lista_ativos = df3['DENOM_CIA'].unique().tolist()
lista_final = []
for ativo in lista_ativos:
    dfativo = df3[df3['DENOM_CIA']==ativo]

    # RECEITA LIQUIDA 3.01

    dfativo_3_01 = dfativo[dfativo['CD_CONTA']=='3.01']
    datas_unicas_ini = dfativo_3_01['DT_INI_EXERC'].unique().tolist()
    datas_unicas_fim = dfativo_3_01['DT_FIM_EXERC'].unique().tolist()

    receita_liquida_total = []
    if len(datas_unicas_ini) == 3 and len(datas_unicas_fim) == 3:
        for i in range(len(datas_unicas_ini)):
            data_ini = datas_unicas_ini[i]
            data_fim = datas_unicas_fim[i]
            # print(f'Para o ativo {ativo}, a Data de início é {data_ini} e a data de fim é {data_fim}.')
            receita_liquida = dfativo_3_01.query('DT_INI_EXERC==@data_ini and DT_FIM_EXERC==@data_fim')['VL_CONTA'].values
            receita_liquida_total.extend(receita_liquida)
    
    # EBIT 3.05

    dfativo_3_05 = dfativo[dfativo['CD_CONTA']=='3.05']
    datas_unicas_ini_3_05 = dfativo_3_05['DT_INI_EXERC'].unique().tolist()
    datas_unicas_fim_3_05 = dfativo_3_05['DT_FIM_EXERC'].unique().tolist() 
    ebit_total = []
    if len(datas_unicas_ini_3_05) == 3 and len(datas_unicas_fim_3_05) == 3:
        for i in range(len(datas_unicas_ini_3_05)):
            data_ini = datas_unicas_ini_3_05[i]
            data_fim = datas_unicas_fim_3_05[i]
            # print(f'Para o ativo {ativo}, a Data de início é {data_ini} e a data de fim é {data_fim}.')
            ebit = dfativo_3_05.query('DT_INI_EXERC==@data_ini and DT_FIM_EXERC==@data_fim')['VL_CONTA'].values
            ebit_total.extend(ebit)

    #  LUCRO LIQUIDO 3.11

    dfativo_3_11 = dfativo[dfativo['CD_CONTA']=='3.11']
    datas_unicas_ini_3_11 = dfativo_3_11['DT_INI_EXERC'].unique().tolist()
    datas_unicas_fim_3_11 = dfativo_3_11['DT_FIM_EXERC'].unique().tolist() 
    lucro_liquido_total = []
    if len(datas_unicas_ini_3_11) == 3  and len(datas_unicas_fim_3_11) == 3:
        for i in range(len(datas_unicas_ini_3_11)):
            data_ini = datas_unicas_ini_3_11[i]
            data_fim = datas_unicas_fim_3_11[i]
            # print(f'Para o ativo {ativo}, a Data de início é {data_ini} e a data de fim é {data_fim}.')
            lucro_liquido = dfativo_3_11.query('DT_INI_EXERC==@data_ini and DT_FIM_EXERC==@data_fim')['VL_CONTA'].values
            lucro_liquido_total.extend(lucro_liquido)

    # print(f'Ativo: {ativo}')
    # print(f'Receita Líquida: {receita_liquida_total}')
    # print(f'EBIT: {ebit_total}')
    # print(f'Lucro Líquido: {lucro_liquido_total}')
    # print('-----------------------------')

    if len(receita_liquida_total) == 3 and len(ebit_total) == 3 and len(lucro_liquido_total) == 3:  
        dicio ={
            'ativo': ativo,
            f'receita_liquida_{DATA_PRINCIPAL[0]}': receita_liquida_total[0],
            f'receita_liquida_{DATA_PRINCIPAL[1]}': receita_liquida_total[1],
            f'receita_liquida_{DATA_PRINCIPAL[2]}': receita_liquida_total[2],

            f'ebit_{DATA_PRINCIPAL[0]}': ebit_total[0],
            f'ebit_{DATA_PRINCIPAL[1]}': ebit_total[1],
            f'ebit_{DATA_PRINCIPAL[2]}': ebit_total[2],

            f'lucro_liquido_{DATA_PRINCIPAL[0]}': lucro_liquido_total[0],
            f'lucro_liquido_{DATA_PRINCIPAL[1]}': lucro_liquido_total[1],
            f'lucro_liquido_{DATA_PRINCIPAL[2]}': lucro_liquido_total[2]
        }
        lista_final.append(dicio)

In [13]:
df_dre = pd.DataFrame(lista_final)
df_dre.head()

,ativo,receita_liquida_2025-03-31,receita_liquida_2025-06-30,receita_liquida_2025-09-30,ebit_2025-03-31,ebit_2025-06-30,ebit_2025-09-30,lucro_liquido_2025-03-31,lucro_liquido_2025-06-30,lucro_liquido_2025-09-30
0,BCO BRASIL S.A.,71720089.0,77532482.0,84767065.0,281839.0,1361531.0,929375.0,4177854.0,3582262.0,3006743.0
1,AXIA ENERGIA S.A.,10414179.0,10198955.0,10002503.0,3205299.0,127334.0,-2650621.0,-353614.0,-1325105.0,-5448117.0
2,COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB,135294.0,128514.0,123057.0,68140.0,54936.0,52379.0,64394.0,59286.0,53637.0
3,CARAMURU ALIMENTOS S.A.,1764715.0,1992560.0,2287804.0,58252.0,129986.0,270811.0,115708.0,174196.0,202252.0
4,AUREN OPERAÇÕES S.A.,831230.0,855338.0,935249.0,237966.0,149586.0,83253.0,13546.0,7137.0,14239.0

In [14]:
print(df_bpa.info())
print(df_bpp.info())
print(df_dre.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 423 entries, 0 to 422
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ativo                   423 non-null    object
 1   caixa_2025-03-31        423 non-null    float64
 2   caixa_2025-06-30        423 non-null    float64
 3   caixa_2025-09-30        423 non-null    float64
 4   ativo_total_2025-03-31  423 non-null    float64
 5   ativo_total_2025-06-30  423 non-null    float64
 6   ativo_total_2025-09-30  423 non-null    float64
dtypes: float64(6), object(1)
memory usage: 23.3+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 412 entries, 0 to 411
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ativo                 412 non-null    object
 1   divida_cp_2025-03-31  412 non-null    float64
 2   divida_cp_2025-06-30  412 non-null    float64
 3   divida_cp_2025-09-30  412 non-null    float64
 4   divida_lp_2025-03-31  412 non-null    float64
 5   divida_lp_2025-06-30  412 non-null    float64
 6   divida_lp_2025-09-30  412 non-null    float64
 7   pl_2025-03-31         412 non-null    float64
 8   pl_2025-06-30         412 non-null    float64
 9   pl_2025-09-30         412 non-null    float64
dtypes: float64(9), object(1)
memory usage: 32.3+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 428 entries, 0 to 427
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ativo                       428 non-null    object
 1   receita_liquida_2025-03-31  428 non-null    float64
 2   receita_liquida_2025-06-30  428 non-null    float64
 3   receita_liquida_2025-09-30  428 non-null    float64
 4   ebit_2025-03-31             428 non-null    float64
 5   ebit_2025-06-30             428 non-null    float64
 6   ebit_2025-09-30             428 non-null    float64
 7   lucro_liquido_2025-03-31    428 non-null    float64
 8   lucro_liquido_2025-06-30    428 non-null    float64
 9   lucro_liquido_2025-09-30    428 non-null    float64
dtypes: float64(9), object(1)
memory usage: 33.6+ KB
None

In [15]:
df_final = df_bpa.merge(df_bpp, on="ativo", how="inner") \
           .merge(df_dre, on="ativo", how="inner")

print(df_bpa.shape)
print(df_bpp.shape)
print(df_dre.shape)
print('----')
print(df_final.shape)

(423, 7)
(412, 10)
(428, 10)
----
(411, 25)

In [16]:
df_final.to_excel('resultado/dados_final_2025.xlsx', index=False)

## ------ FIMM DA RASPAGEM

## _____________________________

## -------- INICIO DAS FORMULAS (MAGIC FORMULA E PIOTROSKI)

In [17]:
df_final.head()

,ativo,caixa_2025-03-31,caixa_2025-06-30,caixa_2025-09-30,ativo_total_2025-03-31,ativo_total_2025-06-30,ativo_total_2025-09-30,divida_cp_2025-03-31,divida_cp_2025-06-30,divida_cp_2025-09-30,...,pl_2025-09-30,receita_liquida_2025-03-31,receita_liquida_2025-06-30,receita_liquida_2025-09-30,ebit_2025-03-31,ebit_2025-06-30,ebit_2025-09-30,lucro_liquido_2025-03-31,lucro_liquido_2025-06-30,lucro_liquido_2025-09-30
0,AXIA ENERGIA S.A.,23235009.0,22980254.0,18501361.0,282016140.0,274960124.0,266502447.0,8750047.0,10944211.0,11210908.0,...,109340402.0,10414179.0,10198955.0,10002503.0,3205299.0,127334.0,-2650621.0,-353614.0,-1325105.0,-5448117.0
1,COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB,681925.0,577724.0,486199.0,1529712.0,1480516.0,1433244.0,0.0,0.0,0.0,...,1247545.0,135294.0,128514.0,123057.0,68140.0,54936.0,52379.0,64394.0,59286.0,53637.0
2,CARAMURU ALIMENTOS S.A.,1504595.0,760429.0,1846418.0,7415662.0,7002071.0,7655100.0,1816453.0,1887354.0,1796545.0,...,2709193.0,1764715.0,1992560.0,2287804.0,58252.0,129986.0,270811.0,115708.0,174196.0,202252.0
3,AUREN OPERAÇÕES S.A.,742038.0,1082926.0,977125.0,10413555.0,10529993.0,10649506.0,1406119.0,1411244.0,1327750.0,...,4692809.0,831230.0,855338.0,935249.0,237966.0,149586.0,83253.0,13546.0,7137.0,14239.0
4,"ARMAC LOCAÇÃO, LOGÍSTICA E SERVIÇOS S.A.",470640.0,363919.0,512001.0,4575716.0,4585303.0,4633471.0,60100.0,95393.0,61861.0,...,1319396.0,439917.0,451467.0,494579.0,92427.0,82075.0,140264.0,12512.0,-6715.0,38304.0

In [18]:
import pandas as pd
import numpy as np


DATAS = ['2025-03-31', '2025-06-30', '2025-09-30']
resultados = []

for _, row in df_final.iterrows():
    empresa = row['ativo']
    
    for data in DATAS:
        try:
            # Contas do período
            caixa        = row[f'caixa_{data}']
            divida_cp    = row[f'divida_cp_{data}']
            divida_lp    = row[f'divida_lp_{data}']
            pl           = row[f'pl_{data}']
            ebit         = row[f'ebit_{data}']
            lucro        = row[f'lucro_liquido_{data}']
            receita      = row[f'receita_liquida_{data}']
            ativo_total  = row[f'ativo_total_{data}']

            divida_bruta    = divida_cp + divida_lp
            divida_liquida  = divida_bruta - caixa
            cap_investido   = pl + divida_liquida

            # ---- Indicadores calculáveis sem preço ----
            roic         = ebit / cap_investido   if cap_investido != 0  else np.nan
            roe          = lucro / pl             if pl != 0             else np.nan
            margem       = lucro / receita        if receita != 0        else np.nan
            div_ebitda   = divida_bruta / ebit    if ebit != 0           else np.nan  # proxy EBITDA≈EBIT por ora
            roa          = lucro / ativo_total    if ativo_total != 0    else np.nan

            resultados.append({
                'ativo':        empresa,
                'dt_refer':     data,
                'ebit':         ebit,
                'cap_investido': cap_investido,
                'ROIC':         roic,
                'ROE':          roe,
                'margem_liq':   margem,
                'div_ebitda':   div_ebitda,
                'ROA':          roa,
                # EV e Earnings Yield entram depois com o preço
                'EV':           np.nan,
                'earnings_yield': np.nan,
            })

        except Exception as e:
            print(f"Erro em {empresa} | {data}: {e}")

df_ind = pd.DataFrame(resultados)

# Remove cap_investido negativo (distorce ROIC — PL negativo)
df_ind = df_ind[df_ind['cap_investido'] > 0]

print(df_ind.shape)
print(df_ind[['ativo','dt_refer','ROIC','ROE','margem_liq']].head(10).to_string(index=False))

(1164, 11)
                                 ativo   dt_refer      ROIC       ROE  margem_liq
                     AXIA ENERGIA S.A. 2025-03-31  0.018921 -0.002909   -0.033955
                     AXIA ENERGIA S.A. 2025-06-30  0.000767 -0.011158   -0.129926
                     AXIA ENERGIA S.A. 2025-09-30 -0.016395 -0.049827   -0.544675
COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB 2025-03-31  0.097906  0.046734    0.475956
COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB 2025-06-30  0.074119  0.044951    0.461319
COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB 2025-09-30  0.068798  0.042994    0.435871
               CARAMURU ALIMENTOS S.A. 2025-03-31  0.013916  0.049180    0.065568
               CARAMURU ALIMENTOS S.A. 2025-06-30  0.025831  0.068936    0.087423
               CARAMURU ALIMENTOS S.A. 2025-09-30  0.059929  0.074654    0.088404
                  AUREN OPERAÇÕES S.A. 2025-03-31  0.028823  0.003483    0.016296

In [20]:
df_ind.head(500)

,ativo,dt_refer,ebit,cap_investido,ROIC,ROE,margem_liq,div_ebitda,ROA,EV,earnings_yield
0,AXIA ENERGIA S.A.,2025-03-31,3205299.0,169406258.0,0.018921,-0.002909,-0.033955,22.170657,-0.001254,NaN,NaN
1,AXIA ENERGIA S.A.,2025-06-30,127334.0,166064436.0,0.000767,-0.011158,-0.129926,552.011780,-0.004819,NaN,NaN
2,AXIA ENERGIA S.A.,2025-09-30,-2650621.0,161674994.0,-0.016395,-0.049827,-0.544675,-26.724286,-0.020443,NaN,NaN
3,COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB,2025-03-31,68140.0,695973.0,0.097906,0.046734,0.475956,0.000000,0.042096,NaN,NaN
4,COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB,2025-06-30,54936.0,741188.0,0.074119,0.044951,0.461319,0.000000,0.040044,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
511,"BRAZIL TOWER, CESSÃO DE INFRA-ESTRUTURAS S.A",2025-06-30,27820.0,975698.0,0.028513,-0.007151,-0.019757,37.622430,-0.000713,NaN,NaN
512,"BRAZIL TOWER, CESSÃO DE INFRA-ESTRUTURAS S.A",2025-09-30,26850.0,1030252.0,0.026062,0.036700,0.101974,38.330987,0.003827,NaN,NaN
513,HBR REALTY EMPREENDIMENTOS IMOBILIÁRIOS S.A.,2025-03-31,13709.0,4489144.0,0.003054,-0.009316,-0.598886,114.546867,-0.005328,NaN,NaN
514,HBR REALTY EMPREENDIMENTOS IMOBILIÁRIOS S.A.,2025-06-30,20827.0,4540795.0,0.004587,-0.010323,-0.470835,79.002305,-0.005789,NaN,NaN
515,HBR REALTY EMPREENDIMENTOS IMOBILIÁRIOS S.A.,2025-09-30,20766.0,4362251.0,0.004760,-0.010335,-0.453174,77.344746,-0.005724,NaN,NaN

In [21]:
def normalizar_cnpj(cnpj):
    if pd.isna(cnpj):
        return None
    return str(cnpj).replace('.','').replace('-','').replace('/','').strip().zfill(14)

import pandas as pd

# ================================================================
# RECOMEÇO LIMPO — um dicionário nome → ticker
# ================================================================

# 1) Carrega mapeamento da B3
df_ticker = pd.read_excel('mapeamento_ticker.xlsx')
df_ticker['cnpj_norm'] = df_ticker['cnpj'].apply(normalizar_cnpj)

# 2) Carrega CNPJ + nome do ITR
df_itr = pd.read_csv('bpa-2025.csv', sep=';', encoding='latin1')
cnpj_nome = df_itr[['CNPJ_CIA','DENOM_CIA']].drop_duplicates()
cnpj_nome.columns = ['cnpj', 'ativo']
cnpj_nome['cnpj_norm'] = cnpj_nome['cnpj'].apply(normalizar_cnpj)

# 3) Monta dicionário nome → ticker
MANUAL_COMPLETO = {
    "JBS S.A.":                                          "JBSS3",
    "BRF S.A.":                                          "BRFS3",
    "CIELO S.A. -  INSTITUIÇÃO DE PAGAMENTO":            "CIEL3",
    "NEOENERGIA S.A.":                                   "NEOE3",
    "LIGHT ENERGIA S.A.":                                "LIGT3",
    "MRS LOGISTICA S.A.":                                "MRSA3B",
    "VOTORANTIM CIMENTOS S.A.":                          "VCIM3",
    "ARTERIS S.A.":                                      "ARTR3",
    "EDP - ENERGIAS DO BRASIL S.A.":                     "ENBR3",
    "CPFL GERACAO DE ENERGIA S.A.":                      "CPFE3",
    "CPFL ENERGIAS RENOVÁVEIS S.A.":                     "CPRE3",
    "CPFL TRANSMISSÃO S.A.":                             "CPFE3",
    "CEMIG GERACAO E TRANSMISSAO S.A.":                  "CMIG3",
    "COPEL GERAÇÃO E TRANSMISSÃO S.A.":                  "CPLE3",
    "GOL LINHAS AEREAS INTELIGENTES S.A.":               "GOLL4",
    "ECORODOVIAS CONCESSÕES E SERVIÇOS S.A.":            "ECOR3",
    "PETRORECÔNCAVO S.A.":                               "RECV3",
    "ORIZON MEIO AMBIENTE S.A.":                         "ORVR3",
    "CLEAR SALE S.A.":                                   "CLSA3",
    "PRIO FORTE S.A.":                                   "PRIO3",
    "ELDORADO BRASIL CELULOSE S.A.":                     "ELDM3",
    "RAIZEN ENERGIA S.A.":                               "RAIZ4",
    "RAÍZEN S.A.":                                       "RAIZ4",
    "BR MALLS PARTICIPACOES S.A.":                       "BRML3",
    "NATURA &CO HOLDING S.A.":                           "NTCO3",
    "TIM BRASIL SERVIÇOS E PARTICIPAÇÕES S.A.":          "TIMS3",
    "SANTOS BRASIL PARTICIPACOES S.A.":                  "STBP3",
    "RUMO S.A.":                                         "RAIL3",
    "SUZANO S.A.":                                       "SUZB3",
    "ENGIE BRASIL ENERGIA S.A.":                         "EGIE3",
    "RAIA DROGASIL S.A.":                                "RADL3",
    "COSAN S.A.":                                        "CSAN3",
    "XP INVESTIMENTOS S.A.":                             "XPBR31",
    "BCO PAN S.A.":                                      "BPAN4",
    "BCO DAYCOVAL S.A.":                                 "DAYC4",
    "ALGAR TELECOM S/A":                                 "ALGT3",
    "ATACADÃO S.A.":                                     "CRFB3",
    "OI S.A. - EM RECUPERAÇÃO JUDICIAL":                 "OIBR3",
    "HYPERA S.A.":                                       "HYPE3",
    "IRANI PAPEL E EMBALAGEM S.A.":                      "RANI3",
    "TRÊS TENTOS AGROINDUSTRIAL S/A":                    "TTEN3",
    "WILSON SONS S.A.":                                  "PORT3",
    "UNIFIQUE TELECOMUNICAÇÕES S.A.":                    "FIQE3",
    "AEGEA SANEAMENTO E PARTICIPAÇÕES S.A.":             "AGYS3",
    "EUROFARMA LABORATÓRIOS S.A.":                       "EURO3",
    "IGUATEMI EMPRESA DE SHOPPING CENTERS S.A":          "IGTI3",
    "IRB - BRASIL RESSEGUROS S.A.":                      "IRBR3",
    "SENIOR SISTEMAS S.A.":                              "SNSY3",
    "POSITIVO TECNOLOGIA S.A.":                          "POSI3",
    "RANDONCORP S.A.":                                   "RAPT4",
    "VALID SOLUÇÕES S.A.":                               "VLID3",
    "ALPHAVILLE S.A.":                                   "AVLL3",
    "ENJOEI S.A.":                                       "ENJU3",
    "BB SEGURIDADE PARTICIPAÇÕES S.A.":                  "BBSE3",
    "LOCALIZA FLEET S.A.":                               "LCAM3",
    "AURA MINERALS INC.":                                "AURA33",
    "GRUPO CASAS BAHIA S.A.":                            "BHIA3",
    "SERENA ENERGIA S.A.":                               "SRNA3",
    "VITRU EDUCAÇÃO S.A.":                               "VTRU3",
    "SER EDUCACIONAL S.A.":                              "SEER3",
    "TRACK & FIELD CO S.A.":                             "TFCO4",
    "NEOGRID PARTICIPAÇÕES S.A.":                        "NGRD3",
    "MILLS LOCAÇÃO, SERVIÇOS E LOGÍSTICA S.A.":          "MILS3",
    "SBF COMÉRCIO DE PRODUTOS ESPORTIVOS S.A.":          "SBFG3",
    "ZAMP SA":                                           "ZAMP3",
    "ALLIED TECNOLOGIA S.A.":                            "ALLD3",
    "PATRIMAR ENGENHARIA S.A.":                          "PATC3",
    "ONCOCLÍNICAS DO BRASIL SERVIÇOS MÉDICOS S.A.":      "ONCO3",
    "KORA SAÚDE PARTICIPAÇÕES S.A.":                     "KRSA3",
    "ELETROMIDIA S.A.":                                  "ELMD3",
    "VITTIA S.A.":                                       "VITT3",
    "LUPO S.A.":                                         "LUPA3",
    "GPS PARTICIPAÇÕES E EMPREENDIMENTOS S.A.":          "GPSE3",
    "COMERC ENERGIA S.A.":                               "CERC3",
    "TC S.A.":                                           "TRAD3",
    "CESP - CIA ENERGETICA DE SAO PAULO":                "CESP6",
    "RODOBENS SA":                                       "RDNI3",
    "MONTEIRO ARANHA S.A.":                              "MOAR3",
    "INTER & CO, INC.":                                  "INBR32",
    "INFRACOMMERCE CXAAS S.A.":                          "IFCM3",
    "MONTE RODOVIAS S.A.":                               "MNTE3",
    "CARAMURU ALIMENTOS S.A.":                           "CRML3",
    "SOLAR BEBIDAS S.A.":                                "SOLB3",
    "COMPANHIA INDUSTRIAL CATAGUASES":                   "CATA4",
    "ALARES INTERNET PARTICIPAÇÕES S/A":                 "ALRS3",
    "COMPANHIA DE LOCAÇÃO DAS AMÉRICAS":                 "LCAM3",
}

# 4) Monta dicionário final nome → ticker
#    Prioridade: CNPJ > manual > None
dict_ticker = {}
dict_setor  = {}

for _, row in cnpj_nome.iterrows():
    nome = row['ativo']

    # Tenta CNPJ
    match = df_ticker[
        (df_ticker['cnpj_norm'] == row['cnpj_norm']) & 
        df_ticker['ticker'].notna()
    ]
    if not match.empty:
        dict_ticker[nome] = match.iloc[0]['ticker']
        dict_setor[nome]  = match.iloc[0]['setor_cvm']
        continue

    # Tenta manual
    if nome in MANUAL_COMPLETO:
        dict_ticker[nome] = MANUAL_COMPLETO[nome]
        dict_setor[nome]  = None
        continue

    dict_ticker[nome] = None
    dict_setor[nome]  = None

print(f"Total empresas: {len(dict_ticker)}")
print(f"Com ticker:     {sum(1 for v in dict_ticker.values() if v)}")
print(f"Sem ticker:     {sum(1 for v in dict_ticker.values() if not v)}")

# 5) Aplica no df_ind limpo — sem colunas duplicadas
df_ind = df_ind[['ativo','dt_refer','ebit','cap_investido',
                  'ROIC','ROE','margem_liq','div_ebitda','ROA',
                  'EV','earnings_yield']].copy()

df_ind['ticker']   = df_ind['ativo'].map(dict_ticker)
df_ind['setor_cvm'] = df_ind['ativo'].map(dict_setor)

# Remove sem ticker
df_ind = df_ind[df_ind['ticker'].notna()].reset_index(drop=True)

print(f"\ndf_ind final: {df_ind.shape}")
print(df_ind[['ativo','dt_refer','ticker','setor_cvm','ROIC','ROE']].head(6).to_string())

Total empresas: 458
Com ticker:     332
Sem ticker:     126

df_ind final: (846, 13)
                                    ativo    dt_refer ticker                           setor_cvm      ROIC       ROE
0                       AXIA ENERGIA S.A.  2025-03-31  AXIA3  Emp. Adm. Part. - Energia Elétrica  0.018921 -0.002909
1                       AXIA ENERGIA S.A.  2025-06-30  AXIA3  Emp. Adm. Part. - Energia Elétrica  0.000767 -0.011158
2                       AXIA ENERGIA S.A.  2025-09-30  AXIA3  Emp. Adm. Part. - Energia Elétrica -0.016395 -0.049827
3  COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB  2025-03-31  CEBR3                    Energia Elétrica  0.097906  0.046734
4  COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB  2025-06-30  CEBR3                    Energia Elétrica  0.074119  0.044951
5  COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB  2025-09-30  CEBR3                    Energia Elétrica  0.068798  0.042994

In [23]:
df_ind.shape

(846, 13)

## Filtra só ibov, ta mto dificil limpar os dados de todas as empresas, quero andar mais pra frente 
## e depois voltamos e ampliamos

In [24]:
lista_ativos = [
    "VALE3.SA", "ITUB4.SA", "PETR4.SA", "PETR3.SA", "AXIA3.SA", "BBDC4.SA", "SBSP3.SA", "B3SA3.SA",
    "ITSA4.SA", "BPAC11.SA", "WEGE3.SA", "BBAS3.SA", "EMBJ3.SA", "ABEV3.SA", "EQTL3.SA", "RENT3.SA",
    "RDOR3.SA", "ENEV3.SA", "PRIO3.SA", "VBBR3.SA", "SUZB3.SA", "RADL3.SA", "AXIA7.SA", "VIVT3.SA",
    "UGPA3.SA", "BBDC3.SA", "GGBR4.SA", "CPLE3.SA", "CMIG4.SA", "TIMS3.SA", "TOTS3.SA", "BBSE3.SA",
    "RAIL3.SA", "ENGI11.SA", "AXIA6.SA", "MOTV3.SA", "KLBN11.SA", "LREN3.SA", "ALOS3.SA", "MBRF3.SA",
    "SANB11.SA", "ASAI3.SA", "EGIE3.SA", "ISAE4.SA", "CSAN3.SA", "CSMG3.SA", "MULT3.SA", "CXSE3.SA",
    "SMFT3.SA", "TAEE11.SA", "PSSA3.SA", "CPFE3.SA", "CMIN3.SA", "BRAV3.SA", "CYRE3.SA", "GOAU4.SA",
    "FLRY3.SA", "NATU3.SA", "HYPE3.SA", "COGN3.SA", "CURY3.SA", "CSNA3.SA", "IGTI11.SA", "BRAP4.SA",
    "DIRR3.SA", "IRBR3.SA", "POMO4.SA", "MGLU3.SA", "MRVE3.SA", "VIVA3.SA", "AURE3.SA", "SLCE3.SA",
    "YDUQ3.SA", "AZZA3.SA", "RECV3.SA", "USIM5.SA", "HAPV3.SA", "CEAB3.SA", "BRKM5.SA", "BEEF3.SA",
    "RENT4.SA", "VAMO3.SA", "CYRE4.SA", "PCAR3.SA", "RAIZ4.SA",
]

In [2]:
import pandas as pd
import numpy as np
import yfinance as yf

def normalizar_cnpj(cnpj):
    if pd.isna(cnpj):
        return None
    return str(cnpj).replace('.','').replace('-','').replace('/','').strip().zfill(14)

# ================================================================
# CONFIGURAÇÃO
# ================================================================

DATAS = ['2025-03-31', '2025-06-30', '2025-09-30']

TICKERS_IBOV = [
    "VALE3", "ITUB4", "PETR4", "PETR3", "AXIA3", "BBDC4", "SBSP3", "B3SA3",
    "ITSA4", "BPAC11", "WEGE3", "BBAS3", "EMBJ3", "ABEV3", "EQTL3", "RENT3",
    "RDOR3", "ENEV3", "PRIO3", "VBBR3", "SUZB3", "RADL3", "AXIA7", "VIVT3",
    "UGPA3", "BBDC3", "GGBR4", "CPLE3", "CMIG4", "TIMS3", "TOTS3", "BBSE3",
    "RAIL3", "ENGI11", "AXIA6", "MOTV3", "KLBN11", "LREN3", "ALOS3", "MBRF3",
    "SANB11", "ASAI3", "EGIE3", "ISAE4", "CSAN3", "CSMG3", "MULT3", "CXSE3",
    "SMFT3", "TAEE11", "PSSA3", "CPFE3", "CMIN3", "BRAV3", "CYRE3", "GOAU4",
    "FLRY3", "NATU3", "HYPE3", "COGN3", "CURY3", "CSNA3", "IGTI11", "BRAP4",
    "DIRR3", "IRBR3", "POMO4", "MGLU3", "MRVE3", "VIVA3", "AURE3", "SLCE3",
    "YDUQ3", "AZZA3", "RECV3", "USIM5", "HAPV3", "CEAB3", "BRKM5", "BEEF3",
    "RENT4", "VAMO3", "CYRE4", "PCAR3", "RAIZ4",
]

# ================================================================
# 1) CARREGA dados_final_2025.xlsx e transforma em formato longo
# ================================================================

df_wide = pd.read_excel('resultado/dados_final_2025.xlsx')
print(f"Empresas no arquivo: {len(df_wide)}")

# Transforma de wide para long (uma linha por empresa por data)
rows = []
for _, row in df_wide.iterrows():
    for data in DATAS:
        rows.append({
            'ativo':         row['ativo'],
            'dt_refer':      data,
            'caixa':         row[f'caixa_{data}'],
            'ativo_total':   row[f'ativo_total_{data}'],
            'divida_cp':     row[f'divida_cp_{data}'],
            'divida_lp':     row[f'divida_lp_{data}'],
            'pl':            row[f'pl_{data}'],
            'receita':       row[f'receita_liquida_{data}'],
            'ebit':          row[f'ebit_{data}'],
            'lucro':         row[f'lucro_liquido_{data}'],
        })

df = pd.DataFrame(rows)
print(f"Total linhas (empresa × data): {len(df)}")

# ================================================================
# 2) MAPEIA ticker → nome da empresa
# ================================================================

# Carrega mapeamento B3
df_mapa = pd.read_excel('mapeamento_ticker.xlsx')

def empresa_tem_ticker(todos_tickers: str, ticker: str) -> bool:
    if pd.isna(todos_tickers):
        return False
    return ticker in [t.strip() for t in str(todos_tickers).split(',')]

# Para cada ticker do Ibovespa, busca o nome da empresa
ticker_para_nome = {}
for ticker in TICKERS_IBOV:
    match = df_mapa[df_mapa['todos_tickers'].apply(
        lambda x: empresa_tem_ticker(x, ticker)
    )]
    if not match.empty:
        ticker_para_nome[ticker] = match.iloc[0]['nome']

print(f"\nTickers mapeados: {len(ticker_para_nome)}/{len(TICKERS_IBOV)}")

# Inverte: nome → ticker
nome_para_ticker = {v: k for k, v in ticker_para_nome.items()}

# ================================================================
# 3) CRUZA nome do ITR com nome do mapeamento B3
# ================================================================

# Carrega CNPJ do ITR
df_itr = pd.read_csv('bpa-2025.csv', sep=';', encoding='latin1')
cnpj_empresa = df_itr[['CNPJ_CIA','DENOM_CIA']].drop_duplicates()
cnpj_empresa.columns = ['cnpj','nome_itr']
cnpj_empresa['cnpj_norm'] = cnpj_empresa['cnpj'].apply(normalizar_cnpj)

# CNPJ do mapeamento B3
df_mapa['cnpj_norm'] = df_mapa['cnpj'].apply(normalizar_cnpj)
cnpj_b3 = df_mapa[['cnpj_norm','nome']].drop_duplicates()
cnpj_b3.columns = ['cnpj_norm','nome_b3']

# Cruza: cnpj → nome_itr + nome_b3
mapa_completo = cnpj_empresa.merge(cnpj_b3, on='cnpj_norm', how='inner')

# Para cada nome_b3 do Ibovespa, pega o nome_itr correspondente
ibov_nomes = {}
for ticker in TICKERS_IBOV:
    if ticker in ticker_para_nome:
        nome_b3 = ticker_para_nome[ticker]
        match = mapa_completo[mapa_completo['nome_b3'] == nome_b3]
        if not match.empty:
            ibov_nomes[ticker] = match.iloc[0]['nome_itr']

print(f"Empresas encontradas no ITR: {len(ibov_nomes)}/{len(TICKERS_IBOV)}")

# ================================================================
# 4) FILTRA df só para empresas do Ibovespa
# ================================================================

nomes_itr_ibov = list(ibov_nomes.values())
df = df[df['ativo'].isin(nomes_itr_ibov)].copy()
print(f"\nLinhas após filtro Ibovespa: {len(df)}")
print(f"Empresas únicas: {df['ativo'].nunique()}")

# Adiciona ticker
nome_itr_para_ticker = {v: k for k, v in ibov_nomes.items()}
df['ticker'] = df['ativo'].map(nome_itr_para_ticker)

# ================================================================
# 5) CALCULA indicadores
# ================================================================

df['divida_bruta']   = df['divida_cp'] + df['divida_lp']
df['divida_liquida'] = df['divida_bruta'] - df['caixa']
df['cap_investido']  = df['pl'] + df['divida_liquida']

df['ROIC']        = df['ebit'] / df['cap_investido']
df['ROE']         = df['lucro'] / df['pl']
df['margem_liq']  = df['lucro'] / df['receita']
df['div_ebitda']  = df['divida_bruta'] / df['ebit']  # proxy EBITDA≈EBIT
df['ROA']         = df['lucro'] / df['ativo_total']

# Remove cap_investido negativo
df = df[df['cap_investido'] > 0].reset_index(drop=True)

print(f"\nApós remover cap_investido ≤ 0: {len(df)} linhas")

# ================================================================
# 6) BUSCA preço histórico
# ================================================================

def get_preco(ticker: str, dt_refer: str):
    try:
        data_fim = pd.Timestamp(dt_refer)
        data_ini = data_fim - pd.Timedelta(days=7)
        hist = yf.download(
            ticker + ".SA",
            start=data_ini,
            end=data_fim + pd.Timedelta(days=1),
            progress=False,
            auto_adjust=True
        )
        if hist.empty:
            return None
        return float(hist["Close"].iloc[-1])
    except Exception:
        return None

combos = df[['ticker','dt_refer']].drop_duplicates()
print(f"\nBuscando preços para {len(combos)} combinações ticker+data...")

precos = {}
for i, row in combos.iterrows():
    key = (row['ticker'], row['dt_refer'])
    precos[key] = get_preco(row['ticker'], row['dt_refer'])
    if (i+1) % 20 == 0:
        print(f"  {i+1}/{len(combos)}...")

df['preco'] = df.apply(lambda r: precos.get((r['ticker'], r['dt_refer'])), axis=1)
print(f"Com preço: {df['preco'].notna().sum()}/{len(df)}")

# ================================================================
# 7) BUSCA número de ações
# ================================================================

df_cap = pd.read_csv(
    'itr_cia_aberta_capital_social_con_2025.csv',
    sep=';', encoding='latin1', dtype={'CNPJ_CIA': str}
)
df_cap['cnpj_norm']  = df_cap['CNPJ_CIA'].apply(normalizar_cnpj)
df_cap['acoes_circ'] = df_cap['QT_ACAO_TOTAL_CAP_INTEGR'] - df_cap['QT_ACAO_TOTAL_TESOURO']
df_cap['dt_refer']   = pd.to_datetime(df_cap['DT_REFER'], dayfirst=True).dt.strftime('%Y-%m-%d')
df_cap = df_cap.sort_values('VERSAO', ascending=False).drop_duplicates(subset=['cnpj_norm','dt_refer'])
df_cap = df_cap[['cnpj_norm','dt_refer','acoes_circ']]

# Adiciona cnpj_norm no df
df = df.merge(
    cnpj_empresa[['nome_itr','cnpj_norm']].rename(columns={'nome_itr':'ativo'}),
    on='ativo',
    how='left'
)

# Junta ações
df = df.merge(df_cap, on=['cnpj_norm','dt_refer'], how='left')
print(f"Com ações: {df['acoes_circ'].notna().sum()}/{len(df)}")

# ================================================================
# 8) CALCULA EV e Earnings Yield
# ================================================================

df['valor_mercado']   = df['preco'] * df['acoes_circ']
df['EV']              = df['valor_mercado'] + df['cap_investido'] - df['pl']
df['earnings_yield']  = df['ebit'] / df['EV']

# ================================================================
# RESULTADO FINAL
# ================================================================

df_final = df[[
    'ativo', 'ticker', 'dt_refer', 
    'preco', 'acoes_circ', 'valor_mercado',
    'ebit', 'cap_investido', 'pl', 'EV',
    'ROIC', 'earnings_yield', 'ROE', 'margem_liq', 'div_ebitda', 'ROA'
]].copy()

print("\n" + "="*70)
print("RESULTADO FINAL")
print("="*70)
print(f"Total linhas:  {len(df_final)}")
print(f"Empresas:      {df_final['ativo'].nunique()}")
print(f"Tickers:       {df_final['ticker'].nunique()}")
print(f"Com EV:        {df_final['EV'].notna().sum()}")
print(f"Com EY:        {df_final['earnings_yield'].notna().sum()}")
print()
print(df_final[['ativo','ticker','dt_refer','earnings_yield','ROIC']].head(12).to_string(index=False))
print()

# Salva
df_final.to_excel('ibovespa_magic_formula.xlsx', index=False)
print("Salvo: ibovespa_magic_formula.xlsx")

Empresas no arquivo: 411
Total linhas (empresa × data): 1233

Tickers mapeados: 83/85
Empresas encontradas no ITR: 75/85

Linhas após filtro Ibovespa: 192
Empresas únicas: 64

Após remover cap_investido ≤ 0: 192 linhas

Buscando preços para 192 combinações ticker+data...

C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  20/192...

C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
$MOTV3.SA: possibly delisted; no price data found  (1d 2025-03-24 00:00:00 -> 2025-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1742785200, endDate = 1743476400")

1 Failed download:
['MOTV3.SA']: possibly delisted; no price data found  (1d 2025-03-24 00:00:00 -> 2025-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1742785200, endDate = 1743476400")
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  40/192...

C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
$EMBJ3.SA: possibly delisted; no price data found  (1d 2025-03-24 00:00:00 -> 2025-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1742785200, endDate = 1743476400")

1 Failed download:
['EMBJ3.SA']: possibly delisted; no price data found  (1d 2025-03-24 00:00:00 -> 2025-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1742785200, endDate = 1743476400")
$EMBJ3.SA: possibly delisted; no price data found  (1d 2025-06-23 00:00:00 -> 2025-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1750647600, endDate = 1751338800")

1 Failed download:
['EMBJ3.SA']: possibly delisted; no price data found  (1d 2025-06-23 00:00:00 -> 2025-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1750647600, endDate = 1751338800")
$EMBJ3.SA: possibly delisted; no price data found  (1d 2025-09-23 00:00:00 -> 2025-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1758596400, endDate = 1759287600")

1 Failed download:
['EMBJ3.SA']: possibly delisted; no price data found  (1d 2025-09-23 00:00:00 -> 2025-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1758596400, endDate = 1759287600")

  60/192...

C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  80/192...

C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
$RENT4.SA: possibly delisted; no price data found  (1d 2025-03-24 00:00:00 -> 2025-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1742785200, endDate = 1743476400")

1 Failed download:
['RENT4.SA']: possibly delisted; no price data found  (1d 2025-03-24 00:00:00 -> 2025-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1742785200, endDate = 1743476400")
$RENT4.SA: possibly delisted; no price data found  (1d 2025-06-23 00:00:00 -> 2025-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1750647600, endDate = 1751338800")

1 Failed download:
['RENT4.SA']: possibly delisted; no price data found  (1d 2025-06-23 00:00:00 -> 2025-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1750647600, endDate = 1751338800")
$RENT4.SA: possibly delisted; no price data found  (1d 2025-09-23 00:00:00 -> 2025-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1758596400, endDate = 1759287600")

1 Failed download:
['RENT4.SA']: possibly delisted; no price data found  (1d 2025-09-23 00:00:00 -> 2025-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1758596400, endDate = 1759287600")
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  100/192...

C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  120/192...

C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  140/192...

C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  160/192...

C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
$NATU3.SA: possibly delisted; no price data found  (1d 2025-03-24 00:00:00 -> 2025-04-01 00:00:00)

1 Failed download:
['NATU3.SA']: possibly delisted; no price data found  (1d 2025-03-24 00:00:00 -> 2025-04-01 00:00:00)
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
$CYRE4.SA: possibly delisted; no price data found  (1d 2025-03-24 00:00:00 -> 2025-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1742785200, endDate = 1743476400")

1 Failed download:
['CYRE4.SA']: possibly delisted; no price data found  (1d 2025-03-24 00:00:00 -> 2025-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1742785200, endDate = 1743476400")
$CYRE4.SA: possibly delisted; no price data found  (1d 2025-06-23 00:00:00 -> 2025-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1750647600, endDate = 1751338800")

1 Failed download:
['CYRE4.SA']: possibly delisted; no price data found  (1d 2025-06-23 00:00:00 -> 2025-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1750647600, endDate = 1751338800")
$CYRE4.SA: possibly delisted; no price data found  (1d 2025-09-23 00:00:00 -> 2025-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1758596400, endDate = 1759287600")

1 Failed download:
['CYRE4.SA']: possibly delisted; no price data found  (1d 2025-09-23 00:00:00 -> 2025-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1758596400, endDate = 1759287600")
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  180/192...

C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:161: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14696\3886184675.py:188: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df_cap['dt_refer']   = pd.to_datetime(df_cap['DT_REFER'], dayfirst=True).dt.strftime('%Y-%m-%d')

Com preço: 181/192
Com ações: 192/192

======================================================================
RESULTADO FINAL
======================================================================
Total linhas:  192
Empresas:      64
Tickers:       64
Com EV:        181
Com EY:        181

            ativo ticker   dt_refer  earnings_yield      ROIC
AXIA ENERGIA S.A.  AXIA6 2025-03-31        0.026792  0.018921
AXIA ENERGIA S.A.  AXIA6 2025-06-30        0.001063  0.000767
AXIA ENERGIA S.A.  AXIA6 2025-09-30       -0.018015 -0.016395
    ENERGISA S.A. ENGI11 2025-03-31        0.000024  0.032673
    ENERGISA S.A. ENGI11 2025-06-30        0.000017  0.028195
    ENERGISA S.A. ENGI11 2025-09-30        0.000016  0.026931
PORTO SEGURO S.A.  PSSA3 2025-03-31        0.037769  0.070531
PORTO SEGURO S.A.  PSSA3 2025-06-30        0.025874  0.065772
PORTO SEGURO S.A.  PSSA3 2025-09-30        0.027182  0.058978
        RUMO S.A.  RAIL3 2025-03-31        0.000028  0.028394
        RUMO S.A.  RAIL3 2025-06-30        0.000039  0.045626
        RUMO S.A.  RAIL3 2025-09-30        0.000049  0.047106

Salvo: ibovespa_magic_formula.xlsx

Como a Magic Formula Original Funciona

Rankeia todas as ações pelo Earnings Yield (maior → melhor → ranking 1, 2, 3...)
Rankeia todas as ações pelo ROIC (maior → melhor → ranking 1, 2, 3...)
Soma os rankings (não os valores)
Seleciona as top 20-30 com menor ranking combinado