In [1]:
import pandas as pd
import numpy as np
import random
import pyomo.environ as pyo
from pyomo.environ import *
from pyomo.environ import SolverFactory
import yfinance as yf
from pathlib import Path
import os
import matplotlib.pyplot as plt

In [2]:
anos = ['2025-12-31',
 '2024-12-31',
 '2023-12-31',
 '2022-12-31',
 '2021-12-31',
 '2020-12-31',
 '2019-12-31',
 '2018-12-31',
 '2017-12-31',
 '2016-12-31',
 '2015-12-31',
 ]

## LER OS RETORNOS, SCORE e SELIC

In [8]:
# Retornos

dfs = {}
for ano in anos:
    ano_usado = ano.split('-')[0]
    nome = f'df_ativos_{ano_usado}.csv'
    caminho = Path('retornos_ativos_otimizacao') / nome
    dfs[ano_usado] = pd.read_csv(caminho).set_index('date')
    dfs[ano_usado] = dfs[ano_usado].drop(columns=dfs[ano_usado].columns[(dfs[ano_usado] == 0).all()])
    print(ano,'-',len(dfs[ano_usado].columns))

2025-12-31 - 78
2024-12-31 - 78
2023-12-31 - 78
2022-12-31 - 77
2021-12-31 - 77
2020-12-31 - 73
2019-12-31 - 73
2018-12-31 - 70
2017-12-31 - 70
2016-12-31 - 67
2015-12-31 - 62

In [9]:
## SELIC para Sigma e excesso
selic_d = pd.read_csv('selic/selic_diario.csv').set_index('date')

In [27]:
## SCORE para score
score_todos_anos = pd.read_csv('score_mf/magic_formula.csv').set_index('Unnamed: 0').reset_index()

In [28]:
score_todos_anos.rename(columns={'Unnamed: 0': 'date'}, inplace=True)

In [29]:
score_todos_anos.set_index('date', inplace=True)

In [30]:
lista_ativos_finais = score_todos_anos.columns.tolist()
score_todos_anos

,ABEV3,ALOS3,ANIM3,AXIA3,AZZA3,B3SA3,BBAS3,BBDC3,BBDC4,BBSE3,...,TAEE11,TEND3,TOTS3,UGPA3,USIM5,VALE3,VBBR3,VIVT3,WEGE3,YDUQ3
date,,,,,,,,,,,,,,,,,,,,,
2015,0.884615,0.307692,0.641026,0.064103,0.692308,0.897436,0.307692,0.307692,0.307692,0.012821,...,0.948718,0.307692,0.769231,0.730769,0.051282,0.076923,0.307692,0.666667,0.564103,0.307692
2016,0.897436,0.243590,0.538462,0.833333,0.666667,0.602564,0.243590,0.243590,0.243590,1.000000,...,0.923077,0.243590,0.782051,0.679487,0.089744,0.551282,0.243590,0.730769,0.576923,0.243590
2017,0.910256,0.185897,0.551282,0.461538,0.628205,0.858974,0.185897,0.185897,0.185897,0.961538,...,0.820513,0.602564,0.576923,0.564103,0.371795,0.589744,0.185897,0.666667,0.474359,0.185897
2018,0.871795,0.173077,0.320513,0.756410,0.576923,0.884615,0.173077,0.173077,0.173077,0.961538,...,0.897436,0.538462,0.551282,0.346154,0.333333,0.602564,0.173077,0.730769,0.512821,0.173077
2019,0.833333,0.198718,0.448718,0.551282,0.679487,0.923077,0.198718,0.198718,0.198718,1.000000,...,0.807692,0.525641,0.512821,0.320513,0.333333,0.294872,0.198718,0.666667,0.602564,0.730769
2020,0.782051,0.179487,0.269231,0.525641,0.730769,0.794872,0.179487,0.179487,0.179487,0.961538,...,0.935897,0.500000,0.641026,0.358974,0.589744,0.602564,0.179487,0.564103,0.538462,0.307692
2021,0.717949,0.102564,0.269231,0.538462,0.794872,0.756410,0.102564,0.102564,0.102564,0.974359,...,0.987179,0.025641,0.384615,0.243590,0.807692,0.782051,0.410256,0.448718,0.487179,0.320513
2022,0.756410,0.115385,0.371795,0.307692,0.666667,0.743590,0.115385,0.115385,0.115385,0.987179,...,0.833333,0.025641,0.384615,0.615385,0.538462,0.717949,0.551282,0.448718,0.564103,0.410256
2023,0.794872,0.935897,0.538462,0.448718,0.628205,0.769231,0.096154,0.096154,0.096154,0.987179,...,0.833333,0.166667,0.384615,0.589744,0.179487,0.564103,0.730769,0.423077,0.576923,0.461538
2024,0.782051,0.794872,0.641026,0.615385,0.217949,0.820513,0.108974,0.108974,0.108974,1.000000,...,0.948718,0.435897,0.679487,0.705128,0.166667,0.538462,0.769231,0.371795,0.589744,0.564103
2025,0.846154,0.794872,0.705128,0.192308,0.551282,0.782051,0.108974,0.108974,0.108974,0.974359,...,0.935897,0.525641,0.692308,0.576923,0.025641,0.282051,0.397436,0.423077,0.628205,0.615385

## EXCESSO DOS ANOS e SIGMA (MAtriz de covariancia)

##### EXCESSO PARA TODOS

In [10]:
dict_sigma = {}
dict_excesso = {}
for an in anos:
    ano = an.split("-")[0]

    try:
        print(f"=============== \n EXCESSO {ano}\n ============")
        print("Atualização, Ano: ",ano)
        df = dfs[ano]
        # df_f = pd.DataFrame(eval(df))
        df_f = df.copy()
        slc = selic_d[selic_d.index.isin(df_f.index)]
        slc['valor_diario'] = slc['valor_diario']/100

        print(f"Tamanho DF de {ano}: ", len(df_f))
        print(f"Tamanho Selic: ", len(slc['valor_diario']))
        ano = int(ano)
        dict_excesso[ano] = df_f.sub(slc['valor_diario'],axis=0)
        print("tamanho final do Excesso: ",len(dict_excesso[ano]))

        print(f"============\n SIGMA {ano}\n===========")            
        dict_sigma[ano] = dict_excesso[ano].cov()
        print('Tamanho final do SIGMA: ',len(dict_sigma[ano]))

    except Exception as e:
        print(e)
        print("ERror")

===============
 EXCESSO 2025
 ============
Atualização, Ano:  2025
Tamanho DF de 2025:  123
Tamanho Selic:  123
tamanho final do Excesso:  123
============
 SIGMA 2025
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2024
 ============
Atualização, Ano:  2024
Tamanho DF de 2024:  122
Tamanho Selic:  122
tamanho final do Excesso:  122
============
 SIGMA 2024
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2023
 ============
Atualização, Ano:  2023
Tamanho DF de 2023:  121
Tamanho Selic:  121
tamanho final do Excesso:  121
============
 SIGMA 2023
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2022
 ============
Atualização, Ano:  2022
Tamanho DF de 2022:  124
Tamanho Selic:  124
tamanho final do Excesso:  124
============
 SIGMA 2022
===========
Tamanho final do SIGMA:  77
===============
 EXCESSO 2021
 ============
Atualização, Ano:  2021
Tamanho DF de 2021:  123
Tamanho Selic:  123
tamanho final do Excesso:  123
============
 SIGMA 2021
===========
Tamanho final do SIGMA:  77
===============
 EXCESSO 2020
 ============
Atualização, Ano:  2020
Tamanho DF de 2020:  120
Tamanho Selic:  120
tamanho final do Excesso:  120
============
 SIGMA 2020
===========
Tamanho final do SIGMA:  73
===============
 EXCESSO 2019
 ============
Atualização, Ano:  2019
Tamanho DF de 2019:  123
Tamanho Selic:  123
tamanho final do Excesso:  123
============
 SIGMA 2019
===========
Tamanho final do SIGMA:  73
===============
 EXCESSO 2018
 ============
Atualização, Ano:  2018
Tamanho DF de 2018:  119
Tamanho Selic:  119
tamanho final do Excesso:  119
============
 SIGMA 2018
===========
Tamanho final do SIGMA:  70
===============
 EXCESSO 2017
 ============
Atualização, Ano:  2017
Tamanho DF de 2017:  119
Tamanho Selic:  119
tamanho final do Excesso:  119
============
 SIGMA 2017
===========
Tamanho final do SIGMA:  70
===============
 EXCESSO 2016
 ============
Atualização, Ano:  2016
Tamanho DF de 2016:  123
Tamanho Selic:  123
tamanho final do Excesso:  123
============
 SIGMA 2016
===========
Tamanho final do SIGMA:  67
===============
 EXCESSO 2015
 ============
Atualização, Ano:  2015
Tamanho DF de 2015:  120
Tamanho Selic:  60
tamanho final do Excesso:  120
============
 SIGMA 2015
===========
Tamanho final do SIGMA:  62

## Hiperparâmetros

In [30]:
vb_cardinalidade_max = 10
vb_cardinalidade_min = 10
vb_peso_maximo = 0.20
vb_peso_minimo = 0.02
vb_theta = 0.5

### Fazendo otimização ano a ano e comparando com o proximo ano

In [33]:
anos = ['2015-12-31', '2016-12-31', '2017-12-31', '2018-12-31', '2019-12-31', '2020-12-31', '2021-12-31', '2022-12-31', '2023-12-31', '2024-12-31', '2025-12-31']
print(anos)

['2015-12-31', '2016-12-31', '2017-12-31', '2018-12-31', '2019-12-31', '2020-12-31', '2021-12-31', '2022-12-31', '2023-12-31', '2024-12-31', '2025-12-31']

In [34]:
score_usado = score_todos_anos[score_todos_anos.index.isin([2015])]
score_usado

,ABEV3,ALOS3,ANIM3,AXIA3,AZZA3,B3SA3,BBAS3,BBDC3,BBDC4,BBSE3,...,TAEE11,TEND3,TOTS3,UGPA3,USIM5,VALE3,VBBR3,VIVT3,WEGE3,YDUQ3
date,,,,,,,,,,,,,,,,,,,,,
2015,0.884615,0.307692,0.641026,0.064103,0.692308,0.897436,0.307692,0.307692,0.307692,0.012821,...,0.948718,0.307692,0.769231,0.730769,0.051282,0.076923,0.307692,0.666667,0.564103,0.307692

In [35]:
dfs[str(2015)]

,ABEV3,ALOS3,ANIM3,AXIA3,AZZA3,B3SA3,BBAS3,BBDC3,BBDC4,BBSE3,...,TAEE11,TEND3,TOTS3,UGPA3,USIM5,VALE3,VBBR3,VIVT3,WEGE3,YDUQ3
date,,,,,,,,,,,,,,,,,,,,,
2015-10-01,0.014422,0.0,-0.044388,-0.009515,-0.012563,0.027080,-0.019078,0.016511,0.013532,0.010072,...,-0.016253,0.0,-0.021235,0.009731,-0.068671,0.038606,0.0,0.010755,0.028462,0.0
2015-10-02,0.018269,0.0,0.049697,0.076929,0.056493,0.035154,0.067740,0.042402,0.037756,0.064242,...,0.034113,0.0,0.040008,0.026389,0.012834,0.034842,0.0,-0.004170,0.028330,0.0
2015-10-05,0.014459,0.0,0.048363,0.033920,-0.019753,-0.019531,0.015084,0.023189,0.029319,0.010875,...,0.023205,0.0,0.023792,-0.003320,0.044310,0.017948,0.0,0.031597,0.024474,0.0
2015-10-06,-0.022605,0.0,0.044153,-0.036258,0.029484,-0.000893,0.022890,0.012116,0.009495,0.000750,...,0.015108,0.0,-0.016559,-0.003624,0.006028,0.009377,0.0,-0.006250,-0.002379,0.0
2015-10-07,0.005535,0.0,0.173864,0.012532,0.002387,0.002604,0.084700,0.034743,0.035919,0.048920,...,0.005947,0.0,0.035936,0.001453,0.021088,0.100494,0.0,0.021375,0.008367,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-03-24,0.000000,0.0,0.004588,0.000000,0.000000,0.002633,-0.033112,-0.023490,-0.018317,-0.011093,...,-0.011778,0.0,-0.005948,0.000720,0.039780,0.065857,0.0,0.002879,-0.009273,0.0
2016-03-28,0.015784,0.0,-0.050002,0.023053,0.036363,0.027387,0.058457,0.032869,0.048744,0.052561,...,0.016070,0.0,0.018628,0.000861,0.016446,0.007975,0.0,0.023233,0.023747,0.0
2016-03-29,0.002077,0.0,-0.026808,-0.021126,0.006578,-0.012064,0.029846,0.022305,0.017434,0.023637,...,0.022950,0.0,-0.018287,0.016047,-0.021527,-0.005265,0.0,0.001273,0.026002,0.0
2016-03-30,-0.009822,0.0,-0.036380,-0.033102,0.015254,0.007733,-0.020772,0.000000,0.001424,-0.013989,...,-0.006475,0.0,-0.010182,0.001410,0.005465,0.029809,0.0,0.010447,-0.006176,0.0
2016-03-31,-0.017233,0.0,0.015303,-0.013380,0.002145,-0.019157,-0.024660,-0.034656,-0.035284,-0.020445,...,0.013049,0.0,-0.034430,-0.017041,-0.010871,-0.025091,0.0,-0.035049,-0.034446,0.0

In [27]:
dict_sigma[2015]

,ABEV3,ANIM3,AXIA3,AZZA3,B3SA3,BBAS3,BBDC3,BBDC4,BBSE3,BEEF3,...,SLCE3,SMTO3,SUZB3,TAEE11,TOTS3,UGPA3,USIM5,VALE3,VIVT3,WEGE3
ABEV3,0.000339,0.000090,0.000346,0.000241,0.000246,0.000269,0.000257,0.000312,0.000331,0.000143,...,0.000016,0.000057,0.000112,0.000203,0.000204,0.000256,0.000100,0.000481,0.000209,0.000243
ANIM3,0.000090,0.002270,0.000487,0.000350,0.000336,0.000874,0.000606,0.000698,0.000370,0.000077,...,0.000188,0.000100,0.000169,0.000393,0.000206,0.000160,0.001193,0.001335,0.000573,0.000132
AXIA3,0.000346,0.000487,0.001414,0.000472,0.000711,0.001278,0.000783,0.000844,0.000883,0.000326,...,-0.000173,0.000122,-0.000285,0.000305,0.000211,0.000380,0.001505,0.000740,0.000422,0.000518
AZZA3,0.000241,0.000350,0.000472,0.000909,0.000370,0.000636,0.000407,0.000546,0.000401,0.000069,...,-0.000130,-0.000002,-0.000082,0.000116,0.000219,0.000229,0.000999,0.000765,0.000291,0.000246
B3SA3,0.000246,0.000336,0.000711,0.000370,0.000871,0.001038,0.000676,0.000722,0.000725,0.000183,...,-0.000040,0.000010,-0.000252,0.000212,0.000126,0.000288,0.001309,0.000739,0.000274,0.000195
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
UGPA3,0.000256,0.000160,0.000380,0.000229,0.000288,0.000364,0.000322,0.000344,0.000401,0.000168,...,0.000117,0.000020,0.000149,0.000179,0.000133,0.000353,0.000194,0.000492,0.000274,0.000282
USIM5,0.000100,0.001193,0.001505,0.000999,0.001309,0.002550,0.001151,0.001241,0.001406,0.000590,...,-0.000338,-0.000117,-0.001161,0.000325,-0.000127,0.000194,0.006672,0.001682,0.000693,0.000057
VALE3,0.000481,0.001335,0.000740,0.000765,0.000739,0.000987,0.000889,0.001034,0.000647,0.000492,...,0.000143,-0.000139,0.000355,0.000247,0.000414,0.000492,0.001682,0.003306,0.000926,0.000548
VIVT3,0.000209,0.000573,0.000422,0.000291,0.000274,0.000512,0.000314,0.000352,0.000345,0.000321,...,0.000152,0.000019,0.000249,0.000193,0.000214,0.000274,0.000693,0.000926,0.000820,0.000320
WEGE3,0.000243,0.000132,0.000518,0.000246,0.000195,0.000511,0.000367,0.000383,0.000413,0.000169,...,0.000090,0.000059,0.000201,0.000144,0.000320,0.000282,0.000057,0.000548,0.000320,0.000760

In [53]:
score_usado.dropna(axis=1)

,ABEV3,ANIM3,AXIA3,AZZA3,B3SA3,BBSE3,BEEF3,BRAP4,BRKM5,CMIG4,...,SBSP3,SLCE3,SUZB3,TAEE11,TOTS3,UGPA3,USIM5,VALE3,VIVT3,WEGE3
ano,,,,,,,,,,,,,,,,,,,,,
2015,0.594862,0.179014,-0.280358,0.188981,0.657607,-9.966455,0.180942,-4.348976,0.170975,8.511375,...,43.455029,0.133358,0.122797,0.778584,0.244284,0.20629,-0.293338,-0.134539,0.182352,0.125224

In [63]:
anos

['2025-12-31',
 '2024-12-31',
 '2023-12-31',
 '2022-12-31',
 '2021-12-31',
 '2020-12-31',
 '2019-12-31',
 '2018-12-31',
 '2017-12-31',
 '2016-12-31',
 '2015-12-31']

In [59]:
y = []
carteiras_anuais = {}
melhor_pesos = None
historico = []
carteiras_criadas = []
for a in anos:
    y.append(a.split('-')[0])
print("=-"*48)
print("Anos totais: ",y)
print("=-"*48)
lista_ativos_finais = {}
for an in anos:
    ano = an.split("-")[0]
    print("COMEÇANDO ANO NOVO: ",ano)
    #deletar modelo
    if 'model' in locals():
        del model
        print('Modelo Antigo deletado \n Iniciando Novo')
    else:
        print("Nao consta model")
        pass
    try:

            #SCORE ------------

        score_todos_anos = pd.read_csv(f'score_mf/{ano}/mf_{ano}.csv').set_index('ano')
        score_usado = score_todos_anos.dropna(axis=1).copy()
        # print(score_usado)
        print("Score Atualizado")
        ano_um = int(ano)

            # RETORNO ---------------

        # retorno_usado = pd.DataFrame(eval(df_usado))
        df_usado = dfs[str(ano_um)]
        retorno_usado = df_usado.copy()
        retorno_usado = retorno_usado[score_usado.columns]

            # Lista ativos por ano ---------
        lista_ativos_finais[ano_um] = score_usado.columns.tolist()
        print("Retornos atualizados")

            # EXCESSO retorno - rf ------------

        excesso_usado = dict_excesso[ano_um][score_usado.columns]
        print("Excessos Atualizados")

            # SIGMA ---------------

        sigma_usado = excesso_usado.cov()
        print("Sigmas Atualizados")
        print("-----")
    except Exception as e:
        print("ERRRRRRRRRRRROR")
        print(e)
    # if df_usado == 'df_ativos_2015':
    #     continue
    # else:
    print("# ------ CRIAÇÃO DO MODELO")
    print("## Carteira criada para o ano: ",int(ano)+1)
    print("## UTILIZANDO SCORE DO ANO DE: ",ano)
    print("## UTILIZANDO DADOS DE RETORNO DE: ",str(ano_um))
    print("## UTILIZANDO EXCESSO DO ANO DE: ",ano_um)
    print("## UTILIZANDO SIGMAS DO ANO DE: ",ano_um)
    print(len(retorno_usado.columns))
    print(len(score_usado.columns))
    print(len(sigma_usado.columns))
    print(len(excesso_usado.columns))

    model = pyo.ConcreteModel()
    #---------VARIÁVEIS-----------
    model.nome_ativos = pyo.Set(initialize = retorno_usado.columns)
    model.ativos = pyo.RangeSet(0, len(retorno_usado.columns)-1)
    model.dias = pyo.RangeSet(0, len(retorno_usado)-1)
    model.retornos_ativos = pyo.Param(model.dias, model.ativos, initialize=lambda model,dia, ativo: retorno_usado.iloc[dia, ativo])    
    model.theta = pyo.Param(initialize=vb_theta)
    model.score = pyo.Param(model.ativos, initialize=lambda model,a: score_usado.iloc[0,a])
    model.cardinalidade_valor_max = pyo.Param(initialize=vb_cardinalidade_max)
    model.cardinalidade_valor_min = pyo.Param(initialize=vb_cardinalidade_min)
    model.peso_maximo = pyo.Param(initialize=vb_peso_maximo)
    model.peso_minimo = pyo.Param(initialize=vb_peso_minimo)
    model.x = pyo.Var(model.ativos, bounds=(0,1),domain=pyo.NonNegativeReals)
    model.y = pyo.Var(model.ativos, within=pyo.Binary)
    model.excesso = pyo.Param( model.ativos , initialize = lambda model,a: excesso_usado.mean().iloc[a])
    model.sigma = pyo.Param(model.ativos, model.ativos, initialize = lambda model,a,b: sigma_usado.iloc[a,b])
    model.s = pyo.Param(initialize = 2, mutable=True)
    model.r = pyo.Var(within=pyo.NonNegativeReals,bounds=(0,10))
    #-------------------------------------- FUNÇÕES
    #=============================
    # Função Objetivo
    #=============================
    def func_objetivo_1(model):
        retorno_esperado = model.theta * sum(
            model.retornos_ativos[dia, a] * model.x[a] for a in model.ativos for dia in model.dias
        )
        # retorno_esperado = model.theta * model.r
        # A dúvida de qual retorno usar (Retorno BRUTO ou Excesso (retorno - selic))

        score_total = (1 - model.theta) * sum(
            model.x[a] * model.score[a] for a in model.ativos
        )
        return retorno_esperado + score_total
    model.obj1 = pyo.Objective(rule=func_objetivo_1, sense=pyo.maximize)
    #=============================
    # RESTRIÇÕES
    #=============================
    def def_r(model):
        return model.r == sum(model.excesso[a]*model.x[a]for a in model.ativos)
    model.const_def_r = pyo.Constraint(rule=def_r)
    ## modelos de Programação de Cone de Segunda Ordem (SOCP) 
    ## e Programação Quadrática com Restrições (QCP)
    def cone(model):
        return model.r**2 >= model.s**2 * sum(model.x[a]*model.sigma[a,b]*model.x[b] for a in model.ativos for b in model.ativos)
    model.constr_cone = pyo.Constraint(rule=cone)
    #REstricao 1 x só ativa se y = 1
    def restr_vinculo_x_y(model, a):
        return model.x[a] <= model.y[a]
    model.const_restr_vinculo_x_y = pyo.Constraint(model.ativos, rule=restr_vinculo_x_y)
    #peso maximo por acao
    def rule_peso_maximo(model, a):
        # return model.x[a] <= 1/model.cardinalidade_valor
        return model.x[a] <= model.peso_maximo
    model.const_peso_maximo = pyo.Constraint(model.ativos, rule=rule_peso_maximo)
    #peso minimo por acao
    def rule_peso_minimo(model, a):
        return model.x[a] >= model.peso_minimo * model.y[a]  # se y=1, então x >= 0.05
    model.const_peso_minimo = pyo.Constraint(model.ativos, rule=rule_peso_minimo)
    #Restrição 2 soma peso 1
    def soma_peso_1(model):
        return sum(model.x[a] for a in model.ativos) == 1
    model.const_soma_peso_1 = pyo.Constraint(rule=soma_peso_1)
    def cardinalidade_min(model):
        return sum(
            model.y[a] for a in model.ativos
            ) >= model.cardinalidade_valor_min
    model.const_cardinalidade_total_min = pyo.Constraint(rule=cardinalidade_min)
    def cardinalidade_max(model):
        return sum(
            model.y[a] for a in model.ativos
            ) <= model.cardinalidade_valor_max
    model.const_cardinalidade_total_max = pyo.Constraint(rule=cardinalidade_max)
    # NOTEBOOOK
    # opt = SolverFactory('cplex', executable='C:\\CPLEX_Studio2211\\cplex\\bin\\x64_win64\\cplex.exe')
    # PC
    opt = SolverFactory('cplex', executable='C:\\Program Files\\IBM\\ILOG\\CPLEX_Studio_Community222\\cplex\\bin\\x64_win64\\cplex.exe')
    s_lo = 0.01        # <-- o Sharpe DIÁRIO 
    s_hi = 1   # teto: 2x o melhor ativo individual
    tol  = 0.001
    print("MODEL.S.VALUE => ",model.s.value)
    melhor_pesos = None
    historico = []
    carteiras_criadas = []
    # print(f"Valor a ser batido com S_LO: {s_lo} e S_HI: {s_hi} ... Diferença: {s_hi-s_lo}")
    print(f"Começando o WHILE do ano {ano}")
    while s_hi - s_lo > tol:
        s_a_ser_usado = 0.5 * (s_lo + s_hi)
        model.s.value = s_a_ser_usado
        model.write('modelo_debug.lp', io_options={'symbolic_solver_labels': True})

        print("="*18)
        res = opt.solve(model, load_solutions=False, tee=False)
        tc = res.solver.termination_condition
        print(f"Modelo Resolveu....Condição: ",tc)
        if tc == pyo.TerminationCondition.optimal:
            model.solutions.load_from(res)
            melhor_pesos = {a: pyo.value(model.x[a]) for a in model.ativos}
            s_lo = model.s.value
            print(f"Valor encontrado para o Sharpe: ",s_lo)
            historico.append((s_a_ser_usado, 'viavel'))
        elif tc in (pyo.TerminationCondition.infeasible,
                    pyo.TerminationCondition.infeasibleOrUnbounded, pyo.TerminationCondition.unbounded,pyo.TerminationCondition.unknown):
            s_hi = s_a_ser_usado
            print(f"Atualização do S_HI : {s_hi}")
            print("="*28)
            historico.append((s_a_ser_usado, 'inviavel'))
        else:
            print(f'status inesperado em s={s_a_ser_usado:.4f}: {tc}')
            pass
    print("SAIU DO WHILE")
    print(f'Sharpe máximo (diário) ≈ {s_lo:.4f}  |  anualizado ≈ {s_lo*np.sqrt(252):.2f}')
    carteiras_anuais[int(ano_um)+1] = {
        'pesos':  melhor_pesos,
        'sharpe_anual': s_lo*np.sqrt(252),
    }
    print(f"{ano_um} -> {melhor_pesos}")
    print("+-="*30)
    if 'model' in locals():
        del model
        print('DELETADO DPS DO WHILE')
    else:
        print("Nao consta model")
        pass

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Anos totais:  ['2025', '2024', '2023', '2022', '2021', '2020', '2019', '2018', '2017', '2016', '2015']
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
COMEÇANDO ANO NOVO:  2025
Nao consta model
Score Atualizado
Retornos atualizados
Excessos Atualizados
Sigmas Atualizados
-----
# ------ CRIAÇÃO DO MODELO
## Carteira criada para o ano:  2026
## UTILIZANDO SCORE DO ANO DE:  2025
## UTILIZANDO DADOS DE RETORNO DE:  2025
## UTILIZANDO EXCESSO DO ANO DE:  2025
## UTILIZANDO SIGMAS DO ANO DE:  2025
70
70
70
70
MODEL.S.VALUE =>  2
Começando o WHILE do ano 2025
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.505
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.2575
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.38125
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.443125
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.4121875
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.39671875
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.40445312499999997
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.4005859375
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.39865234375
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.397685546875
SAIU DO WHILE
Sharpe máximo (diário) ≈ 0.3977  |  anualizado ≈ 6.31
2025 -> {0: 0.15919821525601546, 1: 1.332914160911375e-10, 2: 6.049270150771435e-11, 3: 9.239982613526304e-11, 4: 4.406373216192304e-11, 5: 1.3189011208021934e-10, 6: 2.908023814903517e-10, 7: 3.1786605775710817e-11, 8: 0.0, 9: 1.0227901314444976e-10, 10: 3.050936056508452e-10, 11: 1.285762281444118e-10, 12: 5.6863118723030225e-11, 13: 4.018713519726888e-10, 14: 2.3625786471650625e-10, 15: 3.054041613404318e-11, 16: 0.19999999620553435, 17: 3.0797539251597653e-11, 18: 5.4743176178064496e-11, 19: 0.02183999633991567, 20: 4.998742416145063e-11, 21: 5.5029024073695306e-11, 22: 4.912153109960645e-11, 23: 1.0187501680026052e-10, 24: 9.747203815181747e-11, 25: 0.0, 26: 8.48564534931576e-11, 27: 1.0120489774298435e-10, 28: 1.0111051812973966e-10, 29: 7.06965645655839e-11, 30: 1.5002972147442912e-10, 31: 1.6758779273047405e-10, 32: 6.875355665973299e-11, 33: 9.046382366415212e-11, 34: 7.571154776574967e-11, 35: 1.9895148331740273e-10, 36: 1.7712282242997034e-10, 37: 2.7334151103478564e-10, 38: 1.1814071169040327e-10, 39: 5.863547307530613e-11, 40: 9.326170147968514e-11, 41: 3.591759216382009e-11, 42: 6.521103127669842e-11, 43: 6.917898636225386e-11, 44: 6.582857200505284e-11, 45: 9.229573542329423e-11, 46: 0.02000000089145336, 47: 0.13526870797717963, 48: 7.623091909200315e-11, 49: 0.17109221675012634, 50: 1.5765375937434793e-10, 51: 2.41934776480775e-10, 52: 7.010942141149544e-11, 53: 4.3612705934283935e-11, 54: 7.239148272182156e-11, 55: 1.9171916036097176e-10, 56: 1.7413736689918172e-10, 57: 0.07419984486583824, 58: 3.131094764131028e-11, 59: 1.8581517407825188e-10, 60: 1.784565085963095e-10, 61: 8.287094411420974e-11, 62: 4.559511130538129e-11, 63: 1.679223578236134e-10, 64: 0.047068587494959645, 65: 0.10627436909860834, 66: 2.1284394414144565e-10, 67: 2.0947822291540977e-10, 68: 0.06505805993850468, 69: 4.048916497519956e-11}
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=
DELETADO DPS DO WHILE
COMEÇANDO ANO NOVO:  2024
Nao consta model
Score Atualizado
Retornos atualizados
Excessos Atualizados
Sigmas Atualizados
-----
# ------ CRIAÇÃO DO MODELO
## Carteira criada para o ano:  2025
## UTILIZANDO SCORE DO ANO DE:  2024
## UTILIZANDO DADOS DE RETORNO DE:  2024
## UTILIZANDO EXCESSO DO ANO DE:  2024
## UTILIZANDO SIGMAS DO ANO DE:  2024
70
70
70
70
MODEL.S.VALUE =>  2
Começando o WHILE do ano 2024
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.505
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.2575
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.13375
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.195625
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.1646875
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.18015625
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.18789062499999998
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.1840234375
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.18595703125
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.184990234375
============================
SAIU DO WHILE
Sharpe máximo (diário) ≈ 0.1840  |  anualizado ≈ 2.92
2024 -> {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0, 6: 0.19999998921286022, 7: 0.0, 8: 0.0, 9: 0.08082852781470028, 10: 0.0, 11: 0.0, 12: 0.11601485209971876, 13: 0.1999997236623416, 14: 0.0, 15: 0.0, 16: 0.0, 17: 0.0, 18: 0.0, 19: 0.0, 20: 0.0, 21: 0.0, 22: 0.0, 23: 0.0, 24: 0.1999995061807389, 25: 0.0, 26: 0.0, 27: 0.0, 28: 0.020000251210369347, 29: 0.0, 30: 0.0, 31: 0.0, 32: 0.0, 33: 0.0, 34: 0.0, 35: 0.0, 36: 0.0, 37: 0.0, 38: 0.0, 39: 0.0, 40: 0.0, 41: 0.0, 42: 0.0, 43: 0.0, 44: 0.0, 45: 0.0, 46: 0.020004598313835054, 47: 0.12314776365808804, 48: 0.0, 49: 0.0, 50: 0.020004240701396506, 51: 0.0, 52: 0.0, 53: 0.0, 54: 0.0, 55: 0.0, 56: 0.0, 57: 0.0, 58: 0.0, 59: 0.02000061665706453, 60: 0.0, 61: 0.0, 62: 0.0, 63: 0.0, 64: 0.0, 65: 0.0, 66: 0.0, 67: 0.0, 68: 0.0, 69: 0.0}
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=
DELETADO DPS DO WHILE
COMEÇANDO ANO NOVO:  2023
Nao consta model
Score Atualizado
Retornos atualizados
Excessos Atualizados
Sigmas Atualizados
-----
# ------ CRIAÇÃO DO MODELO
## Carteira criada para o ano:  2024
## UTILIZANDO SCORE DO ANO DE:  2023
## UTILIZANDO DADOS DE RETORNO DE:  2023
## UTILIZANDO EXCESSO DO ANO DE:  2023
## UTILIZANDO SIGMAS DO ANO DE:  2023
70
70
70
70
MODEL.S.VALUE =>  2
Começando o WHILE do ano 2023
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.505
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.2575
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.38125
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.443125
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.4121875
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.42765624999999996
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.435390625
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.4315234375
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.43345703125
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.434423828125
SAIU DO WHILE
Sharpe máximo (diário) ≈ 0.4344  |  anualizado ≈ 6.90
2023 -> {0: 1.0709454558924824e-10, 1: 9.7168579034738e-11, 2: 1.3818180141846874e-10, 3: 9.501633330533251e-11, 4: 8.722041450127235e-11, 5: 5.582316674969642e-11, 6: 0.0552870071998626, 7: 3.526625249896076e-11, 8: 7.039693909616476e-11, 9: 8.538691993387413e-10, 10: 2.9856128633482015e-10, 11: 1.28940563043256e-10, 12: 3.2095541113270606e-11, 13: 1.387066683437126e-10, 14: 9.562056013672148e-11, 15: 4.5281957401620476e-11, 16: 0.04909980956075749, 17: 1.8339797342875105e-10, 18: 8.410415856788514e-11, 19: 0.19999999974585603, 20: 9.512872801011614e-11, 21: 2.151577635942838e-10, 22: 5.947309496796824e-11, 23: 9.400739733325747e-11, 24: 0.19999999792924836, 25: 6.85941927299798e-11, 26: 9.897370770466438e-11, 27: 9.860091341303429e-11, 28: 3.87080968108277e-11, 29: 6.846754591084237e-11, 30: 7.220359465968124e-11, 31: 8.07925117271623e-11, 32: 4.2574321987423735e-11, 33: 2.084348486665423e-10, 34: 3.133959623327526e-11, 35: 2.342304418428966e-10, 36: 2.5400699160587895e-10, 37: 5.3988594463690124e-11, 38: 2.70768295958563e-10, 39: 1.1436631245934599e-10, 40: 6.941131431438582e-11, 41: 2.3779064361200457e-11, 42: 1.212717176778998e-10, 43: 2.4587929049184537e-11, 44: 2.1575773620639453e-11, 45: 1.160553183539293e-10, 46: 3.572435726972745e-10, 47: 0.05786623309294054, 48: 0.02172465656396488, 49: 2.768206676589504e-10, 50: 6.493487330897967e-10, 51: 1.134078866121824e-10, 52: 9.354916084731465e-11, 53: 7.661147174001775e-11, 54: 4.424888527083837e-11, 55: 1.576502562193335e-10, 56: 0.020000000093999527, 57: 7.399068408030482e-11, 58: 9.544976246964223e-11, 59: 0.11630920192971717, 60: 4.119876761973446e-10, 61: 4.213657047197242e-11, 62: 5.1450994908014705e-11, 63: 0.14128757175767437, 64: 0.13842551489440763, 65: 7.981822951891646e-11, 66: 0.0, 67: 0.0, 68: 1.0320749573345563e-10, 69: 3.778720149032294e-11}
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=
DELETADO DPS DO WHILE
COMEÇANDO ANO NOVO:  2022
Nao consta model
Score Atualizado
Retornos atualizados
Excessos Atualizados
Sigmas Atualizados
-----
# ------ CRIAÇÃO DO MODELO
## Carteira criada para o ano:  2023
## UTILIZANDO SCORE DO ANO DE:  2022
## UTILIZANDO DADOS DE RETORNO DE:  2022
## UTILIZANDO EXCESSO DO ANO DE:  2022
## UTILIZANDO SIGMAS DO ANO DE:  2022
69
69
69
69
MODEL.S.VALUE =>  2
Começando o WHILE do ano 2022
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.505
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.2575
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.13375
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.195625
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.2265625
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.21109375
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.21882812499999998
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.2226953125
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.22462890624999998
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.22366210937499997
============================
SAIU DO WHILE
Sharpe máximo (diário) ≈ 0.2227  |  anualizado ≈ 3.54
2022 -> {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.19999999284306555, 6: 0.0, 7: 0.1999999997647705, 8: 0.0, 9: 0.0, 10: 0.0, 11: 0.0, 12: 0.0, 13: 0.0, 14: 0.0, 15: 0.0, 16: 0.020000014023537488, 17: 0.0, 18: 0.020000566338625958, 19: 0.0, 20: 0.0, 21: 0.0, 22: 0.0, 23: 0.1999999991066663, 24: 0.0, 25: 0.0, 26: 0.0, 27: 0.0, 28: 0.0, 29: 0.0, 30: 0.0, 31: 0.0, 32: 0.0, 33: 0.0, 34: 0.0, 35: 0.0, 36: 0.0, 37: 0.020000025737106297, 38: 0.0, 39: 0.0, 40: 0.0, 41: 0.0, 42: 0.0, 43: 0.0, 44: 0.0, 45: 0.0, 46: 0.0, 47: 0.07295374375177928, 48: 0.0, 49: 0.0, 50: 0.0, 51: 0.0, 52: 0.0, 53: 0.0, 54: 0.078402623765658, 55: 0.0, 56: 0.0, 57: 0.0, 58: 0.0, 59: 0.0, 60: 0.0, 61: 0.0, 62: 0.0, 63: 0.0, 64: 0.020000014194770245, 65: 0.0, 66: 0.0, 67: 0.16864302805378936, 68: 0.0}
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=
DELETADO DPS DO WHILE
COMEÇANDO ANO NOVO:  2021
Nao consta model
Score Atualizado
Retornos atualizados
Excessos Atualizados
Sigmas Atualizados
-----
# ------ CRIAÇÃO DO MODELO
## Carteira criada para o ano:  2022
## UTILIZANDO SCORE DO ANO DE:  2021
## UTILIZANDO DADOS DE RETORNO DE:  2021
## UTILIZANDO EXCESSO DO ANO DE:  2021
## UTILIZANDO SIGMAS DO ANO DE:  2021
69
69
69
69
MODEL.S.VALUE =>  2
Começando o WHILE do ano 2021
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.505
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.2575
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.38125
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.31937499999999996
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.2884375
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.30390625
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.296171875
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.3000390625
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.30197265625
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.30293945312500004
SAIU DO WHILE
Sharpe máximo (diário) ≈ 0.3029  |  anualizado ≈ 4.81
2021 -> {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.19732697774777835, 6: 0.04039514011353082, 7: 0.1999999931498726, 8: 0.0, 9: 0.0, 10: 0.0, 11: 0.0, 12: 0.020000210137912526, 13: 0.0, 14: 0.0, 15: 0.0, 16: 0.0, 17: 0.0, 18: 0.0, 19: 0.0, 20: 0.0, 21: 0.0, 22: 0.052581762145754926, 23: 0.0, 24: 0.0, 25: 0.0, 26: 0.0, 27: 0.0, 28: 0.0, 29: 0.0, 30: 0.0, 31: 0.0, 32: 0.0, 33: 0.0, 34: 0.020004167335548575, 35: 0.0, 36: 0.0, 37: 0.0, 38: 0.0, 39: 0.0, 40: 0.0, 41: 0.0, 42: 0.0, 43: 0.0, 44: 0.0, 45: 0.049690684267040514, 46: 0.020001155042270423, 47: 0.0, 48: 0.0, 49: 0.0, 50: 0.0, 51: 0.0, 52: 0.0, 53: 0.0, 54: 0.0, 55: 0.0, 56: 0.0, 57: 0.0, 58: 0.0, 59: 0.19999996727371466, 60: 0.0, 61: 0.0, 62: 0.0, 63: 0.0, 64: 0.0, 65: 0.0, 66: 0.19999996331276657, 67: 0.0, 68: 0.0}
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=
DELETADO DPS DO WHILE
COMEÇANDO ANO NOVO:  2020
Nao consta model
Score Atualizado
Retornos atualizados
Excessos Atualizados
Sigmas Atualizados
-----
# ------ CRIAÇÃO DO MODELO
## Carteira criada para o ano:  2021
## UTILIZANDO SCORE DO ANO DE:  2020
## UTILIZANDO DADOS DE RETORNO DE:  2020
## UTILIZANDO EXCESSO DO ANO DE:  2020
## UTILIZANDO SIGMAS DO ANO DE:  2020
65
65
65
65
MODEL.S.VALUE =>  2
Começando o WHILE do ano 2020
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.505
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.2575
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.38125
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.443125
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.4121875
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.42765624999999996
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.419921875
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.41605468749999996
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.41412109374999995
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.41508789062499996
============================
SAIU DO WHILE
Sharpe máximo (diário) ≈ 0.4141  |  anualizado ≈ 6.57
2020 -> {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0, 6: 0.0, 7: 0.0, 8: 0.07243674060464222, 9: 0.10753090869735718, 10: 0.0, 11: 0.0, 12: 0.0, 13: 0.0, 14: 0.0, 15: 0.0, 16: 0.10812012072039702, 17: 0.0, 18: 0.0, 19: 0.0, 20: 0.0, 21: 0.0, 22: 0.08500891699001929, 23: 0.0, 24: 0.0, 25: 0.0, 26: 0.0, 27: 0.0, 28: 0.0, 29: 0.0, 30: 0.0, 31: 0.0, 32: 0.08398982425308305, 33: 0.0, 34: 0.0, 35: 0.0, 36: 0.0, 37: 0.0, 38: 0.0, 39: 0.0, 40: 0.0, 41: 0.0, 42: 0.0, 43: 0.0, 44: 0.0, 45: 0.0, 46: 0.04764493584580791, 47: 0.0, 48: 0.0, 49: 0.0, 50: 0.0, 51: 0.0, 52: 0.0, 53: 0.0, 54: 0.19999999744125077, 55: 0.07526855581256645, 56: 0.20000000441766286, 57: 0.0, 58: 0.0, 59: 0.0, 60: 0.0, 61: 0.020000001538861556, 62: 0.0, 63: 0.0, 64: 0.0}
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=
DELETADO DPS DO WHILE
COMEÇANDO ANO NOVO:  2019
Nao consta model
Score Atualizado
Retornos atualizados
Excessos Atualizados
Sigmas Atualizados
-----
# ------ CRIAÇÃO DO MODELO
## Carteira criada para o ano:  2020
## UTILIZANDO SCORE DO ANO DE:  2019
## UTILIZANDO DADOS DE RETORNO DE:  2019
## UTILIZANDO EXCESSO DO ANO DE:  2019
## UTILIZANDO SIGMAS DO ANO DE:  2019
64
64
64
64
MODEL.S.VALUE =>  2
Começando o WHILE do ano 2019
==================
Modelo Resolveu....Condição:  unknown
Atualização do S_HI : 0.505
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.2575
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.13375
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.07187500000000001
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.1028125
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.08734375
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.07960937500000001
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.0757421875
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.07767578125
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.078642578125
============================
SAIU DO WHILE
Sharpe máximo (diário) ≈ 0.0777  |  anualizado ≈ 1.23

In [64]:
carteiras_anuais

{2026: {'pesos': {0: 0.15919821525601546,
   1: 1.332914160911375e-10,
   2: 6.049270150771435e-11,
   3: 9.239982613526304e-11,
   4: 4.406373216192304e-11,
   5: 1.3189011208021934e-10,
   6: 2.908023814903517e-10,
   7: 3.1786605775710817e-11,
   8: 0.0,
   9: 1.0227901314444976e-10,
   10: 3.050936056508452e-10,
   11: 1.285762281444118e-10,
   12: 5.6863118723030225e-11,
   13: 4.018713519726888e-10,
   14: 2.3625786471650625e-10,
   15: 3.054041613404318e-11,
   16: 0.19999999620553435,
   17: 3.0797539251597653e-11,
   18: 5.4743176178064496e-11,
   19: 0.02183999633991567,
   20: 4.998742416145063e-11,
   21: 5.5029024073695306e-11,
   22: 4.912153109960645e-11,
   23: 1.0187501680026052e-10,
   24: 9.747203815181747e-11,
   25: 0.0,
   26: 8.48564534931576e-11,
   27: 1.0120489774298435e-10,
   28: 1.0111051812973966e-10,
   29: 7.06965645655839e-11,
   30: 1.5002972147442912e-10,
   31: 1.6758779273047405e-10,
   32: 6.875355665973299e-11,
   33: 9.046382366415212e-11,
   34: 7.571154776574967e-11,
   35: 1.9895148331740273e-10,
   36: 1.7712282242997034e-10,
   37: 2.7334151103478564e-10,
   38: 1.1814071169040327e-10,
   39: 5.863547307530613e-11,
   40: 9.326170147968514e-11,
   41: 3.591759216382009e-11,
   42: 6.521103127669842e-11,
   43: 6.917898636225386e-11,
   44: 6.582857200505284e-11,
   45: 9.229573542329423e-11,
   46: 0.02000000089145336,
   47: 0.13526870797717963,
   48: 7.623091909200315e-11,
   49: 0.17109221675012634,
   50: 1.5765375937434793e-10,
   51: 2.41934776480775e-10,
   52: 7.010942141149544e-11,
   53: 4.3612705934283935e-11,
   54: 7.239148272182156e-11,
   55: 1.9171916036097176e-10,
   56: 1.7413736689918172e-10,
   57: 0.07419984486583824,
   58: 3.131094764131028e-11,
   59: 1.8581517407825188e-10,
   60: 1.784565085963095e-10,
   61: 8.287094411420974e-11,
   62: 4.559511130538129e-11,
   63: 1.679223578236134e-10,
   64: 0.047068587494959645,
   65: 0.10627436909860834,
   66: 2.1284394414144565e-10,
   67: 2.0947822291540977e-10,
   68: 0.06505805993850468,
   69: 4.048916497519956e-11},
  'sharpe_anual': np.float64(6.3130623422158205)},
 2025: {'pesos': {0: 0.0,
   1: 0.0,
   2: 0.0,
   3: 0.0,
   4: 0.0,
   5: 0.0,
   6: 0.19999998921286022,
   7: 0.0,
   8: 0.0,
   9: 0.08082852781470028,
   10: 0.0,
   11: 0.0,
   12: 0.11601485209971876,
   13: 0.1999997236623416,
   14: 0.0,
   15: 0.0,
   16: 0.0,
   17: 0.0,
   18: 0.0,
   19: 0.0,
   20: 0.0,
   21: 0.0,
   22: 0.0,
   23: 0.0,
   24: 0.1999995061807389,
   25: 0.0,
   26: 0.0,
   27: 0.0,
   28: 0.020000251210369347,
   29: 0.0,
   30: 0.0,
   31: 0.0,
   32: 0.0,
   33: 0.0,
   34: 0.0,
   35: 0.0,
   36: 0.0,
   37: 0.0,
   38: 0.0,
   39: 0.0,
   40: 0.0,
   41: 0.0,
   42: 0.0,
   43: 0.0,
   44: 0.0,
   45: 0.0,
   46: 0.020004598313835054,
   47: 0.12314776365808804,
   48: 0.0,
   49: 0.0,
   50: 0.020004240701396506,
   51: 0.0,
   52: 0.0,
   53: 0.0,
   54: 0.0,
   55: 0.0,
   56: 0.0,
   57: 0.0,
   58: 0.0,
   59: 0.02000061665706453,
   60: 0.0,
   61: 0.0,
   62: 0.0,
   63: 0.0,
   64: 0.0,
   65: 0.0,
   66: 0.0,
   67: 0.0,
   68: 0.0,
   69: 0.0},
  'sharpe_anual': np.float64(2.9212815061934267)},
 2024: {'pesos': {0: 1.0709454558924824e-10,
   1: 9.7168579034738e-11,
   2: 1.3818180141846874e-10,
   3: 9.501633330533251e-11,
   4: 8.722041450127235e-11,
   5: 5.582316674969642e-11,
   6: 0.0552870071998626,
   7: 3.526625249896076e-11,
   8: 7.039693909616476e-11,
   9: 8.538691993387413e-10,
   10: 2.9856128633482015e-10,
   11: 1.28940563043256e-10,
   12: 3.2095541113270606e-11,
   13: 1.387066683437126e-10,
   14: 9.562056013672148e-11,
   15: 4.5281957401620476e-11,
   16: 0.04909980956075749,
   17: 1.8339797342875105e-10,
   18: 8.410415856788514e-11,
   19: 0.19999999974585603,
   20: 9.512872801011614e-11,
   21: 2.151577635942838e-10,
   22: 5.947309496796824e-11,
   23: 9.400739733325747e-11,
   24: 0.19999999792924836,
   25: 6.85941927299798e-11,
   26: 9.897370770466438e-11,
   27: 9.860091341303429e-11,
   28: 3.87080968108277e-11,
   29: 6.846754591084237e-11,
   30: 7.220359465968124e-11,
   31: 8.07925117271623e-11,
   32: 4.2574321987423735e-11,
   33: 2.084348486665423e-10,
   34: 3.133959623327526e-11,
   35: 2.342304418428966e-10,
   36: 2.5400699160587895e-10,
   37: 5.3988594463690124e-11,
   38: 2.70768295958563e-10,
   39: 1.1436631245934599e-10,
   40: 6.941131431438582e-11,
   41: 2.3779064361200457e-11,
   42: 1.212717176778998e-10,
   43: 2.4587929049184537e-11,
   44: 2.1575773620639453e-11,
   45: 1.160553183539293e-10,
   46: 3.572435726972745e-10,
   47: 0.05786623309294054,
   48: 0.02172465656396488,
   49: 2.768206676589504e-10,
   50: 6.493487330897967e-10,
   51: 1.134078866121824e-10,
   52: 9.354916084731465e-11,
   53: 7.661147174001775e-11,
   54: 4.424888527083837e-11,
   55: 1.576502562193335e-10,
   56: 0.020000000093999527,
   57: 7.399068408030482e-11,
   58: 9.544976246964223e-11,
   59: 0.11630920192971717,
   60: 4.119876761973446e-10,
   61: 4.213657047197242e-11,
   62: 5.1450994908014705e-11,
   63: 0.14128757175767437,
   64: 0.13842551489440763,
   65: 7.981822951891646e-11,
   66: 0.0,
   67: 0.0,
   68: 1.0320749573345563e-10,
   69: 3.778720149032294e-11},
  'sharpe_anual': np.float64(6.896264476916503)},
 2023: {'pesos': {0: 0.0,
   1: 0.0,
   2: 0.0,
   3: 0.0,
   4: 0.0,
   5: 0.19999999284306555,
   6: 0.0,
   7: 0.1999999997647705,
   8: 0.0,
   9: 0.0,
   10: 0.0,
   11: 0.0,
   12: 0.0,
   13: 0.0,
   14: 0.0,
   15: 0.0,
   16: 0.020000014023537488,
   17: 0.0,
   18: 0.020000566338625958,
   19: 0.0,
   20: 0.0,
   21: 0.0,
   22: 0.0,
   23: 0.1999999991066663,
   24: 0.0,
   25: 0.0,
   26: 0.0,
   27: 0.0,
   28: 0.0,
   29: 0.0,
   30: 0.0,
   31: 0.0,
   32: 0.0,
   33: 0.0,
   34: 0.0,
   35: 0.0,
   36: 0.0,
   37: 0.020000025737106297,
   38: 0.0,
   39: 0.0,
   40: 0.0,
   41: 0.0,
   42: 0.0,
   43: 0.0,
   44: 0.0,
   45: 0.0,
   46: 0.0,
   47: 0.07295374375177928,
   48: 0.0,
   49: 0.0,
   50: 0.0,
   51: 0.0,
   52: 0.0,
   53: 0.0,
   54: 0.078402623765658,
   55: 0.0,
   56: 0.0,
   57: 0.0,
   58: 0.0,
   59: 0.0,
   60: 0.0,
   61: 0.0,
   62: 0.0,
   63: 0.0,
   64: 0.020000014194770245,
   65: 0.0,
   66: 0.0,
   67: 0.16864302805378936,
   68: 0.0},
  'sharpe_anual': np.float64(3.5351784900888825)},
 2022: {'pesos': {0: 0.0,
   1: 0.0,
   2: 0.0,
   3: 0.0,
   4: 0.0,
   5: 0.19732697774777835,
   6: 0.04039514011353082,
   7: 0.1999999931498726,
   8: 0.0,
   9: 0.0,
   10: 0.0,
   11: 0.0,
   12: 0.020000210137912526,
   13: 0.0,
   14: 0.0,
   15: 0.0,
   16: 0.0,
   17: 0.0,
   18: 0.0,
   19: 0.0,
   20: 0.0,
   21: 0.0,
   22: 0.052581762145754926,
   23: 0.0,
   24: 0.0,
   25: 0.0,
   26: 0.0,
   27: 0.0,
   28: 0.0,
   29: 0.0,
   30: 0.0,
   31: 0.0,
   32: 0.0,
   33: 0.0,
   34: 0.020004167335548575,
   35: 0.0,
   36: 0.0,
   37: 0.0,
   38: 0.0,
   39: 0.0,
   40: 0.0,
   41: 0.0,
   42: 0.0,
   43: 0.0,
   44: 0.0,
   45: 0.049690684267040514,
   46: 0.020001155042270423,
   47: 0.0,
   48: 0.0,
   49: 0.0,
   50: 0.0,
   51: 0.0,
   52: 0.0,
   53: 0.0,
   54: 0.0,
   55: 0.0,
   56: 0.0,
   57: 0.0,
   58: 0.0,
   59: 0.19999996727371466,
   60: 0.0,
   61: 0.0,
   62: 0.0,
   63: 0.0,
   64: 0.0,
   65: 0.0,
   66: 0.19999996331276657,
   67: 0.0,
   68: 0.0},
  'sharpe_anual': np.float64(4.809014731671954)},
 2021: {'pesos': {0: 0.0,
   1: 0.0,
   2: 0.0,
   3: 0.0,
   4: 0.0,
   5: 0.0,
   6: 0.0,
   7: 0.0,
   8: 0.07243674060464222,
   9: 0.10753090869735718,
   10: 0.0,
   11: 0.0,
   12: 0.0,
   13: 0.0,
   14: 0.0,
   15: 0.0,
   16: 0.10812012072039702,
   17: 0.0,
   18: 0.0,
   19: 0.0,
   20: 0.0,
   21: 0.0,
   22: 0.08500891699001929,
   23: 0.0,
   24: 0.0,
   25: 0.0,
   26: 0.0,
   27: 0.0,
   28: 0.0,
   29: 0.0,
   30: 0.0,
   31: 0.0,
   32: 0.08398982425308305,
   33: 0.0,
   34: 0.0,
   35: 0.0,
   36: 0.0,
   37: 0.0,
   38: 0.0,
   39: 0.0,
   40: 0.0,
   41: 0.0,
   42: 0.0,
   43: 0.0,
   44: 0.0,
   45: 0.0,
   46: 0.04764493584580791,
   47: 0.0,
   48: 0.0,
   49: 0.0,
   50: 0.0,
   51: 0.0,
   52: 0.0,
   53: 0.0,
   54: 0.19999999744125077,
   55: 0.07526855581256645,
   56: 0.20000000441766286,
   57: 0.0,
   58: 0.0,
   59: 0.0,
   60: 0.0,
   61: 0.020000001538861556,
   62: 0.0,
   63: 0.0,
   64: 0.0},
  'sharpe_anual': np.float64(6.573968560371388)},
 2020: {'pesos': {0: 0.0,
   1: 1.7882427204888025e-09,
   2: 0.0,
   3: 7.179184861393732e-10,
   4: 4.2064684536479056e-09,
   5: 0.0,
   6: 1.1598001979569515e-09,
   7: 4.87480987024977e-10,
   8: 9.821055904744795e-10,
   9: 0.0,
   10: 0.0,
   11: 0.0,
   12: 1.208613896575732e-09,
   13: 0.19999999671339297,
   14: 0.020000000402906067,
   15: 0.0,
   16: 0.0,
   17: 0.0,
   18: 0.0,
   19: 5.955214950022799e-10,
   20: 0.0,
   21: 1.8738614012636206e-09,
   22: 0.0,
   23: 0.02885848087459416,
   24: 1.0753741601039616e-09,
   25: 2.959931524551883e-09,
   26: 8.951796088250204e-10,
   27: 8.788462049193233e-10,
   28: 6.900875931804203e-10,
   29: 6.882993015777378e-10,
   30: 4.1677268660191344e-10,
   31: 0.0,
   32: 1.4259303533552828e-09,
   33: 1.4274666038794783e-09,
   34: 1.4045758317601621e-09,
   35: 0.019999970946000558,
   36: 0.0,
   37: 1.8341131618791096e-08,
   38: 0.0,
   39: 0.0,
   40: 6.415551202134805e-10,
   41: 1.005263618066675e-09,
   42: 0.0,
   43: 0.0,
   44: 7.646190429246182e-10,
   45: 0.0256895247181039,
   46: 9.377108464151305e-10,
   47: 0.08545199520365308,
   48: 7.66701640000364e-10,
   49: 0.0,
   50: 0.0,
   51: 0.0,
   52: 2.1376670165249811e-10,
   53: 0.19999999965649753,
   54: 0.019999998569059634,
   55: 0.0,
   56: 1.0044518253335475e-09,
   57: 8.931015277054979e-10,
   58: 0.0,
   59: 0.0,
   60: 1.3533112124932605e-09,
   61: 0.19999998862294174,
   62: 0.19999999932676774,
   63: 0.0},
  'sharpe_anual': np.float64(1.2330648004809233)},
 2019: {'pesos': {0: 6.987126734820937e-11,
   1: 9.027981268864719e-11,
   2: 7.270621860707977e-11,
   3: 7.662266621700304e-11,
   4: 6.778428935680841e-11,
   5: 1.190173555449682e-10,
   6: 8.6017123031247e-11,
   7: 4.9875838269748795e-11,
   8: 7.818929635181724e-11,
   9: 0.03327437775287557,
   10: 2.943862687419492e-11,
   11: 0.1413942552523767,
   12: 0.0,
   13: 1.0322350947850648e-10,
   14: 2.9433401321281725e-10,
   15: 1.94522231638759e-09,
   16: 9.429986758456564e-11,
   17: 1.4638000487299506e-10,
   18: 3.2819605659145953e-10,
   19: 9.12103010920536e-11,
   20: 1.1214147926353661e-10,
   21: 7.712125136574513e-11,
   22: 0.07392480081931335,
   23: 0.0,
   24: 2.5563776008869466e-10,
   25: 1.4865667907382694e-10,
   26: 4.68674927917728e-11,
   27: 4.625045789362079e-11,
   28: 4.3048639588957364e-11,
   29: 7.6181937994286e-11,
   30: 0.18774448035104366,
   31: 0.15575214302828144,
   32: 6.878150254935392e-11,
   33: 0.04869947255132453,
   34: 1.0388797013138136e-10,
   35: 8.397314916877988e-11,
   36: 8.568323595502655e-11,
   37: 1.0167622001320352e-10,
   38: 0.0,
   39: 6.373506603320291e-11,
   40: 7.849104103933605e-11,
   41: 5.791047113328797e-11,
   42: 5.602407068466768e-11,
   43: 5.303404299451788e-11,
   44: 0.04865400844968444,
   45: 9.062216318348535e-11,
   46: 7.388205442707447e-11,
   47: 1.0983565621200278e-10,
   48: 1.2434403746332486e-10,
   49: 1.0104687534148018e-10,
   50: 0.18506740355411594,
   51: 3.0095053058075846e-10,
   52: 3.601131497586283e-11,
   53: 0.026846810261616904,
   54: 3.5806883778095844e-10,
   55: 1.276957568048462e-10,
   56: 0.09864224231773643,
   57: 6.430001998831924e-11,
   58: 5.135971118130647e-11,
   59: 4.6177470237919125e-11,
   60: 1.8833488489930429e-10,
   61: 5.827549491647414e-11},
  'sharpe_anual': np.float64(6.957654175306048)},
 2018: {'pesos': {0: 0.0,
   1: 0.0,
   2: 0.0,
   3: 0.0,
   4: 0.0,
   5: 0.0,
   6: 0.0,
   7: 0.0,
   8: 0.0,
   9: 0.0,
   10: 0.0,
   11: 0.0,
   12: 0.0,
   13: 0.0,
   14: 0.0,
   15: 0.0,
   16: 0.03190137887390288,
   17: 0.0,
   18: 0.0,
   19: 0.0,
   20: 0.0,
   21: 0.0,
   22: 0.0,
   23: 0.190128341179584,
   24: 0.020000003193416497,
   25: 0.0,
   26: 0.0,
   27: 0.0,
   28: 0.0,
   29: 0.0,
   30: 0.19999999923705983,
   31: 0.0,
   32: 0.0,
   33: 0.0,
   34: 0.0,
   35: 0.0,
   36: 0.0,
   37: 0.0,
   38: 0.0,
   39: 0.0,
   40: 0.0,
   41: 0.0,
   42: 0.0,
   43: 0.0,
   44: 0.0,
   45: 0.02963461366853838,
   46: 0.0,
   47: 0.0,
   48: 0.0,
   49: 0.1087247153615505,
   50: 0.0,
   51: 0.0,
   52: 0.15815275666984888,
   53: 0.1259464363170056,
   54: 0.0,
   55: 0.0810805968907208,
   56: 0.0,
   57: 0.0,
   58: 0.0,
   59: 0.054431159378841715,
   60: 0.0,
   61: 0.0},
  'sharpe_anual': np.float64(6.389799465202751)},
 2017: {'pesos': {0: 9.845818670513019e-11,
   1: 0.0,
   2: 7.189465214927685e-11,
   3: 0.061750889938794726,
   4: 5.067592720297129e-10,
   5: 0.0,
   6: 6.39741497240781e-10,
   7: 0.08151712688976298,
   8: 8.743483124001043e-10,
   9: 3.7364360503874663e-10,
   10: 5.855449877983925e-11,
   11: 0.1710362324603177,
   12: 3.8773899846620773e-10,
   13: 1.1975432266244354e-10,
   14: 0.06892640698936889,
   15: 4.8153661081883976e-11,
   16: 9.701779657797478e-10,
   17: 3.6968288035530883e-10,
   18: 6.749593195068038e-11,
   19: 1.3903291471242644e-10,
   20: 1.361743393839939e-10,
   21: 8.214625127370191e-10,
   22: 0.04225168021768996,
   23: 4.974467999665078e-10,
   24: 3.356947509119854e-08,
   25: 9.433351436173688e-10,
   26: 3.378015181501482e-10,
   27: 1.566695084940761e-10,
   28: 0.0,
   29: 2.2094392739193897e-10,
   30: 0.0,
   31: 2.6498439359003894e-10,
   32: 7.803631162424918e-10,
   33: 1.368896636547172e-10,
   34: 2.2375962485600985e-10,
   35: 0.05166657653967112,
   36: 1.3304856710437556e-10,
   37: 0.0,
   38: 1.976222238527014e-10,
   39: 6.006755138009646e-11,
   40: 6.873436305116149e-11,
   41: 8.964099434209769e-11,
   42: 0.1999999989234381,
   43: 1.27117794256214e-10,
   44: 1.2930204227760245e-10,
   45: 7.024220114654808e-11,
   46: 1.695777994131439e-10,
   47: 4.662068816247244e-11,
   48: 0.05822374489845006,
   49: 0.19999999782196515,
   50: 0.0646273012892667,
   51: 1.0025961545780774e-10,
   52: 2.994801934597569e-10,
   53: 2.863751398854299e-10,
   54: 1.5673480384482608e-10,
   55: 2.3436475316245507e-10,
   56: 1.7833887587602018e-10},
  'sharpe_anual': np.float64(6.48188401278707)},
 2016: {'pesos': {0: 1.5787015454349266e-11,
   1: 3.920610042795701e-12,
   2: 6.603423621605737e-12,
   3: 1.4058600114858565e-11,
   4: 2.3666059303550108e-11,
   5: 8.408622186983876e-12,
   6: 6.525586003000779e-12,
   7: 5.76663233051998e-12,
   8: 9.14448881285652e-12,
   9: 5.693472068133409e-12,
   10: 2.6488051306465945e-11,
   11: 2.2445375588118365e-11,
   12: 5.927598362656362e-12,
   13: 5.970226808256984e-11,
   14: 1.8074479274796902e-11,
   15: 1.75097715941519e-11,
   16: 1.419872373584986e-11,
   17: 2.3737613818393733e-11,
   18: 0.07810350218377679,
   19: 9.299084441983109e-12,
   20: 9.842939140415116e-12,
   21: 0.01999999993113947,
   22: 3.138291881416488e-11,
   23: 1.2143756483066105e-11,
   24: 0.13937759747374098,
   25: 9.564799441253801e-12,
   26: 6.524498124952924e-12,
   27: 0.1476037445769218,
   28: 1.3466247881907504e-11,
   29: 1.0972275597436896e-11,
   30: 0.020000000011712676,
   31: 7.352915007563344e-12,
   32: 1.1102090982700102e-11,
   33: 0.03203452884523933,
   34: 7.896090665069471e-12,
   35: 0.13246873621442823,
   36: 0.19999999967940726,
   37: 6.267962590403878e-12,
   38: 5.4725200180654765e-12,
   39: 5.722034425394778e-11,
   40: 3.4259840671973735e-12,
   41: 6.142786366473234e-12,
   42: 0.20000000004364288,
   43: 5.853923965188379e-12,
   44: 1.133086724020237e-11,
   45: 0.03041189092235532,
   46: 2.6200813057234334e-11,
   47: 6.192212306984372e-12,
   48: 5.864148388326765e-11,
   49: 1.1254057977469802e-11,
   50: 2.048078518307525e-11,
   51: 4.954035559101725e-12,
   52: 7.488910457571944e-12,
   53: 4.080744586047545e-12,
   54: 7.117024565768384e-12},
  'sharpe_anual': np.float64(7.586898583798891)}}

In [68]:
linhas = []
for an in anos:
    an = int(an.split('-')[0])+1
    print(an)
    for k, v in carteiras_anuais[an]['pesos'].items():
        if v >= vb_peso_minimo:
            linhas.append({'ano': an, 'ativo': lista_ativos_finais[an-1][k], 'peso': round(v, 4)})

df_portfolios = pd.DataFrame(linhas)

# # visões instantâneas:
# df_portfolios[df_portfolios['ano'] == 2016].sort_values('peso', ascending=False)  # uma carteira
# df_portfolios.pivot(index='ativo', columns='ano', values='peso')                  # matriz ativo × ano
# df_portfolios.groupby('ativo')['ano'].count().sort_values(ascending=False)

2026
2025
2024
2023
2022
2021
2020
2019
2018
2017
2016

In [69]:
df_portfolios

      ano  ativo    peso
0    2026  ABEV3  0.1592
1    2026  CSMG3  0.2000
2    2026  CXSE3  0.0218
3    2026  PETR3  0.0200
4    2026  PETR4  0.1353
..    ...    ...     ...
102  2016  MGLU3  0.0320
103  2016  MRVE3  0.1325
104  2016  MULT3  0.2000
105  2016  RADL3  0.2000
106  2016  SBSP3  0.0304

[107 rows x 3 columns]

In [70]:
df_portfolios.to_csv('carteiras_mf.csv')