In [1]:
import pandas as pd
import numpy as np
import random
import pyomo.environ as pyo
from pyomo.environ import *
from pyomo.environ import SolverFactory
import yfinance as yf
from pathlib import Path
import os
import matplotlib.pyplot as plt

In [2]:
anos = ['2025-12-31',
 '2024-12-31',
 '2023-12-31',
 '2022-12-31',
 '2021-12-31',
 '2020-12-31',
 '2019-12-31',
 '2018-12-31',
 '2017-12-31',
 '2016-12-31',
 '2015-12-31',
 ]

## LER OS RETORNOS, SCORE e SELIC

In [3]:
# Retornos

dfs = {}
for ano in anos:
    ano_usado = ano.split('-')[0]
    nome = f'df_ativos_{ano_usado}.csv'
    caminho = Path('retornos_ativos') / nome
    dfs[ano_usado] = pd.read_csv(caminho).set_index('date')

In [4]:
## SELIC para Sigma e excesso
selic_d = pd.read_csv('selic/selic_diario.csv').set_index('date')

In [5]:
## SCORE para score
score_todos_anos = pd.read_csv('score_piotroski/piotroski.csv').set_index('Unnamed: 0').reset_index()

In [6]:
score_todos_anos.rename(columns={'Unnamed: 0': 'date'}, inplace=True)

In [7]:
score_todos_anos.set_index('date', inplace=True)

In [8]:
lista_ativos_finais = score_todos_anos.columns.tolist()
score_todos_anos

,ABEV3,ALOS3,ANIM3,AXIA3,AZZA3,B3SA3,BBAS3,BBDC3,BBDC4,BBSE3,...,TAEE11,TEND3,TOTS3,UGPA3,USIM5,VALE3,VBBR3,VIVT3,WEGE3,YDUQ3
date,,,,,,,,,,,,,,,,,,,,,
2015,0.375,0.625,0.125,0.500,0.125,0.625,0.625,0.375,0.375,0.375,...,0.625,0.750,0.125,0.875,0.125,0.125,0.000,0.375,0.625,0.250
2016,0.625,0.750,0.375,0.750,0.750,0.000,0.500,0.500,0.500,0.625,...,0.375,0.875,0.500,0.375,0.250,1.000,0.000,0.875,0.875,0.500
2017,0.625,0.625,1.000,0.500,0.625,0.625,0.500,0.375,0.375,0.500,...,0.375,0.750,0.625,0.375,0.875,0.750,0.875,0.875,0.375,0.875
2018,0.625,0.875,0.375,0.750,0.500,0.750,0.750,0.125,0.125,0.250,...,0.500,0.750,0.750,0.500,0.875,1.000,0.750,0.625,0.875,0.875
2019,0.375,0.625,0.125,0.375,0.375,0.750,0.625,0.500,0.500,0.375,...,0.375,0.375,0.625,0.500,0.750,0.500,0.500,0.375,1.000,0.500
2020,0.375,0.500,0.250,0.750,0.500,0.625,0.500,0.250,0.250,0.500,...,0.625,0.500,0.625,0.500,0.625,0.875,0.500,0.625,0.750,0.375
2021,0.500,0.750,0.500,0.500,0.750,0.625,0.500,0.375,0.375,0.500,...,0.500,0.125,0.500,0.500,0.875,0.875,0.625,0.375,0.625,0.500
2022,0.375,0.625,0.750,0.375,0.625,0.750,0.750,0.500,0.500,0.625,...,0.500,0.250,0.875,0.625,0.500,0.375,0.375,0.500,0.500,0.625
2023,0.750,0.625,0.625,0.625,0.375,0.375,0.625,0.250,0.250,0.500,...,0.375,0.625,0.875,0.625,0.500,0.625,0.875,0.750,0.875,0.875
2024,0.625,0.750,0.875,0.500,0.250,0.750,0.375,0.625,0.625,0.500,...,0.875,0.875,0.625,0.250,0.375,0.250,0.500,0.625,0.500,0.750
2025,0.625,0.875,0.875,0.500,0.875,0.500,0.625,0.375,0.375,0.375,...,0.500,0.750,0.625,0.500,0.750,0.500,0.375,0.875,0.500,0.625

## EXCESSO DOS ANOS e SIGMA (MAtriz de covariancia)

##### EXCESSO PARA TODOS

In [9]:
dict_sigma = {}
dict_excesso = {}
for an in anos:
    ano = an.split("-")[0]
    if ano == '2015':
        pass
    else:
        try:
            print(f"=============== \n EXCESSO {ano}\n ============")
            print("Atualização, Ano: ",ano)
            df = dfs[ano]
            # df_f = pd.DataFrame(eval(df))
            df_f = df.copy()
            slc = selic_d[selic_d.index.isin(df_f.index)]
            slc['valor_diario'] = slc['valor_diario']/100

            print(f"Tamanho DF de {ano}: ", len(df_f))
            print(f"Tamanho Selic: ", len(slc['valor_diario']))
            ano = int(ano)
            dict_excesso[ano] = df_f.sub(slc['valor_diario'],axis=0)
            print("tamanho final do Excesso: ",len(dict_excesso[ano]))

            print(f"============\n SIGMA {ano}\n===========")            
            dict_sigma[ano] = dict_excesso[ano].cov()
            print('Tamanho final do SIGMA: ',len(dict_sigma[ano]))

        except Exception as e:
            print(e)
            print("ERror")

===============
 EXCESSO 2025
 ============
Atualização, Ano:  2025
Tamanho DF de 2025:  250
Tamanho Selic:  250
tamanho final do Excesso:  250
============
 SIGMA 2025
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2024
 ============
Atualização, Ano:  2024
Tamanho DF de 2024:  251
Tamanho Selic:  251
tamanho final do Excesso:  251
============
 SIGMA 2024
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2023
 ============
Atualização, Ano:  2023
Tamanho DF de 2023:  246
Tamanho Selic:  246
tamanho final do Excesso:  246
============
 SIGMA 2023
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2022
 ============
Atualização, Ano:  2022
Tamanho DF de 2022:  251
Tamanho Selic:  251
tamanho final do Excesso:  251
============
 SIGMA 2022
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2021
 ============
Atualização, Ano:  2021
Tamanho DF de 2021:  249
Tamanho Selic:  249
tamanho final do Excesso:  249
============
 SIGMA 2021
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2020
 ============
Atualização, Ano:  2020
Tamanho DF de 2020:  246
Tamanho Selic:  246
tamanho final do Excesso:  246
============
 SIGMA 2020
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2019
 ============
Atualização, Ano:  2019
Tamanho DF de 2019:  250
Tamanho Selic:  250
tamanho final do Excesso:  250
============
 SIGMA 2019
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2018
 ============
Atualização, Ano:  2018
Tamanho DF de 2018:  245
Tamanho Selic:  245
tamanho final do Excesso:  245
============
 SIGMA 2018
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2017
 ============
Atualização, Ano:  2017
Tamanho DF de 2017:  244
Tamanho Selic:  244
tamanho final do Excesso:  244
============
 SIGMA 2017
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2016
 ============
Atualização, Ano:  2016
Tamanho DF de 2016:  251
Tamanho Selic:  251
tamanho final do Excesso:  251
============
 SIGMA 2016
===========
Tamanho final do SIGMA:  78

## Hiperparâmetros

In [10]:
vb_cardinalidade_max = 10
vb_cardinalidade_min = 10
vb_peso_maximo = 0.20
vb_peso_minimo = 0.02
vb_theta = 0.5

### Fazendo otimização ano a ano e comparando com o proximo ano

In [11]:
anos = ['2015-12-31', '2016-12-31', '2017-12-31', '2018-12-31', '2019-12-31', '2020-12-31', '2021-12-31', '2022-12-31', '2023-12-31', '2024-12-31', '2025-12-31']
print(anos)

['2015-12-31', '2016-12-31', '2017-12-31', '2018-12-31', '2019-12-31', '2020-12-31', '2021-12-31', '2022-12-31', '2023-12-31', '2024-12-31', '2025-12-31']

In [12]:
score_usado = score_todos_anos[score_todos_anos.index.isin(['2015'])]
score_usado

Empty DataFrame
Columns: [ABEV3, ALOS3, ANIM3, AXIA3, AZZA3, B3SA3, BBAS3, BBDC3, BBDC4, BBSE3, BEEF3, BPAC11, BRAP4, BRAV3, BRKM5, CMIG4, COGN3, CPFE3, CPLE3, CSAN3, CSMG3, CSNA3, CVCB3, CYRE3, DIRR3, ECOR3, EGIE3, EMBJ3, ENEV3, ENGI11, EQTL3, EZTC3, FLRY3, GGBR4, GOAU4, HYPE3, IGTI11, ISAE4, ITSA4, ITUB3, ITUB4, JHSF3, KLBN11, LREN3, MDNE3, MGLU3, MOTV3, MOVI3, MRVE3, MULT3, PETR3, PETR4, POMO4, PRIO3, PSSA3, RADL3, RAIL3, RAPT4, RENT3, SANB11, SAPR11, SBSP3, SLCE3, SMFT3, SUZB3, TAEE11, TEND3, TOTS3, UGPA3, USIM5, VALE3, VBBR3, VIVT3, WEGE3, YDUQ3]
Index: []

[0 rows x 75 columns]

In [13]:
from pydoc import text


y = []

carteiras_anuais = {}

melhor_pesos = None
historico = []
carteiras_criadas = []
for a in anos:
    y.append(a.split('-')[0])

print("=-"*48)
print("Anos totais: ",y)
print("=-"*48)

for an in anos:
    ano = an.split("-")[0]
    print("COMEÇANDO ANO NOVO: ",ano)
    #deletar modelo
    if 'model' in locals():
        del model
        print('Modelo Antigo deletado \n Iniciando Novo')
    else:
        print("Nao consta model")
        pass

    print("-"*15)
    print("Começando Modelo do ano: ", ano)
    print("="*6)

    try:

        score_usado = score_todos_anos[score_todos_anos.index.isin([int(ano)])]
        # print(score_usado)
        print("Score Atualizado")
        

        ano_um = int(ano)+1
        # df_usado = f'df_ativos_{ano_um}'
        # retorno_usado = pd.DataFrame(eval(df_usado))
        df_usado = dfs[str(ano_um)]
        retorno_usado = df_usado.copy()
        retorno_usado = retorno_usado[lista_ativos_finais]
        print("Retornos atualizados")

        excesso_usado = dict_excesso[ano_um]
        print("Excessos Atualizados")
        
        sigma_usado = dict_sigma[ano_um]
        print("Sigmas Atualizados")
        
        print("-----")
    except Exception as e:
        print("ERRRRRRRRRRRROR")
        print(e)

    # if df_usado == 'df_ativos_2015':
    #     continue
    # else:
    print("# ------ CRIAÇÃO DO MODELO")
    print("## UTILIZANDO SCORE DO ANO DE: ",ano)
    print("## UTILIZANDO DADOS DE RETORNO DE: ",str(ano_um))
    print("## UTILIZANDO EXCESSO DO ANO DE: ",ano_um)
    print("## UTILIZANDO SIGMAS DO ANO DE: ",ano_um)

    model = pyo.ConcreteModel()

    #---------VARIÁVEIS-----------
    model.nome_ativos = pyo.Set(initialize = lista_ativos_finais)
    model.ativos = pyo.RangeSet(0, len(lista_ativos_finais)-1)
    model.dias = pyo.RangeSet(0, len(retorno_usado)-1)
    model.retornos_ativos = pyo.Param(model.dias, model.ativos, initialize=lambda model,dia, ativo: retorno_usado.iloc[dia, ativo])    
    model.theta = pyo.Param(initialize=vb_theta)
    model.score = pyo.Param(model.ativos, initialize=lambda model,a: score_usado.iloc[0,a])
    model.cardinalidade_valor_max = pyo.Param(initialize=vb_cardinalidade_max)
    model.cardinalidade_valor_min = pyo.Param(initialize=vb_cardinalidade_min)
    model.peso_maximo = pyo.Param(initialize=vb_peso_maximo)
    model.peso_minimo = pyo.Param(initialize=vb_peso_minimo)
    model.x = pyo.Var(model.ativos, bounds=(0,1))
    model.y = pyo.Var(model.ativos, within=pyo.Binary)
    model.excesso = pyo.Param( model.ativos , initialize = lambda model,a: excesso_usado.mean().iloc[a])
    model.sigma = pyo.Param(model.ativos, model.ativos, initialize = lambda model,a,b: sigma_usado.iloc[a,b])
    model.s = pyo.Param(initialize = 2, mutable=True)
    model.r = pyo.Var(within=pyo.NonNegativeReals)
    
    #-------------------------------------- FUNÇÕES

    #=============================
    # Função Objetivo
    #=============================

    def func_objetivo_1(model):
        retorno_esperado = model.theta * sum(
            model.retornos_ativos[dia, a] * model.x[a] for a in model.ativos for dia in model.dias
        )
        # retorno_esperado = model.theta * model.r
        # A dúvida de qual retorno usar (Retorno BRUTO ou Excesso (retorno - selic))

        score_total = (1 - model.theta) * sum(
            model.x[a] * model.score[a] for a in model.ativos
        )
        return retorno_esperado + score_total
    model.obj1 = pyo.Objective(rule=func_objetivo_1, sense=pyo.maximize)

    #=============================
    # RESTRIÇÕES
    #=============================

    def def_r(model):
        return model.r == sum(model.excesso[a]*model.x[a]for a in model.ativos)
    model.const_def_r = pyo.Constraint(rule=def_r)

    ## modelos de Programação de Cone de Segunda Ordem (SOCP) 
    ## e Programação Quadrática com Restrições (QCP)
    def cone(model):
        return model.r**2 >= model.s**2 * sum(model.x[a]*model.sigma[a,b]*model.x[b] for a in model.ativos for b in model.ativos)
    model.constr_cone = pyo.Constraint(rule=cone)

    #REstricao 1 x só ativa se y = 1
    def restr_vinculo_x_y(model, a):
        return model.x[a] <= model.y[a]
    model.const_restr_vinculo_x_y = pyo.Constraint(model.ativos, rule=restr_vinculo_x_y)

    #peso maximo por acao
    def rule_peso_maximo(model, a):
        # return model.x[a] <= 1/model.cardinalidade_valor
        return model.x[a] <= model.peso_maximo
    model.const_peso_maximo = pyo.Constraint(model.ativos, rule=rule_peso_maximo)

    #peso minimo por acao
    def rule_peso_minimo(model, a):
        return model.x[a] >= model.peso_minimo * model.y[a]  # se y=1, então x >= 0.05
    model.const_peso_minimo = pyo.Constraint(model.ativos, rule=rule_peso_minimo)

    #Restrição 2 soma peso 1
    def soma_peso_1(model):
        return sum(model.x[a] for a in model.ativos) == 1
    model.const_soma_peso_1 = pyo.Constraint(rule=soma_peso_1)


    def cardinalidade_min(model):
        return sum(
            model.y[a] for a in model.ativos
            ) >= model.cardinalidade_valor_min
    model.const_cardinalidade_total_min = pyo.Constraint(rule=cardinalidade_min)

    def cardinalidade_max(model):
        return sum(
            model.y[a] for a in model.ativos
            ) <= model.cardinalidade_valor_max
    model.const_cardinalidade_total_max = pyo.Constraint(rule=cardinalidade_max)


    # NOTEBOOOK
    # opt = SolverFactory('cplex', executable='C:\\CPLEX_Studio2211\\cplex\\bin\\x64_win64\\cplex.exe')

    # PC
    opt = SolverFactory('cplex', executable='C:\\Program Files\\IBM\\ILOG\\CPLEX_Studio_Community222\\cplex\\bin\\x64_win64\\cplex.exe')

    s_lo = 0.01        # <-- o Sharpe DIÁRIO 
    s_hi = 1   # teto: 2x o melhor ativo individual
    tol  = 0.001
    print("MODEL.S.VALUE => ",model.s.value)
    melhor_pesos = None
    historico = []
    carteiras_criadas = []
    # print(f"Valor a ser batido com S_LO: {s_lo} e S_HI: {s_hi} ... Diferença: {s_hi-s_lo}")
    print(f"Começando o WHILE do ano {ano}")
    while s_hi - s_lo > tol:
        s_a_ser_usado = 0.5 * (s_lo + s_hi)
        # print(s_a_ser_usado)
        model.s.value = s_a_ser_usado
        print("="*18)
        # print("Objetivo: (É o S lá da restrição de sharpe): ",s_a_ser_usado)
        res = opt.solve(model, load_solutions=False, tee=False)
        tc = res.solver.termination_condition
        print(f"Modelo Resolveu....Condição: ",tc)
        if tc == pyo.TerminationCondition.optimal:
            model.solutions.load_from(res)
            melhor_pesos = {a: pyo.value(model.x[a]) for a in model.ativos}
            # print({x:i for x,i in melhor_pesos.items() if i>0})
            s_lo = model.s.value
            print(f"Valor encontrado para o Sharpe: ",s_lo)
            # print(f"Valor FO: ",pyo.value(model.obj1))
            # print(f"Atualização de Valores para próxima rodagem: TC {tc} com S_LO: {s_lo} e S_HI: {s_hi} ... Diferença: {s_hi-s_lo}")
            # print("="*28)
            # for x,i in melhor_pesos.items():
            #     if i>0:

            #         dc = {
            #         'ativos_selecionados':melhor_pesos,
            #         'sharpe':pyo.value(model.s),
            #             }
            historico.append((s_a_ser_usado, 'viavel'))
            # carteiras_criadas.append(dc)
        elif tc in (pyo.TerminationCondition.infeasible,
                    pyo.TerminationCondition.infeasibleOrUnbounded):
            s_hi = s_a_ser_usado
            print(f"Atualização do S_HI : {s_hi}")
            print("="*28)

            historico.append((s_a_ser_usado, 'inviavel'))
        else:
            print(f'status inesperado em s={s_a_ser_usado:.4f}: {tc}')
            pass
    print("SAIU DO WHILE")
    print(f'Sharpe máximo (diário) ≈ {s_a_ser_usado:.4f}  |  anualizado ≈ {s_a_ser_usado*np.sqrt(252):.2f}')
    # print(historico)
    carteiras_anuais[int(ano_um)] = {
        'pesos':  melhor_pesos,
        'sharpe_anual': s_lo*np.sqrt(252),
    }
    print(f"{ano_um} -> {melhor_pesos}")
    print("+-="*30)
    if 'model' in locals():
        del model
        print('DELETADO DPS DO WHILE')
    else:
        print("Nao consta model")
        pass

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Anos totais:  ['2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
COMEÇANDO ANO NOVO:  2015
Nao consta model
---------------
Começando Modelo do ano:  2015
======
Score Atualizado
Retornos atualizados
Excessos Atualizados
Sigmas Atualizados
-----
# ------ CRIAÇÃO DO MODELO
## UTILIZANDO SCORE DO ANO DE:  2015
## UTILIZANDO DADOS DE RETORNO DE:  2016
## UTILIZANDO EXCESSO DO ANO DE:  2016
## UTILIZANDO SIGMAS DO ANO DE:  2016
MODEL.S.VALUE =>  2
Começando o WHILE do ano 2015
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.505
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.2575
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.38125
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.31937499999999996
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.2884375
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.30390625
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.296171875
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.3000390625
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.29810546875
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.297138671875
SAIU DO WHILE
Sharpe máximo (diário) ≈ 0.2971  |  anualizado ≈ 4.72
2016 -> {0: 2.330595929611094e-09, 1: 1.4828504749610926e-08, 2: 0.027893063296608792, 3: 0.0842590620680534, 4: 0.0, 5: 2.5290052248789556e-09, 6: 2.5353464899245465e-09, 7: 1.604933422914451e-09, 8: 1.7671317090175754e-09, 9: 1.805869967250791e-09, 10: 2.135409831328136e-09, 11: 1.044514517499919e-08, 12: 0.0538779389185768, 13: 1.0540503742302939e-08, 14: 0.0, 15: 1.1298739750092706e-09, 16: 1.8653155174888056e-09, 17: 0.0, 18: 2.599076811468793e-09, 19: 2.293236430362913e-09, 20: 0.13987659656817758, 21: 7.056931940282786e-10, 22: 0.0, 23: 3.2308594194120865e-08, 24: 1.7628785560777982e-09, 25: 1.2561825006087339e-09, 26: 2.415505088377872e-09, 27: 1.7098859019916296e-09, 28: 1.730714678245653e-09, 29: 0.0, 30: 0.17423100710149386, 31: 8.649042763889123e-09, 32: 3.0375844946613965e-09, 33: 0.17485602595694588, 34: 1.20515903192222e-09, 35: 1.4665188066459006e-09, 36: 2.6286058950988494e-09, 37: 0.0, 38: 1.5347109530763044e-08, 39: 1.1696330241216834e-08, 40: 1.8649321378795884e-09, 41: 5.416014520070521e-09, 42: 1.7110787700654988e-09, 43: 2.7722926480941905e-09, 44: 2.062204105122395e-09, 45: 3.470238199622547e-08, 46: 1.818583420905274e-08, 47: 0.09657745398010095, 48: 3.304943851788678e-09, 49: 0.1355196569869584, 50: 5.428801629499043e-09, 51: 3.18947053071562e-09, 52: 1.045689791554676e-09, 53: 1.3768482597942516e-09, 54: 3.5667438283767022e-09, 55: 0.05292559189056065, 56: 2.3184494461032235e-09, 57: 5.078099312530238e-09, 58: 8.018761822653078e-09, 59: 2.8200355600188918e-09, 60: 4.74242283932827e-09, 61: 3.2413678978006542e-09, 62: 3.080246252768401e-08, 63: 8.907159759843442e-10, 64: 5.218477240686563e-09, 65: 3.019821536831754e-08, 66: 4.592020565666833e-09, 67: 0.059983276173285784, 68: 0.0, 69: 0.0, 70: 3.5543203500795358e-09, 71: 3.422704557846672e-09, 72: 2.186048451215036e-09, 73: 1.8140512321226576e-09, 74: 9.209103662565968e-09}
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=
DELETADO DPS DO WHILE
COMEÇANDO ANO NOVO:  2016
Nao consta model
---------------
Começando Modelo do ano:  2016
======
Score Atualizado
Retornos atualizados
Excessos Atualizados
Sigmas Atualizados
-----
# ------ CRIAÇÃO DO MODELO
## UTILIZANDO SCORE DO ANO DE:  2016
## UTILIZANDO DADOS DE RETORNO DE:  2017
## UTILIZANDO EXCESSO DO ANO DE:  2017
## UTILIZANDO SIGMAS DO ANO DE:  2017
MODEL.S.VALUE =>  2
Começando o WHILE do ano 2016
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.505
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.2575
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.38125
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.31937499999999996
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.35031249999999997
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.33484375
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.34257812499999996
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.3464453125
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.34451171875
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.34354492187499996
SAIU DO WHILE
Sharpe máximo (diário) ≈ 0.3435  |  anualizado ≈ 5.45
2017 -> {0: 0.059673707677341536, 1: 1.8621306458487627e-07, 2: 0.05429778197971775, 3: 4.221040727027553e-09, 4: 4.786305083621257e-08, 5: 6.118925501917509e-09, 6: 2.267931757766624e-09, 7: 3.5259196431101795e-09, 8: 3.9512686490882945e-09, 9: 3.451771792443874e-09, 10: 4.560129379390087e-09, 11: 1.066500282522609e-08, 12: 2.187454489983783e-08, 13: 1.3533943087400247e-07, 14: 3.6935168410930285e-08, 15: 1.684474481422918e-09, 16: 3.5712161666321806e-09, 17: 5.657911812679946e-09, 18: 2.5975183813110264e-09, 19: 3.860828042342802e-09, 20: 4.581748150118175e-09, 21: 1.7161838390806972e-09, 22: 0.1033963459275956, 23: 1.650107578564193e-07, 24: 2.9965681649121788e-09, 25: 3.3201696893911907e-09, 26: 2.638523572968042e-09, 27: 1.139709727609901e-08, 28: 1.9695739361219284e-08, 29: 4.75279938106133e-09, 30: 0.07185760035934494, 31: 1.3133442564093153e-08, 32: 5.909672675251726e-09, 33: 1.5737910888592873e-08, 34: 7.390223529597751e-09, 35: 4.628352740051503e-09, 36: 9.450462534739742e-09, 37: 2.538463051197563e-07, 38: 0.19999998533995586, 39: 9.658305344730484e-09, 40: 1.1997802365339476e-08, 41: 1.3068208542392864e-08, 42: 6.736326838291044e-09, 43: 1.4490825234536809e-09, 44: 1.2457707291510985e-08, 45: 4.338943456452083e-09, 46: 8.796946269446543e-08, 47: 1.0212956730032466e-08, 48: 1.7627200042209408e-09, 49: 3.4679884290858364e-09, 50: 3.940348493453319e-09, 51: 2.9884208757370367e-09, 52: 6.377133682703763e-09, 53: 4.123173436124156e-09, 54: 1.747519284765345e-08, 55: 0.0, 56: 0.07705517348448934, 57: 3.7272219298218395e-08, 58: 3.8082402801047336e-09, 59: 9.94980944193581e-09, 60: 0.09040521511933199, 61: 5.124191028075942e-09, 62: 1.2714356874655932e-08, 63: 1.7740156015008846e-09, 64: 0.1581638284636613, 65: 9.424567304788187e-08, 66: 8.646349146573581e-09, 67: 0.16514881552739136, 68: 5.6891833806964685e-09, 69: 3.739691877707065e-08, 70: 1.2044031567372043e-08, 71: 4.351475052222336e-09, 72: 1.4280104351571667e-08, 73: 0.020000032673566783, 74: 1.0640332816258215e-07}
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=
DELETADO DPS DO WHILE
COMEÇANDO ANO NOVO:  2017
Nao consta model
---------------
Começando Modelo do ano:  2017
======
Score Atualizado
Retornos atualizados
Excessos Atualizados
Sigmas Atualizados
-----
# ------ CRIAÇÃO DO MODELO
## UTILIZANDO SCORE DO ANO DE:  2017
## UTILIZANDO DADOS DE RETORNO DE:  2018
## UTILIZANDO EXCESSO DO ANO DE:  2018
## UTILIZANDO SIGMAS DO ANO DE:  2018
MODEL.S.VALUE =>  2
Começando o WHILE do ano 2017
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.505
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.2575
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.38125
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.31937499999999996
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.2884375
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.27296875
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.265234375
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.2613671875
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.26330078125
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.262333984375
============================
SAIU DO WHILE
Sharpe máximo (diário) ≈ 0.2623  |  anualizado ≈ 4.16
2018 -> {0: 0.0, 1: 6.099788589947339e-08, 2: 0.0, 3: 9.521056637619578e-09, 4: 2.783154698528342e-09, 5: 3.877165879248572e-09, 6: 4.698202070659502e-09, 7: 0.0, 8: 3.0461442238127933e-09, 9: 6.146144284512353e-09, 10: 0.0, 11: 0.05300449767750718, 12: 3.762927078677478e-09, 13: 0.19999988593895324, 14: 2.7809690359487472e-08, 15: 0.0, 16: 0.0, 17: 0.0, 18: 0.04617749123868128, 19: 3.6904340632651353e-09, 20: 1.4184433122783563e-07, 21: 0.0, 22: 0.0, 23: 5.01508655042274e-08, 24: 4.585644346558581e-09, 25: 0.05514935764621298, 26: 3.945296545371575e-09, 27: 1.7511705019561098e-08, 28: 9.426546784152513e-09, 29: 0.0736728240634291, 30: 8.969886012870912e-09, 31: 1.2241434591415544e-08, 32: 0.0, 33: 2.1673096181716066e-09, 34: 2.4601055707841863e-09, 35: 0.0, 36: 3.8022421002415774e-09, 37: 0.0, 38: 0.19999999617587605, 39: 0.0, 40: 0.0, 41: 5.240331949123565e-09, 42: 0.0, 43: 0.0, 44: 4.09601453783601e-09, 45: 0.0, 46: 5.60635888558261e-08, 47: 0.0, 48: 3.589208808717196e-09, 49: 0.0, 50: 3.95959927505982e-09, 51: 4.085235752832158e-09, 52: 6.373960842686064e-09, 53: 7.701904609807463e-09, 54: 4.313721235365676e-09, 55: 0.06271960287102539, 56: 9.072399207928535e-08, 57: 6.110380051559143e-09, 58: 1.0977700005937436e-08, 59: 3.563795333019078e-09, 60: 4.822868026353743e-09, 61: 3.828021138967177e-09, 62: 0.0, 63: 0.0, 64: 0.0, 65: 7.989705599015352e-08, 66: 2.092360846100372e-08, 67: 0.06456644315672719, 68: 2.1167588208364095e-08, 69: 1.7358158905268765e-08, 70: 0.044709290995455994, 71: 0.0, 72: 8.889196449806024e-10, 73: 8.394680181486115e-09, 74: 0.19999988593895324}
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=
DELETADO DPS DO WHILE
COMEÇANDO ANO NOVO:  2018
Nao consta model
---------------
Começando Modelo do ano:  2018
======
Score Atualizado
Retornos atualizados
Excessos Atualizados
Sigmas Atualizados
-----
# ------ CRIAÇÃO DO MODELO
## UTILIZANDO SCORE DO ANO DE:  2018
## UTILIZANDO DADOS DE RETORNO DE:  2019
## UTILIZANDO EXCESSO DO ANO DE:  2019
## UTILIZANDO SIGMAS DO ANO DE:  2019
MODEL.S.VALUE =>  2
Começando o WHILE do ano 2018
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.505
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.2575
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.13375
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.07187500000000001
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.1028125
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.11828125
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.110546875
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.1144140625
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.11248046875
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.113447265625
SAIU DO WHILE
Sharpe máximo (diário) ≈ 0.1134  |  anualizado ≈ 1.80
2019 -> {0: 0.0, 1: 0.16592529471983863, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0, 6: 0.0, 7: 0.0, 8: 0.0, 9: 0.0, 10: 0.0, 11: 0.0, 12: 0.0, 13: 0.0, 14: 0.0, 15: 0.0, 16: 0.0, 17: 0.0, 18: 0.19999998378200726, 19: 0.0, 20: 0.0, 21: 0.0, 22: 0.0, 23: 0.19999979817125044, 24: 0.0, 25: 0.0, 26: 0.0, 27: 0.0, 28: 0.0, 29: 0.1340752809536452, 30: 0.0, 31: 0.0, 32: 0.0, 33: 0.0, 34: 0.0, 35: 0.0, 36: 0.0, 37: 0.02000020617015391, 38: 0.0, 39: 0.0, 40: 0.0, 41: 0.0, 42: 0.0, 43: 0.020000014289986247, 44: 0.0, 45: 0.0, 46: 0.0, 47: 0.020000014288506833, 48: 0.0, 49: 0.0, 50: 0.0, 51: 0.0, 52: 0.0, 53: 0.0, 54: 0.0, 55: 0.0, 56: 0.0, 57: 0.19999931527065987, 58: 0.0, 59: 0.0, 60: 0.0, 61: 0.0, 62: 0.0, 63: 0.0, 64: 0.0, 65: 0.02000005043582701, 66: 0.0, 67: 0.0, 68: 0.0, 69: 0.0, 70: 0.0, 71: 0.0, 72: 0.0, 73: 0.0, 74: 0.020000050899461698}
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=
DELETADO DPS DO WHILE
COMEÇANDO ANO NOVO:  2019
Nao consta model
---------------
Começando Modelo do ano:  2019
======
Score Atualizado
Retornos atualizados
Excessos Atualizados
Sigmas Atualizados
-----
# ------ CRIAÇÃO DO MODELO
## UTILIZANDO SCORE DO ANO DE:  2019
## UTILIZANDO DADOS DE RETORNO DE:  2020
## UTILIZANDO EXCESSO DO ANO DE:  2020
## UTILIZANDO SIGMAS DO ANO DE:  2020
MODEL.S.VALUE =>  2
Começando o WHILE do ano 2019
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.505
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.2575
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.38125
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.31937499999999996
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.2884375
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.30390625
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.296171875
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.3000390625
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.30197265625
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.301005859375
============================
SAIU DO WHILE
Sharpe máximo (diário) ≈ 0.3010  |  anualizado ≈ 4.78
2020 -> {0: 2.214580207897281e-09, 1: 2.478049020471412e-08, 2: 2.83733363275649e-09, 3: 4.070530647498418e-09, 4: 5.285659411650984e-09, 5: 2.591770597153287e-09, 6: 1.1377178649783516e-09, 7: 1.4471673151800729e-09, 8: 2.1093128326892833e-09, 9: 1.497513751095927e-09, 10: 4.1318983891266414e-09, 11: 0.04264725164536119, 12: 1.2144568116174359e-08, 13: 0.0, 14: 5.308155347844906e-09, 15: 3.1577992477397597e-09, 16: 9.808182289627245e-10, 17: 2.9167346554790222e-09, 18: 2.4638870007633646e-09, 19: 2.260079921496336e-09, 20: 2.419592543828122e-09, 21: 0.12155433754658135, 22: 7.19389157361931e-09, 23: 0.19999996796138353, 24: 2.8079814074807544e-09, 25: 2.118986046420646e-09, 26: 1.4048616091416316e-09, 27: 2.6735702257761183e-09, 28: 1.8487218749747875e-09, 29: 0.03852447967232634, 30: 2.399970217997305e-09, 31: 4.817936902074204e-09, 32: 1.0729582340377034e-09, 33: 4.360650321248804e-09, 34: 4.3767344937505295e-09, 35: 2.993934387181555e-09, 36: 1.7159447735777449e-09, 37: 6.67785552094468e-08, 38: 8.991719247170447e-10, 39: 0.0, 40: 1.5314115951694717e-09, 41: 1.749632898490158e-09, 42: 1.396234633466738e-09, 43: 5.140348491837619e-09, 44: 1.0442836070296007e-08, 45: 2.4044652116923214e-09, 46: 3.9656316476517374e-09, 47: 0.03881857257113801, 48: 1.446136726180737e-09, 49: 4.843919382168215e-09, 50: 2.768289021850329e-09, 51: 2.4611139622149658e-09, 52: 1.9533043178795577e-09, 53: 2.993689877966473e-09, 54: 1.3363949073074056e-09, 55: 0.04528097497212347, 56: 1.6050993065112427e-09, 57: 3.6642389505736086e-09, 58: 1.5024053882908049e-09, 59: 6.0369735934641825e-09, 60: 3.0152426717350007e-09, 61: 1.904280028038084e-09, 62: 1.6469788490822215e-09, 63: 1.410726578273611e-09, 64: 0.14521883189595353, 65: 5.8086127635789024e-08, 66: 9.575390264474998e-09, 67: 0.11297883406523587, 68: 0.1999999950898841, 69: 1.8843761242879034e-09, 70: 5.5112582053829775e-08, 71: 1.6258537938360903e-09, 72: 2.7934105526820975e-09, 73: 0.0549763520150274, 74: 4.2004843049010436e-08}
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=
DELETADO DPS DO WHILE
COMEÇANDO ANO NOVO:  2020
Nao consta model
---------------
Começando Modelo do ano:  2020
======
Score Atualizado
Retornos atualizados
Excessos Atualizados
Sigmas Atualizados
-----
# ------ CRIAÇÃO DO MODELO
## UTILIZANDO SCORE DO ANO DE:  2020
## UTILIZANDO DADOS DE RETORNO DE:  2021
## UTILIZANDO EXCESSO DO ANO DE:  2021
## UTILIZANDO SIGMAS DO ANO DE:  2021
MODEL.S.VALUE =>  2
Começando o WHILE do ano 2020
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.505
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.2575
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.13375
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.195625
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.1646875
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.14921875
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.156953125
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.1530859375
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.15501953125
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.154052734375
============================
SAIU DO WHILE
Sharpe máximo (diário) ≈ 0.1541  |  anualizado ≈ 2.45

In [14]:
carteiras_anuais

{2016: {'pesos': {0: 2.330595929611094e-09,
   1: 1.4828504749610926e-08,
   2: 0.027893063296608792,
   3: 0.0842590620680534,
   4: 0.0,
   5: 2.5290052248789556e-09,
   6: 2.5353464899245465e-09,
   7: 1.604933422914451e-09,
   8: 1.7671317090175754e-09,
   9: 1.805869967250791e-09,
   10: 2.135409831328136e-09,
   11: 1.044514517499919e-08,
   12: 0.0538779389185768,
   13: 1.0540503742302939e-08,
   14: 0.0,
   15: 1.1298739750092706e-09,
   16: 1.8653155174888056e-09,
   17: 0.0,
   18: 2.599076811468793e-09,
   19: 2.293236430362913e-09,
   20: 0.13987659656817758,
   21: 7.056931940282786e-10,
   22: 0.0,
   23: 3.2308594194120865e-08,
   24: 1.7628785560777982e-09,
   25: 1.2561825006087339e-09,
   26: 2.415505088377872e-09,
   27: 1.7098859019916296e-09,
   28: 1.730714678245653e-09,
   29: 0.0,
   30: 0.17423100710149386,
   31: 8.649042763889123e-09,
   32: 3.0375844946613965e-09,
   33: 0.17485602595694588,
   34: 1.20515903192222e-09,
   35: 1.4665188066459006e-09,
   36: 2.6286058950988494e-09,
   37: 0.0,
   38: 1.5347109530763044e-08,
   39: 1.1696330241216834e-08,
   40: 1.8649321378795884e-09,
   41: 5.416014520070521e-09,
   42: 1.7110787700654988e-09,
   43: 2.7722926480941905e-09,
   44: 2.062204105122395e-09,
   45: 3.470238199622547e-08,
   46: 1.818583420905274e-08,
   47: 0.09657745398010095,
   48: 3.304943851788678e-09,
   49: 0.1355196569869584,
   50: 5.428801629499043e-09,
   51: 3.18947053071562e-09,
   52: 1.045689791554676e-09,
   53: 1.3768482597942516e-09,
   54: 3.5667438283767022e-09,
   55: 0.05292559189056065,
   56: 2.3184494461032235e-09,
   57: 5.078099312530238e-09,
   58: 8.018761822653078e-09,
   59: 2.8200355600188918e-09,
   60: 4.74242283932827e-09,
   61: 3.2413678978006542e-09,
   62: 3.080246252768401e-08,
   63: 8.907159759843442e-10,
   64: 5.218477240686563e-09,
   65: 3.019821536831754e-08,
   66: 4.592020565666833e-09,
   67: 0.059983276173285784,
   68: 0.0,
   69: 0.0,
   70: 3.5543203500795358e-09,
   71: 3.422704557846672e-09,
   72: 2.186048451215036e-09,
   73: 1.8140512321226576e-09,
   74: 9.209103662565968e-09},
  'sharpe_anual': np.float64(4.7169301840876345)},
 2017: {'pesos': {0: 0.059673707677341536,
   1: 1.8621306458487627e-07,
   2: 0.05429778197971775,
   3: 4.221040727027553e-09,
   4: 4.786305083621257e-08,
   5: 6.118925501917509e-09,
   6: 2.267931757766624e-09,
   7: 3.5259196431101795e-09,
   8: 3.9512686490882945e-09,
   9: 3.451771792443874e-09,
   10: 4.560129379390087e-09,
   11: 1.066500282522609e-08,
   12: 2.187454489983783e-08,
   13: 1.3533943087400247e-07,
   14: 3.6935168410930285e-08,
   15: 1.684474481422918e-09,
   16: 3.5712161666321806e-09,
   17: 5.657911812679946e-09,
   18: 2.5975183813110264e-09,
   19: 3.860828042342802e-09,
   20: 4.581748150118175e-09,
   21: 1.7161838390806972e-09,
   22: 0.1033963459275956,
   23: 1.650107578564193e-07,
   24: 2.9965681649121788e-09,
   25: 3.3201696893911907e-09,
   26: 2.638523572968042e-09,
   27: 1.139709727609901e-08,
   28: 1.9695739361219284e-08,
   29: 4.75279938106133e-09,
   30: 0.07185760035934494,
   31: 1.3133442564093153e-08,
   32: 5.909672675251726e-09,
   33: 1.5737910888592873e-08,
   34: 7.390223529597751e-09,
   35: 4.628352740051503e-09,
   36: 9.450462534739742e-09,
   37: 2.538463051197563e-07,
   38: 0.19999998533995586,
   39: 9.658305344730484e-09,
   40: 1.1997802365339476e-08,
   41: 1.3068208542392864e-08,
   42: 6.736326838291044e-09,
   43: 1.4490825234536809e-09,
   44: 1.2457707291510985e-08,
   45: 4.338943456452083e-09,
   46: 8.796946269446543e-08,
   47: 1.0212956730032466e-08,
   48: 1.7627200042209408e-09,
   49: 3.4679884290858364e-09,
   50: 3.940348493453319e-09,
   51: 2.9884208757370367e-09,
   52: 6.377133682703763e-09,
   53: 4.123173436124156e-09,
   54: 1.747519284765345e-08,
   55: 0.0,
   56: 0.07705517348448934,
   57: 3.7272219298218395e-08,
   58: 3.8082402801047336e-09,
   59: 9.94980944193581e-09,
   60: 0.09040521511933199,
   61: 5.124191028075942e-09,
   62: 1.2714356874655932e-08,
   63: 1.7740156015008846e-09,
   64: 0.1581638284636613,
   65: 9.424567304788187e-08,
   66: 8.646349146573581e-09,
   67: 0.16514881552739136,
   68: 5.6891833806964685e-09,
   69: 3.739691877707065e-08,
   70: 1.2044031567372043e-08,
   71: 4.351475052222336e-09,
   72: 1.4280104351571667e-08,
   73: 0.020000032673566783,
   74: 1.0640332816258215e-07},
  'sharpe_anual': np.float64(5.453606564762182)},
 2018: {'pesos': {0: 0.0,
   1: 6.099788589947339e-08,
   2: 0.0,
   3: 9.521056637619578e-09,
   4: 2.783154698528342e-09,
   5: 3.877165879248572e-09,
   6: 4.698202070659502e-09,
   7: 0.0,
   8: 3.0461442238127933e-09,
   9: 6.146144284512353e-09,
   10: 0.0,
   11: 0.05300449767750718,
   12: 3.762927078677478e-09,
   13: 0.19999988593895324,
   14: 2.7809690359487472e-08,
   15: 0.0,
   16: 0.0,
   17: 0.0,
   18: 0.04617749123868128,
   19: 3.6904340632651353e-09,
   20: 1.4184433122783563e-07,
   21: 0.0,
   22: 0.0,
   23: 5.01508655042274e-08,
   24: 4.585644346558581e-09,
   25: 0.05514935764621298,
   26: 3.945296545371575e-09,
   27: 1.7511705019561098e-08,
   28: 9.426546784152513e-09,
   29: 0.0736728240634291,
   30: 8.969886012870912e-09,
   31: 1.2241434591415544e-08,
   32: 0.0,
   33: 2.1673096181716066e-09,
   34: 2.4601055707841863e-09,
   35: 0.0,
   36: 3.8022421002415774e-09,
   37: 0.0,
   38: 0.19999999617587605,
   39: 0.0,
   40: 0.0,
   41: 5.240331949123565e-09,
   42: 0.0,
   43: 0.0,
   44: 4.09601453783601e-09,
   45: 0.0,
   46: 5.60635888558261e-08,
   47: 0.0,
   48: 3.589208808717196e-09,
   49: 0.0,
   50: 3.95959927505982e-09,
   51: 4.085235752832158e-09,
   52: 6.373960842686064e-09,
   53: 7.701904609807463e-09,
   54: 4.313721235365676e-09,
   55: 0.06271960287102539,
   56: 9.072399207928535e-08,
   57: 6.110380051559143e-09,
   58: 1.0977700005937436e-08,
   59: 3.563795333019078e-09,
   60: 4.822868026353743e-09,
   61: 3.828021138967177e-09,
   62: 0.0,
   63: 0.0,
   64: 0.0,
   65: 7.989705599015352e-08,
   66: 2.092360846100372e-08,
   67: 0.06456644315672719,
   68: 2.1167588208364095e-08,
   69: 1.7358158905268765e-08,
   70: 0.044709290995455994,
   71: 0.0,
   72: 8.889196449806024e-10,
   73: 8.394680181486115e-09,
   74: 0.19999988593895324},
  'sharpe_anual': np.float64(4.149075473984338)},
 2019: {'pesos': {0: 0.0,
   1: 0.16592529471983863,
   2: 0.0,
   3: 0.0,
   4: 0.0,
   5: 0.0,
   6: 0.0,
   7: 0.0,
   8: 0.0,
   9: 0.0,
   10: 0.0,
   11: 0.0,
   12: 0.0,
   13: 0.0,
   14: 0.0,
   15: 0.0,
   16: 0.0,
   17: 0.0,
   18: 0.19999998378200726,
   19: 0.0,
   20: 0.0,
   21: 0.0,
   22: 0.0,
   23: 0.19999979817125044,
   24: 0.0,
   25: 0.0,
   26: 0.0,
   27: 0.0,
   28: 0.0,
   29: 0.1340752809536452,
   30: 0.0,
   31: 0.0,
   32: 0.0,
   33: 0.0,
   34: 0.0,
   35: 0.0,
   36: 0.0,
   37: 0.02000020617015391,
   38: 0.0,
   39: 0.0,
   40: 0.0,
   41: 0.0,
   42: 0.0,
   43: 0.020000014289986247,
   44: 0.0,
   45: 0.0,
   46: 0.0,
   47: 0.020000014288506833,
   48: 0.0,
   49: 0.0,
   50: 0.0,
   51: 0.0,
   52: 0.0,
   53: 0.0,
   54: 0.0,
   55: 0.0,
   56: 0.0,
   57: 0.19999931527065987,
   58: 0.0,
   59: 0.0,
   60: 0.0,
   61: 0.0,
   62: 0.0,
   63: 0.0,
   64: 0.0,
   65: 0.02000005043582701,
   66: 0.0,
   67: 0.0,
   68: 0.0,
   69: 0.0,
   70: 0.0,
   71: 0.0,
   72: 0.0,
   73: 0.0,
   74: 0.020000050899461698},
  'sharpe_anual': np.float64(1.8009195105842197)},
 2020: {'pesos': {0: 2.214580207897281e-09,
   1: 2.478049020471412e-08,
   2: 2.83733363275649e-09,
   3: 4.070530647498418e-09,
   4: 5.285659411650984e-09,
   5: 2.591770597153287e-09,
   6: 1.1377178649783516e-09,
   7: 1.4471673151800729e-09,
   8: 2.1093128326892833e-09,
   9: 1.497513751095927e-09,
   10: 4.1318983891266414e-09,
   11: 0.04264725164536119,
   12: 1.2144568116174359e-08,
   13: 0.0,
   14: 5.308155347844906e-09,
   15: 3.1577992477397597e-09,
   16: 9.808182289627245e-10,
   17: 2.9167346554790222e-09,
   18: 2.4638870007633646e-09,
   19: 2.260079921496336e-09,
   20: 2.419592543828122e-09,
   21: 0.12155433754658135,
   22: 7.19389157361931e-09,
   23: 0.19999996796138353,
   24: 2.8079814074807544e-09,
   25: 2.118986046420646e-09,
   26: 1.4048616091416316e-09,
   27: 2.6735702257761183e-09,
   28: 1.8487218749747875e-09,
   29: 0.03852447967232634,
   30: 2.399970217997305e-09,
   31: 4.817936902074204e-09,
   32: 1.0729582340377034e-09,
   33: 4.360650321248804e-09,
   34: 4.3767344937505295e-09,
   35: 2.993934387181555e-09,
   36: 1.7159447735777449e-09,
   37: 6.67785552094468e-08,
   38: 8.991719247170447e-10,
   39: 0.0,
   40: 1.5314115951694717e-09,
   41: 1.749632898490158e-09,
   42: 1.396234633466738e-09,
   43: 5.140348491837619e-09,
   44: 1.0442836070296007e-08,
   45: 2.4044652116923214e-09,
   46: 3.9656316476517374e-09,
   47: 0.03881857257113801,
   48: 1.446136726180737e-09,
   49: 4.843919382168215e-09,
   50: 2.768289021850329e-09,
   51: 2.4611139622149658e-09,
   52: 1.9533043178795577e-09,
   53: 2.993689877966473e-09,
   54: 1.3363949073074056e-09,
   55: 0.04528097497212347,
   56: 1.6050993065112427e-09,
   57: 3.6642389505736086e-09,
   58: 1.5024053882908049e-09,
   59: 6.0369735934641825e-09,
   60: 3.0152426717350007e-09,
   61: 1.904280028038084e-09,
   62: 1.6469788490822215e-09,
   63: 1.410726578273611e-09,
   64: 0.14521883189595353,
   65: 5.8086127635789024e-08,
   66: 9.575390264474998e-09,
   67: 0.11297883406523587,
   68: 0.1999999950898841,
   69: 1.8843761242879034e-09,
   70: 5.5112582053829775e-08,
   71: 1.6258537938360903e-09,
   72: 2.7934105526820975e-09,
   73: 0.0549763520150274,
   74: 4.2004843049010436e-08},
  'sharpe_anual': np.float64(4.762972457879794)},
 2021: {'pesos': {0: 4.887313609417882e-09,
   1: 0.01999985363223913,
   2: 0.0,
   3: 3.3980097131124185e-09,
   4: 3.5274532994616315e-08,
   5: 1.8331618840105989e-09,
   6: 1.2479782547761657e-08,
   7: 1.4993250108149906e-09,
   8: 1.7817635716488396e-09,
   9: 9.53983745843608e-09,
   10: 0.10829231660430946,
   11: 2.38424139107067e-09,
   12: 0.19884126582576372,
   13: 1.732023641863238e-09,
   14: 5.7882160044116715e-09,
   15: 1.1411554398764738e-08,
   16: 0.0,
   17: 0.13333701013683633,
   18: 6.919932504286346e-08,
   19: 2.5030583024428928e-09,
   20: 2.650304970970281e-09,
   21: 0.0,
   22: 1.1341102157191551e-09,
   23: 2.4525298239380816e-09,
   24: 1.0682099619533847e-09,
   25: 2.507183270385495e-09,
   26: 0.0,
   27: 1.3595355089097765e-08,
   28: 2.289004816568005e-09,
   29: 2.0432552028231417e-09,
   30: 8.051295134402498e-09,
   31: 5.932312958191681e-09,
   32: 0.0,
   33: 1.1651073024166368e-09,
   34: 2.877114092309178e-09,
   35: 2.5263436382632783e-09,
   36: 0.0199999751334105,
   37: 4.792039901232358e-09,
   38: 0.0,
   39: 1.3016878320599311e-08,
   40: 3.8478476546642475e-09,
   41: 6.79725560503976e-09,
   42: 6.9280169597187275e-09,
   43: 1.9307726179235893e-09,
   44: 2.588694437452885e-09,
   45: 0.0,
   46: 1.1118563324251611e-09,
   47: 0.0,
   48: 3.943201151130471e-09,
   49: 2.9509021677284605e-09,
   50: 1.1695207326986032e-09,
   51: 2.594590698826521e-09,
   52: 0.1999999822616834,
   53: 0.026530956142140637,
   54: 2.5062549762127304e-09,
   55: 4.475017809583713e-09,
   56: 3.2102878523563177e-09,
   57: 3.4961979257272573e-09,
   58: 2.426677693272088e-09,
   59: 1.2949187773874787e-09,
   60: 3.4699914095960474e-09,
   61: 3.067613210437028e-09,
   62: 3.8412994001654284e-09,
   63: 4.622715160683495e-09,
   64: 6.6688457955151596e-09,
   65: 1.2156516820421361e-09,
   66: 0.09364169932214285,
   67: 2.8523951384322802e-09,
   68: 0.17282504022633371,
   69: 0.0,
   70: 0.026531593960006573,
   71: 0.0,
   72: 1.1933422477795927e-09,
   73: 3.587807455717856e-09,
   74: 1.2066266122018642e-08},
  'sharpe_anual': np.float64(2.430163919077062)},
 2022: {'pesos': {0: 2.7538003015082827e-08,
   1: 0.199999860193991,
   2: 2.582892907054916e-09,
   3: 1.2390270953721446e-08,
   4: 6.697380800758815e-09,
   5: 5.04961194693379e-09,
   6: 0.09195123924760414,
   7: 7.671123482021836e-09,
   8: 6.306870993481954e-09,
   9: 0.19999998665234398,
   10: 1.4149006944437964e-08,
   11: 6.605630964583437e-09,
   12: 1.4779645728159938e-08,
   13: 6.740242383650849e-09,
   14: 4.094763380215975e-09,
   15: 7.3782291633577354e-09,
   16: 5.69641009385253e-09,
   17: 7.922643278659518e-08,
   18: 4.7032697450034337e-08,
   19: 5.0833616728418e-09,
   20: 0.028963325584149668,
   21: 6.363876704957155e-09,
   22: 1.6590677737011242e-09,
   23: 2.836751954916962e-08,
   24: 9.132382132377505e-09,
   25: 0.03019759060848614,
   26: 5.648979315418038e-09,
   27: 8.357620080791878e-08,
   28: 0.15446157497897375,
   29: 7.2882726440209124e-09,
   30: 1.1382534540091977e-08,
   31: 2.4800579265841578e-08,
   32: 5.861528278593737e-09,
   33: 1.9798362920740433e-08,
   34: 2.0244869798282904e-08,
   35: 3.563143842723055e-08,
   36: 3.028905623495367e-08,
   37: 1.1499341308158797e-08,
   38: 2.832589122256383e-09,
   39: 1.7160979920892315e-08,
   40: 9.40400012186855e-09,
   41: 1.565337333768338e-08,
   42: 1.2707751309962281e-08,
   43: 4.796260062400558e-09,
   44: 1.182153882376377e-08,
   45: 4.427412844224149e-09,
   46: 8.056174547868764e-09,
   47: 3.440537789217229e-09,
   48: 1.1485014229014336e-08,
   49: 3.844465508260601e-09,
   50: 4.358367432249912e-09,
   51: 3.5040506297031694e-08,
   52: 0.027516147706611146,
   53: 0.020004667380223516,
   54: 0.1291593891117802,
   55: 0.11774516422971805,
   56: 1.7822821678211008e-07,
   57: 2.211073284176574e-08,
   58: 1.596145143090445e-08,
   59: 7.460704988254676e-09,
   60: 1.0563450808323716e-08,
   61: 8.495960861702565e-09,
   62: 2.642513275084041e-08,
   63: 2.8911221369718305e-08,
   64: 2.7442704894771775e-08,
   65: 4.2970119687687505e-09,
   66: 5.160808075158222e-09,
   67: 1.279435021102155e-08,
   68: 4.8497781519215164e-08,
   69: 5.2382435466304204e-09,
   70: 6.912582528690971e-09,
   71: 1.2111271530311465e-08,
   72: 4.405437137022174e-09,
   73: 1.9660121165367474e-08,
   74: 4.402019447005917e-09},
  'sharpe_anual': np.float64(1.5400132924286511)},
 2023: {'pesos': {0: 9.470009943709858e-09,
   1: 1.7590155356056977e-08,
   2: 7.919131711906772e-09,
   3: 1.0773726842455101e-08,
   4: 5.249570845030932e-09,
   5: 6.422829683954258e-09,
   6: 6.629307489207971e-08,
   7: 1.036728009537107e-08,
   8: 6.34845262020775e-08,
   9: 2.2697162122302326e-08,
   10: 4.774715637821307e-09,
   11: 1.6935156319727048e-07,
   12: 5.714288090444736e-09,
   13: 1.418110317800676e-08,
   14: 9.254618572642229e-09,
   15: 1.475288816881837e-08,
   16: 6.194599045613336e-09,
   17: 3.97592270021928e-08,
   18: 2.8280073688640032e-08,
   19: 5.476965442108767e-09,
   20: 0.0,
   21: 8.885702533158571e-09,
   22: 3.762734493482121e-09,
   23: 0.1999999468421508,
   24: 1.792976838694339e-08,
   25: 2.0983401676591772e-08,
   26: 1.7086418699873714e-08,
   27: 1.9388270305462373e-08,
   28: 0.06290483265200243,
   29: 9.01222766400625e-09,
   30: 1.499798638887633e-08,
   31: 1.4424491237881008e-08,
   32: 6.718046085428258e-09,
   33: 8.773633745956693e-09,
   34: 7.666423844965037e-09,
   35: 7.395513396289691e-09,
   36: 6.286093904706213e-09,
   37: 1.153669482884644e-08,
   38: 2.102612902024999e-08,
   39: 2.8996234968428712e-08,
   40: 1.8408139285271488e-08,
   41: 6.689596760718229e-08,
   42: 7.791706750866326e-08,
   43: 1.1876713406912011e-08,
   44: 0.0,
   45: 3.804489281244804e-09,
   46: 0.04935829560164667,
   47: 2.3890645806588036e-09,
   48: 1.078658899487474e-08,
   49: 4.933735554474495e-09,
   50: 6.580094216095566e-09,
   51: 1.5791142806680633e-08,
   52: 1.5276519714358866e-07,
   53: 0.12251046833835857,
   54: 0.07056103959722568,
   55: 0.020000063578064727,
   56: 0.08352232337969115,
   57: 2.1828247922966326e-08,
   58: 1.0775299171490914e-08,
   59: 2.1837896128785377e-08,
   60: 6.710232033243214e-09,
   61: 1.2170408946241625e-08,
   62: 4.5931332121304855e-08,
   63: 0.12476442689928277,
   64: 1.1673064304237089e-08,
   65: 6.507720258027495e-08,
   66: 1.4138904517080422e-08,
   67: 0.13431300100850835,
   68: 3.363274304002735e-08,
   69: 4.0541080116374913e-08,
   70: 5.425062123959573e-09,
   71: 0.1320641437823512,
   72: 4.166065567824372e-08,
   73: 6.36339782051998e-09,
   74: 1.2657592827859963e-07},
  'sharpe_anual': np.float64(5.192700346606613)},
 2024: {'pesos': {0: 0.024363642748970578,
   1: 0.0,
   2: 0.0,
   3: 0.0,
   4: 0.0,
   5: 0.0,
   6: 0.0,
   7: 0.0,
   8: 0.0,
   9: 0.1999999830414586,
   10: 0.0,
   11: 0.0,
   12: 0.0,
   13: 0.0,
   14: 0.0,
   15: 0.0,
   16: 0.0,
   17: 0.1757539888750952,
   18: 0.0,
   19: 0.0,
   20: 0.0,
   21: 0.0,
   22: 0.0,
   23: 0.0,
   24: 0.0,
   25: 0.03953242978708789,
   26: 0.0,
   27: 0.0,
   28: 0.16206906729588655,
   29: 0.0,
   30: 0.0,
   31: 0.0,
   32: 0.0,
   33: 0.0,
   34: 0.0,
   35: 0.0,
   36: 0.0,
   37: 0.0,
   38: 0.020384075661077125,
   39: 0.0,
   40: 0.0,
   41: 0.0,
   42: 0.0,
   43: 0.0,
   44: 0.0,
   45: 0.0,
   46: 0.0,
   47: 0.0,
   48: 0.0,
   49: 0.0,
   50: 0.0,
   51: 0.0,
   52: 0.19999910964540007,
   53: 0.0,
   54: 0.0,
   55: 0.0,
   56: 0.13789765023377742,
   57: 0.0,
   58: 0.0,
   59: 0.0,
   60: 0.0,
   61: 0.0,
   62: 0.020000021016864634,
   63: 0.020000041830122054,
   64: 0.0,
   65: 0.0,
   66: 0.0,
   67: 0.0,
   68: 0.0,
   69: 0.0,
   70: 0.0,
   71: 0.0,
   72: 0.0,
   73: 0.0,
   74: 0.0},
  'sharpe_anual': np.float64(2.73711241102479)},
 2025: {'pesos': {0: 2.2511498064817514e-08,
   1: 4.0870962772746136e-08,
   2: 3.444843100506799e-09,
   3: 3.286486826274567e-08,
   4: 2.1711785957065347e-09,
   5: 3.7778595586606e-09,
   6: 2.0575362062603803e-09,
   7: 1.4292104817734757e-08,
   8: 1.3562044075914021e-08,
   9: 5.237207646453424e-09,
   10: 1.8689158977423426e-09,
   11: 5.762619586106878e-09,
   12: 1.9930536036119886e-08,
   13: 2.230583960588244e-09,
   14: 1.8576054420368009e-09,
   15: 7.176565067134621e-09,
   16: 0.0,
   17: 0.0,
   18: 0.0,
   19: 1.0618334862226312e-09,
   20: 0.19999999864102438,
   21: 1.0608880210890123e-09,
   22: 1.8536194197170535e-09,
   23: 0.041393959276963876,
   24: 3.580147187449396e-09,
   25: 5.663505559589531e-09,
   26: 2.84627747350725e-09,
   27: 6.333780292547933e-09,
   28: 6.753229942431828e-09,
   29: 0.1283535823337896,
   30: 5.472217561227723e-09,
   31: 5.075585878050446e-09,
   32: 3.703336819197029e-09,
   33: 1.1638898917437608e-08,
   34: 5.046413637351662e-09,
   35: 5.479683793014712e-09,
   36: 4.036705424609977e-09,
   37: 5.190617545263999e-09,
   38: 3.5536590443138083e-09,
   39: 9.478439075188661e-09,
   40: 1.0609792455752177e-08,
   41: 0.12528964422280678,
   42: 8.463116062908146e-09,
   43: 0.09914806898817127,
   44: 0.0,
   45: 3.0115473791905102e-09,
   46: 6.68656611166525e-08,
   47: 1.3300798118625113e-09,
   48: 4.749159625093554e-09,
   49: 1.477602990889836e-08,
   50: 4.129890118783162e-09,
   51: 5.726418099320527e-09,
   52: 9.750159622041924e-08,
   53: 0.0,
   54: 1.400682598601125e-08,
   55: 0.14322366834458453,
   56: 2.3887889580930912e-08,
   57: 4.34939077693695e-09,
   58: 2.658700582181774e-09,
   59: 1.2681520182038643e-09,
   60: 3.6506890611000843e-09,
   61: 3.4193134068515938e-09,
   62: 0.02325219949890511,
   63: 1.7084396397177478e-08,
   64: 2.9195199933644162e-08,
   65: 1.9853714803198808e-09,
   66: 3.399803891366685e-09,
   67: 7.607289547913178e-09,
   68: 2.4574238577060434e-08,
   69: 0.024401005886029583,
   70: 3.4982577426399504e-09,
   71: 1.770231683151714e-08,
   72: 4.347536815290601e-09,
   73: 0.1481366168054839,
   74: 0.06680064610934644},
  'sharpe_anual': np.float64(4.256507446166044)},
 2026: {'pesos': {0: 2.4681637766363606e-08,
   1: 5.634810901918038e-08,
   2: 3.2567969153115185e-09,
   3: 3.2125166571219556e-08,
   4: 2.305963596579731e-09,
   5: 3.596470337219997e-09,

In [15]:
linhas = []
for an in anos:
    an = int(an.split('-')[0])+1
    print(an)
    for k, v in carteiras_anuais[an]['pesos'].items():
        if v >= vb_peso_minimo:
            linhas.append({'ano': an, 'ativo': lista_ativos_finais[k], 'peso': round(v, 4)})

df_portfolios = pd.DataFrame(linhas)

# # visões instantâneas:
# df_portfolios[df_portfolios['ano'] == 2016].sort_values('peso', ascending=False)  # uma carteira
# df_portfolios.pivot(index='ativo', columns='ano', values='peso')                  # matriz ativo × ano
# df_portfolios.groupby('ativo')['ano'].count().sort_values(ascending=False)

2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026

In [16]:
df_portfolios

      ano  ativo    peso
0    2016  ANIM3  0.0279
1    2016  AXIA3  0.0843
2    2016  BRAP4  0.0539
3    2016  CSMG3  0.1399
4    2016  EQTL3  0.1742
..    ...    ...     ...
102  2026  RADL3  0.1423
103  2026  SLCE3  0.0338
104  2026  USIM5  0.0294
105  2026  WEGE3  0.1545
106  2026  YDUQ3  0.0618

[107 rows x 3 columns]

In [17]:
df_portfolios.to_csv('carteiras_piotroski.csv')