In [1]:
import pandas as pd

In [2]:
DATA_PRINCIPAL = ['2022-03-31', '2022-06-30', '2022-09-30']

## BPA --------- FEITO

In [3]:
df = pd.read_csv('itr_cia_aberta_BPA_ind_2022.csv', sep=';', encoding='latin-1')
df=df[df['ORDEM_EXERC'] == 'ÚLTIMO']

In [4]:
df

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
1,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2022-03-31,1,Ativo Total,2.080279e+09,S
3,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2022-03-31,1.01,Caixa e Equivalentes de Caixa,4.550810e+07,S
5,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2022-03-31,1.01.01,Caixa,1.464667e+07,S
7,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2022-03-31,1.01.02,Aplicações de Liquidez,3.086143e+07,S
9,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2022-03-31,1.02,Ativos Financeiros,1.886945e+09,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288515,97.837.181/0001-47,2022-09-30,1,DEXCO S.A.,21091,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2022-09-30,1.02.04.01.04,Goodwill na aquisição da Satipel em 2009,4.550300e+04,N
288517,97.837.181/0001-47,2022-09-30,1,DEXCO S.A.,21091,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2022-09-30,1.02.04.01.05,Goodwill de empresa incorporada em 2010,2.402000e+03,N
288519,97.837.181/0001-47,2022-09-30,1,DEXCO S.A.,21091,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2022-09-30,1.02.04.01.06,Goodwill de empresa incorporada em 2011,0.000000e+00,N
288521,97.837.181/0001-47,2022-09-30,1,DEXCO S.A.,21091,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2022-09-30,1.02.04.01.07,Goodwill de empresa incorporada em 2012,0.000000e+00,N
288523,97.837.181/0001-47,2022-09-30,1,DEXCO S.A.,21091,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2022-09-30,1.02.04.01.08,Goodwill de empresa incorporada em 2014,0.000000e+00,N

In [5]:
df['DT_REFER'].unique().tolist()

['2022-03-31',
 '2022-06-30',
 '2022-09-30',
 '2022-12-31',
 '2022-05-31',
 '2022-08-31',
 '2022-11-30']

In [6]:
lista_ativos = df['DENOM_CIA'].unique().tolist()
lista_final = []
data_refer = df['DT_REFER'].unique().tolist()
datas = df['DT_FIM_EXERC'].unique().tolist()
for ativo in lista_ativos:
    dfativo = df[df['DENOM_CIA']==ativo]
    
    caixa = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="1.01.01"')['VL_CONTA'].values
    ativo_total = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="1"')['VL_CONTA'].values
    

    if len(caixa) == 3 and len(ativo_total) == 3:
        dicio = {
            'ativo': ativo,
            
            f'caixa_{DATA_PRINCIPAL[0]}': caixa[0],
            f'caixa_{DATA_PRINCIPAL[1]}': caixa[1],
            f'caixa_{DATA_PRINCIPAL[2]}': caixa[2],
            
           

            f'ativo_total_{DATA_PRINCIPAL[0]}': ativo_total[0],
            f'ativo_total_{DATA_PRINCIPAL[1]}': ativo_total[1],
            f'ativo_total_{DATA_PRINCIPAL[2]}': ativo_total[2],
            

        
        }    
        lista_final.append(dicio)

In [7]:
df_bpa = pd.DataFrame(lista_final)
print(df_bpa.shape)
df_bpa.head()

(702, 7)

,ativo,caixa_2022-03-31,caixa_2022-06-30,caixa_2022-09-30,ativo_total_2022-03-31,ativo_total_2022-06-30,ativo_total_2022-09-30
0,BCO BRASIL S.A.,14646674.0,28977508.0,13144473.0,2.080279e+09,2.135262e+09,2.187761e+09
1,BRB BANCO DE BRASILIA S.A.,195388.0,270516.0,243682.0,3.742471e+07,3.744494e+07,3.892248e+07
2,AXIA ENERGIA S.A.,3280706.0,2901153.0,4283537.0,1.391172e+08,1.639446e+08,1.663802e+08
3,COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB,491688.0,241439.0,256513.0,1.178707e+06,9.724560e+05,1.001220e+06
4,CARAMURU ALIMENTOS S.A.,464400.0,570105.0,2064042.0,7.941590e+06,8.783483e+06,9.440657e+06

## BPP ------------ Fazendo

In [8]:
df2 = pd.read_csv('itr_cia_aberta_BPP_ind_2022.csv', sep=';', encoding='latin-1')
df2=df2[df2['ORDEM_EXERC'] == 'ÚLTIMO']
df2.head(60)

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
1,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2,Passivo Total,2.080279e+09,S
3,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.01,Passivos Financeiros Avaliados ao Valor Justo ...,6.799548e+06,S
5,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.01.01,Instrumentos financeiros derivativos,6.799548e+06,N
7,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.02,Passivos Financeiros ao Custo Amortizado,1.834615e+09,S
9,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.02.01,Depósitos,1.834615e+09,S
11,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.02.01.01,Recursos de instituições financeiras,8.734851e+08,N
13,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.02.01.02,Recursos de clientes,6.413689e+08,N
15,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.02.01.03,Recursos de emissões de títulos e valores mobi...,2.020910e+08,N
17,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.02.01.06,Outros passivos financeiros,1.176703e+08,N
19,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.02.02,Captações no Mercado Aberto,0.000000e+00,S
21,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.02.03,Recursos Mercado Interfinanceiro,0.000000e+00,S
23,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.02.04,Outras Captações,0.000000e+00,S
25,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.03,Provisões,3.703610e+07,S
27,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.04,Passivos Fiscais,2.090383e+07,S
29,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.05,Outros Passivos,3.894724e+07,S
31,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.05.01,Capital Social Realizado,0.000000e+00,N
33,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.05.02,Reservas de Capital,0.000000e+00,N
35,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.05.03,Reservas de Reavaliação,0.000000e+00,N
37,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.05.04,Reservas de Lucro,0.000000e+00,N
39,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.05.05,Ajustes de Avaliação Patrimonial,0.000000e+00,N
41,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.05.06,Lucros/Prejuízos Acumulados,0.000000e+00,N
43,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.06,Passivos sobre Ativos Não Correntes a Venda e ...,0.000000e+00,S
45,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.06.01,Passivos sobre Ativos Não Correntes a Venda,0.000000e+00,S
47,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.06.02,Passivos sobre Ativos de Operações Descontinuadas,0.000000e+00,S
49,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.07,Patrimônio Líquido,1.419766e+08,S
51,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.07.01,Capital Social Realizado,9.000002e+07,S
53,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.07.02,Reservas de Capital,1.402523e+06,S
55,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.07.02.01,Ágio na Emissão de Ações,0.000000e+00,S
57,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.07.02.02,Reserva Especial de Ágio na Incorporação,0.000000e+00,S
59,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.07.02.03,Alienação de Bônus de Subscrição,0.000000e+00,S
61,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.07.02.04,Opções Outorgadas,0.000000e+00,S
63,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.07.02.05,Ações em Tesouraria,0.000000e+00,S
65,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.07.03,Reservas de Reavaliação,0.000000e+00,S
67,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.07.04,Reservas de Lucros,4.871866e+07,S
69,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.07.04.01,Reserva Legal,1.023779e+07,S
71,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.07.04.02,Reserva Estatutária,3.875170e+07,S
73,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.07.04.03,Reserva para Contingências,0.000000e+00,S
75,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.07.04.04,Reserva de Lucros a Realizar,0.000000e+00,S
77,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.07.04.05,Reserva de Retenção de Lucros,0.000000e+00,S
79,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.07.04.06,Reserva Especial para Dividendos Não Distribuídos,0.000000e+00,S
81,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.07.04.07,Reserva de Incentivos Fiscais,0.000000e+00,S
83,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.07.04.08,Dividendo Adicional Proposto,0.000000e+00,S
85,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.07.04.09,Ações em Tesouraria,-2.708400e+05,S
87,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.07.05,Lucros/Prejuízos Acumulados,6.571250e+06,S
89,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.07.06,Ajustes de Avaliação Patrimonial,0.000000e+00,S
91,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.07.07,Ajustes Acumulados de Conversão,0.000000e+00,S
93,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-03-31,2.07.08,Outros Resultados Abrangentes,-4.715894e+06,S
95,00.000.000/0001-91,2022-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-06-30,2,Passivo Total,2.135262e+09,S
97,00.000.000/0001-91,2022-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-06-30,2.01,Passivos Financeiros Avaliados ao Valor Justo ...,3.376697e+06,S
99,00.000.000/0001-91,2022-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-06-30,2.01.01,Instrumentos financeiros derivativos,3.376697e+06,N
101,00.000.000/0001-91,2022-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-06-30,2.02,Passivos Financeiros ao Custo Amortizado,1.884674e+09,S
103,00.000.000/0001-91,2022-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-06-30,2.02.01,Depósitos,1.884674e+09,S
105,00.000.000/0001-91,2022-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-06-30,2.02.01.01,Recursos de instituições financeiras,8.434209e+08,N
107,00.000.000/0001-91,2022-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-06-30,2.02.01.02,Recursos de clientes,6.931486e+08,N
109,00.000.000/0001-91,2022-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-06-30,2.02.01.03,Recursos de emissões de títulos e valores mobi...,2.178404e+08,N
111,00.000.000/0001-91,2022-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-06-30,2.02.01.06,Outros passivos financeiros,1.302644e+08,N
113,00.000.000/0001-91,2022-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-06-30,2.02.02,Captações no Mercado Aberto,0.000000e+00,S
115,00.000.000/0001-91,2022-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-06-30,2.02.03,Recursos Mercado Interfinanceiro,0.000000e+00,S
117,00.000.000/0001-91,2022-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-06-30,2.02.04,Outras Captações,0.000000e+00,S
119,00.000.000/0001-91,2022-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2022-06-30,2.03,Provisões,3.784147e+07,S

In [9]:
lista_ativos = df2['DENOM_CIA'].unique().tolist()
lista_final = []
data_refer = df2['DT_REFER'].unique().tolist()
datas = df2['DT_FIM_EXERC'].unique().tolist()
for ativo in lista_ativos:
    dfativo = df2[df2['DENOM_CIA']==ativo]
    # datas = dfativo['DT_REFER'].unique().tolist() 
    divida_cp = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="2.01.04"')['VL_CONTA'].values
    divida_lp = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="2.02.01"')['VL_CONTA'].values
    pl = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="2.03"')['VL_CONTA'].values

    if len(divida_cp) == 3 and len(divida_lp) == 3 and len(pl) == 3:
        dicio = {
            'ativo': ativo,
            
            f'divida_cp_{DATA_PRINCIPAL[0]}': divida_cp[0],
            f'divida_cp_{DATA_PRINCIPAL[1]}': divida_cp[1],
            f'divida_cp_{DATA_PRINCIPAL[2]}': divida_cp[2],
            
            
            f'divida_lp_{DATA_PRINCIPAL[0]}': divida_lp[0],
            f'divida_lp_{DATA_PRINCIPAL[1]}': divida_lp[1],
            f'divida_lp_{DATA_PRINCIPAL[2]}': divida_lp[2],
        
            
            f'pl_{DATA_PRINCIPAL[0]}': pl[0],
            f'pl_{DATA_PRINCIPAL[1]}': pl[1],
            f'pl_{DATA_PRINCIPAL[2]}': pl[2]
        
        }    
        lista_final.append(dicio)

In [10]:
df_bpp = pd.DataFrame(lista_final)
print(df_bpp.shape)
df_bpp.head()

(686, 10)

,ativo,divida_cp_2022-03-31,divida_cp_2022-06-30,divida_cp_2022-09-30,divida_lp_2022-03-31,divida_lp_2022-06-30,divida_lp_2022-09-30,pl_2022-03-31,pl_2022-06-30,pl_2022-09-30
0,BRB BANCO DE BRASILIA S.A.,0.0,0.0,812248.0,20644210.0,20774270.0,21505123.0,688432.0,687872.0,692086.0
1,AXIA ENERGIA S.A.,5248605.0,3658106.0,3756041.0,17700727.0,17352692.0,16984939.0,78816099.0,106712385.0,111495023.0
2,COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB,0.0,0.0,0.0,0.0,0.0,0.0,868046.0,928570.0,962556.0
3,CARAMURU ALIMENTOS S.A.,2287606.0,3337927.0,2973264.0,1238267.0,1033675.0,1835384.0,1542402.0,1602051.0,1761273.0
4,NEUMARKT TRADE AND FINANCIAL CENTER S/A,0.0,0.0,0.0,73995.0,75901.0,75020.0,-69250.0,-71269.0,-70345.0

## DRE ------------ Fazendo

In [11]:
df3 = pd.read_csv('itr_cia_aberta_DRE_ind_2022.csv', sep=';', encoding='latin-1')
df3=df3[df3['ORDEM_EXERC'] == 'ÚLTIMO']

In [12]:
print(df3.shape)
df3.head(200)

(119289, 15)

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
1,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2022-01-01,2022-03-31,3.01,Receitas de Intermediação Financeira,36426529.00,S
3,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2022-01-01,2022-03-31,3.01.01,Operações de Crédito,18693699.00,N
5,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2022-01-01,2022-03-31,3.01.02,Operações de Arrendamento Mercantil,0.00,N
7,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2022-01-01,2022-03-31,3.01.03,Resultado de Operações com TVM,19321038.00,N
9,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2022-01-01,2022-03-31,3.01.04,Resultado de IFD,-2571731.00,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,00.000.000/0001-91,2022-09-30,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2022-01-01,2022-09-30,3.10.02,Contribuições,0.00,N
393,00.000.000/0001-91,2022-09-30,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2022-07-01,2022-09-30,3.10.02,Contribuições,0.00,N
396,00.000.000/0001-91,2022-09-30,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2022-01-01,2022-09-30,3.11,Lucro ou Prejuízo Líquido do Período,22202021.00,S
397,00.000.000/0001-91,2022-09-30,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2022-07-01,2022-09-30,3.11,Lucro ou Prejuízo Líquido do Período,8043522.00,S
400,00.000.000/0001-91,2022-09-30,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2022-01-01,2022-09-30,3.99,Lucro por Ação (R$/Ação),7.78,N

In [13]:
lista_ativos = df3['DENOM_CIA'].unique().tolist()
lista_final = []
for ativo in lista_ativos:
    dfativo = df3[df3['DENOM_CIA']==ativo]

    # RECEITA LIQUIDA 3.01

    dfativo_3_01 = dfativo[dfativo['CD_CONTA']=='3.01']
    datas_unicas_ini = dfativo_3_01['DT_INI_EXERC'].unique().tolist()
    datas_unicas_fim = dfativo_3_01['DT_FIM_EXERC'].unique().tolist()

    receita_liquida_total = []
    if len(datas_unicas_ini) == 3 and len(datas_unicas_fim) == 3:
        for i in range(len(datas_unicas_ini)):
            data_ini = datas_unicas_ini[i]
            data_fim = datas_unicas_fim[i]
            # print(f'Para o ativo {ativo}, a Data de início é {data_ini} e a data de fim é {data_fim}.')
            receita_liquida = dfativo_3_01.query('DT_INI_EXERC==@data_ini and DT_FIM_EXERC==@data_fim')['VL_CONTA'].values
            receita_liquida_total.extend(receita_liquida)
    
    # EBIT 3.05

    dfativo_3_05 = dfativo[dfativo['CD_CONTA']=='3.05']
    datas_unicas_ini_3_05 = dfativo_3_05['DT_INI_EXERC'].unique().tolist()
    datas_unicas_fim_3_05 = dfativo_3_05['DT_FIM_EXERC'].unique().tolist() 
    ebit_total = []
    if len(datas_unicas_ini_3_05) == 3 and len(datas_unicas_fim_3_05) == 3:
        for i in range(len(datas_unicas_ini_3_05)):
            data_ini = datas_unicas_ini_3_05[i]
            data_fim = datas_unicas_fim_3_05[i]
            # print(f'Para o ativo {ativo}, a Data de início é {data_ini} e a data de fim é {data_fim}.')
            ebit = dfativo_3_05.query('DT_INI_EXERC==@data_ini and DT_FIM_EXERC==@data_fim')['VL_CONTA'].values
            ebit_total.extend(ebit)

    #  LUCRO LIQUIDO 3.11

    dfativo_3_11 = dfativo[dfativo['CD_CONTA']=='3.11']
    datas_unicas_ini_3_11 = dfativo_3_11['DT_INI_EXERC'].unique().tolist()
    datas_unicas_fim_3_11 = dfativo_3_11['DT_FIM_EXERC'].unique().tolist() 
    lucro_liquido_total = []
    if len(datas_unicas_ini_3_11) == 3  and len(datas_unicas_fim_3_11) == 3:
        for i in range(len(datas_unicas_ini_3_11)):
            data_ini = datas_unicas_ini_3_11[i]
            data_fim = datas_unicas_fim_3_11[i]
            # print(f'Para o ativo {ativo}, a Data de início é {data_ini} e a data de fim é {data_fim}.')
            lucro_liquido = dfativo_3_11.query('DT_INI_EXERC==@data_ini and DT_FIM_EXERC==@data_fim')['VL_CONTA'].values
            lucro_liquido_total.extend(lucro_liquido)

    # print(f'Ativo: {ativo}')
    # print(f'Receita Líquida: {receita_liquida_total}')
    # print(f'EBIT: {ebit_total}')
    # print(f'Lucro Líquido: {lucro_liquido_total}')
    # print('-----------------------------')

    # PIETROSKI F_SCORE
    # ROA = lucro_liquido_total / ativo_total  3.11 / 1 
    # Margem liq = lucro_liquido_total / receita_liquida_total 3.11 / 3.01
    # Giro do ativo = receita_liquida_total / ativo_total 3.01 / 1
    # Alavancagem financeira = divida_total(bruta) / ativo total  (2.01.04 + 2.02.01) / 2.03


    # 3 é DRE, vamo buscar
    #ll ja tenho e ativo total tb, entao ROA ok
    # Margem liq tb ja tenho, so fazer conta
    #giro do ativo tb ja tenho, so fazer conta

    if len(receita_liquida_total) == 3 and len(ebit_total) == 3 and len(lucro_liquido_total) == 3:  
        dicio ={
            'ativo': ativo,
            f'receita_liquida_{DATA_PRINCIPAL[0]}': receita_liquida_total[0],
            f'receita_liquida_{DATA_PRINCIPAL[1]}': receita_liquida_total[1],
            f'receita_liquida_{DATA_PRINCIPAL[2]}': receita_liquida_total[2],

            f'ebit_{DATA_PRINCIPAL[0]}': ebit_total[0],
            f'ebit_{DATA_PRINCIPAL[1]}': ebit_total[1],
            f'ebit_{DATA_PRINCIPAL[2]}': ebit_total[2],

            f'lucro_liquido_{DATA_PRINCIPAL[0]}': lucro_liquido_total[0],
            f'lucro_liquido_{DATA_PRINCIPAL[1]}': lucro_liquido_total[1],
            f'lucro_liquido_{DATA_PRINCIPAL[2]}': lucro_liquido_total[2]
        }
        lista_final.append(dicio)

In [14]:
df_dre = pd.DataFrame(lista_final)
print(df_dre.shape)
df_dre.head()

(708, 10)

,ativo,receita_liquida_2022-03-31,receita_liquida_2022-06-30,receita_liquida_2022-09-30,ebit_2022-03-31,ebit_2022-06-30,ebit_2022-09-30,lucro_liquido_2022-03-31,lucro_liquido_2022-06-30,lucro_liquido_2022-09-30
0,BCO BRASIL S.A.,36426529.0,65059522.0,68170786.0,7870570.0,9930748.0,10729971.0,6570637.0,7587862.0,8043522.0
1,BRB BANCO DE BRASILIA S.A.,1201489.0,1409802.0,1463322.0,85199.0,147202.0,70606.0,70666.0,121626.0,59273.0
2,AXIA ENERGIA S.A.,19206.0,82208.0,37793.0,1951613.0,1323755.0,324616.0,2708342.0,1397541.0,-14533.0
3,COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB,15753.0,13093.0,15267.0,27988.0,50151.0,30043.0,39044.0,60524.0,35601.0
4,CARAMURU ALIMENTOS S.A.,1807770.0,2332349.0,2385802.0,-263241.0,323224.0,262763.0,27659.0,59648.0,159222.0

In [15]:
print(df_bpa.info())
print(df_bpp.info())
print(df_dre.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 702 entries, 0 to 701
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ativo                   702 non-null    object
 1   caixa_2022-03-31        702 non-null    float64
 2   caixa_2022-06-30        702 non-null    float64
 3   caixa_2022-09-30        702 non-null    float64
 4   ativo_total_2022-03-31  702 non-null    float64
 5   ativo_total_2022-06-30  702 non-null    float64
 6   ativo_total_2022-09-30  702 non-null    float64
dtypes: float64(6), object(1)
memory usage: 38.5+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 686 entries, 0 to 685
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ativo                 686 non-null    object
 1   divida_cp_2022-03-31  686 non-null    float64
 2   divida_cp_2022-06-30  686 non-null    float64
 3   divida_cp_2022-09-30  686 non-null    float64
 4   divida_lp_2022-03-31  686 non-null    float64
 5   divida_lp_2022-06-30  686 non-null    float64
 6   divida_lp_2022-09-30  686 non-null    float64
 7   pl_2022-03-31         686 non-null    float64
 8   pl_2022-06-30         686 non-null    float64
 9   pl_2022-09-30         686 non-null    float64
dtypes: float64(9), object(1)
memory usage: 53.7+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 708 entries, 0 to 707
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ativo                       708 non-null    object
 1   receita_liquida_2022-03-31  708 non-null    float64
 2   receita_liquida_2022-06-30  708 non-null    float64
 3   receita_liquida_2022-09-30  708 non-null    float64
 4   ebit_2022-03-31             708 non-null    float64
 5   ebit_2022-06-30             708 non-null    float64
 6   ebit_2022-09-30             708 non-null    float64
 7   lucro_liquido_2022-03-31    708 non-null    float64
 8   lucro_liquido_2022-06-30    708 non-null    float64
 9   lucro_liquido_2022-09-30    708 non-null    float64
dtypes: float64(9), object(1)
memory usage: 55.4+ KB
None

In [16]:
df_final = df_bpa.merge(df_bpp, on="ativo", how="inner") \
           .merge(df_dre, on="ativo", how="inner")

print(df_bpa.shape)
print(df_bpp.shape)
print(df_dre.shape)
print('----')
print(df_final.shape)

(702, 7)
(686, 10)
(708, 10)
----
(685, 25)

In [17]:
df_final.to_excel('resultado/dados_final_2022.xlsx', index=False)

## ------ FIMM DA RASPAGEM

## _____________________________

## -------- INICIO DAS FORMULAS (MAGIC FORMULA E PIOTROSKI)

In [18]:
print(df_final.shape)
df_final.head()

(685, 25)

,ativo,caixa_2022-03-31,caixa_2022-06-30,caixa_2022-09-30,ativo_total_2022-03-31,ativo_total_2022-06-30,ativo_total_2022-09-30,divida_cp_2022-03-31,divida_cp_2022-06-30,divida_cp_2022-09-30,...,pl_2022-09-30,receita_liquida_2022-03-31,receita_liquida_2022-06-30,receita_liquida_2022-09-30,ebit_2022-03-31,ebit_2022-06-30,ebit_2022-09-30,lucro_liquido_2022-03-31,lucro_liquido_2022-06-30,lucro_liquido_2022-09-30
0,BRB BANCO DE BRASILIA S.A.,195388.0,270516.0,243682.0,37424710.0,37444935.0,38922484.0,0.0,0.0,812248.0,...,692086.0,1201489.0,1409802.0,1463322.0,85199.0,147202.0,70606.0,70666.0,121626.0,59273.0
1,AXIA ENERGIA S.A.,3280706.0,2901153.0,4283537.0,139117167.0,163944580.0,166380211.0,5248605.0,3658106.0,3756041.0,...,111495023.0,19206.0,82208.0,37793.0,1951613.0,1323755.0,324616.0,2708342.0,1397541.0,-14533.0
2,COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB,491688.0,241439.0,256513.0,1178707.0,972456.0,1001220.0,0.0,0.0,0.0,...,962556.0,15753.0,13093.0,15267.0,27988.0,50151.0,30043.0,39044.0,60524.0,35601.0
3,CARAMURU ALIMENTOS S.A.,464400.0,570105.0,2064042.0,7941590.0,8783483.0,9440657.0,2287606.0,3337927.0,2973264.0,...,1761273.0,1807770.0,2332349.0,2385802.0,-263241.0,323224.0,262763.0,27659.0,59648.0,159222.0
4,NEUMARKT TRADE AND FINANCIAL CENTER S/A,17.0,2.0,9.0,22461.0,21681.0,21667.0,0.0,0.0,0.0,...,-70345.0,125.0,118.0,140.0,45.0,-247.0,57.0,-3800.0,-2019.0,924.0

## ------------

In [19]:
import pandas as pd
import numpy as np
import yfinance as yf

def normalizar_cnpj(cnpj):
    if pd.isna(cnpj):
        return None
    return str(cnpj).replace('.','').replace('-','').replace('/','').strip().zfill(14)

# ================================================================
# CONFIGURAÇÃO
# ================================================================

DATAS = DATA_PRINCIPAL

TICKERS_IBOV = [
    "VALE3", "ITUB4", "PETR4", "PETR3", "AXIA3", "BBDC4", "SBSP3", "B3SA3",
    "ITSA4", "BPAC11", "WEGE3", "BBAS3", "EMBJ3", "ABEV3", "EQTL3", "RENT3",
    "RDOR3", "ENEV3", "PRIO3", "VBBR3", "SUZB3", "RADL3", "AXIA7", "VIVT3",
    "UGPA3", "BBDC3", "GGBR4", "CPLE3", "CMIG4", "TIMS3", "TOTS3", "BBSE3",
    "RAIL3", "ENGI11", "AXIA6", "MOTV3", "KLBN11", "LREN3", "ALOS3", "MBRF3",
    "SANB11", "ASAI3", "EGIE3", "ISAE4", "CSAN3", "CSMG3", "MULT3", "CXSE3",
    "SMFT3", "TAEE11", "PSSA3", "CPFE3", "CMIN3", "BRAV3", "CYRE3", "GOAU4",
    "FLRY3", "NATU3", "HYPE3", "COGN3", "CURY3", "CSNA3", "IGTI11", "BRAP4",
    "DIRR3", "IRBR3", "POMO4", "MGLU3", "MRVE3", "VIVA3", "AURE3", "SLCE3",
    "YDUQ3", "AZZA3", "RECV3", "USIM5", "HAPV3", "CEAB3", "BRKM5", "BEEF3",
    "RENT4", "VAMO3", "CYRE4", "PCAR3", "RAIZ4",
]

# ================================================================
# 1) CARREGA dados_final_2025.xlsx e transforma em formato longo
# ================================================================

# df_wide = pd.read_excel('resultado/dados_final_2024.xlsx')
df_wide = df_final
print(f"Empresas no arquivo: {len(df_wide)}")

# Transforma de wide para long (uma linha por empresa por data)
rows = []
for _, row in df_wide.iterrows():
    for data in DATAS:
        rows.append({
            'ativo':         row['ativo'],
            'dt_refer':      data,
            'caixa':         row[f'caixa_{data}'],
            'ativo_total':   row[f'ativo_total_{data}'],
            'divida_cp':     row[f'divida_cp_{data}'],
            'divida_lp':     row[f'divida_lp_{data}'],
            'pl':            row[f'pl_{data}'],
            'receita':       row[f'receita_liquida_{data}'],
            'ebit':          row[f'ebit_{data}'],
            'lucro':         row[f'lucro_liquido_{data}'],
        })

df = pd.DataFrame(rows)
print(f"Total linhas (empresa × data): {len(df)}")

# ================================================================
# 2) MAPEIA ticker → nome da empresa
# ================================================================

# Carrega mapeamento B3
df_mapa = pd.read_excel('../mapeamento_ticker.xlsx')

def empresa_tem_ticker(todos_tickers: str, ticker: str) -> bool:
    if pd.isna(todos_tickers):
        return False
    return ticker in [t.strip() for t in str(todos_tickers).split(',')]

# Para cada ticker do Ibovespa, busca o nome da empresa
ticker_para_nome = {}
for ticker in TICKERS_IBOV:
    match = df_mapa[df_mapa['todos_tickers'].apply(
        lambda x: empresa_tem_ticker(x, ticker)
    )]
    if not match.empty:
        ticker_para_nome[ticker] = match.iloc[0]['nome']

print(f"\nTickers mapeados: {len(ticker_para_nome)}/{len(TICKERS_IBOV)}")

# Inverte: nome → ticker
nome_para_ticker = {v: k for k, v in ticker_para_nome.items()}

# ================================================================
# 3) CRUZA nome do ITR com nome do mapeamento B3
# ================================================================

# Carrega CNPJ do ITR
df_itr = pd.read_csv('itr_cia_aberta_BPP_ind_2022.csv', sep=';', encoding='latin1')
cnpj_empresa = df_itr[['CNPJ_CIA','DENOM_CIA']].drop_duplicates()
cnpj_empresa.columns = ['cnpj','nome_itr']
cnpj_empresa['cnpj_norm'] = cnpj_empresa['cnpj'].apply(normalizar_cnpj)

# CNPJ do mapeamento B3
df_mapa['cnpj_norm'] = df_mapa['cnpj'].apply(normalizar_cnpj)
cnpj_b3 = df_mapa[['cnpj_norm','nome']].drop_duplicates()
cnpj_b3.columns = ['cnpj_norm','nome_b3']

# Cruza: cnpj → nome_itr + nome_b3
mapa_completo = cnpj_empresa.merge(cnpj_b3, on='cnpj_norm', how='inner')

# Para cada nome_b3 do Ibovespa, pega o nome_itr correspondente
ibov_nomes = {}
for ticker in TICKERS_IBOV:
    if ticker in ticker_para_nome:
        nome_b3 = ticker_para_nome[ticker]
        match = mapa_completo[mapa_completo['nome_b3'] == nome_b3]
        if not match.empty:
            ibov_nomes[ticker] = match.iloc[0]['nome_itr']

print(f"Empresas encontradas no ITR: {len(ibov_nomes)}/{len(TICKERS_IBOV)}")

# ================================================================
# 4) FILTRA df só para empresas do Ibovespa
# ================================================================

nomes_itr_ibov = list(ibov_nomes.values())
df = df[df['ativo'].isin(nomes_itr_ibov)].copy()
print(f"\nLinhas após filtro Ibovespa: {len(df)}")
print(f"Empresas únicas: {df['ativo'].nunique()}")

# Adiciona ticker
nome_itr_para_ticker = {v: k for k, v in ibov_nomes.items()}
df['ticker'] = df['ativo'].map(nome_itr_para_ticker)

# ================================================================
# 5) CALCULA indicadores
# ================================================================

df['divida_bruta']   = df['divida_cp'] + df['divida_lp']
df['divida_liquida'] = df['divida_bruta'] - df['caixa']
df['cap_investido']  = df['pl'] + df['divida_liquida']

df['ROIC']        = df['ebit'] / df['cap_investido']
df['ROE']         = df['lucro'] / df['pl']
df['margem_liq']  = df['lucro'] / df['receita']
df['div_ebitda']  = df['divida_bruta'] / df['ebit']  # proxy EBITDA≈EBIT
df['ROA']         = df['lucro'] / df['ativo_total']

df['giro_ativo'] = df['receita'] / df['ativo_total']
df['alavancagem'] = df['divida_bruta'] / df['ativo_total']

# Remove cap_investido negativo
df = df[df['cap_investido'] > 0].reset_index(drop=True)

print(f"\nApós remover cap_investido ≤ 0: {len(df)} linhas")

# ================================================================
# 6) BUSCA preço histórico
# ================================================================

def get_preco(ticker: str, dt_refer: str):
    try:
        data_fim = pd.Timestamp(dt_refer)
        data_ini = data_fim - pd.Timedelta(days=7)
        hist = yf.download(
            ticker + ".SA",
            start=data_ini,
            end=data_fim + pd.Timedelta(days=1),
            progress=False,
            auto_adjust=True
        )
        if hist.empty:
            return None
        return float(hist["Close"].iloc[-1])
    except Exception:
        return None

combos = df[['ticker','dt_refer']].drop_duplicates()
print(f"\nBuscando preços para {len(combos)} combinações ticker+data...")

precos = {}
for i, row in combos.iterrows():
    key = (row['ticker'], row['dt_refer'])
    precos[key] = get_preco(row['ticker'], row['dt_refer'])
    if (i+1) % 20 == 0:
        print(f"  {i+1}/{len(combos)}...")

df['preco'] = df.apply(lambda r: precos.get((r['ticker'], r['dt_refer'])), axis=1)
print(f"Com preço: {df['preco'].notna().sum()}/{len(df)}")

# ================================================================
# 7) BUSCA número de ações
# ================================================================

df_cap = pd.read_csv(
    'itr_cia_aberta_composicao_capital_2022.csv',
    sep=';', encoding='latin1', dtype={'CNPJ_CIA': str}
)
df_cap['cnpj_norm']  = df_cap['CNPJ_CIA'].apply(normalizar_cnpj)
df_cap['acoes_circ'] = df_cap['QT_ACAO_TOTAL_CAP_INTEGR'] - df_cap['QT_ACAO_TOTAL_TESOURO']
df_cap['dt_refer']   = pd.to_datetime(df_cap['DT_REFER'], dayfirst=True).dt.strftime('%Y-%m-%d')
df_cap = df_cap.sort_values('VERSAO', ascending=False).drop_duplicates(subset=['cnpj_norm','dt_refer'])
df_cap = df_cap[['cnpj_norm','dt_refer','acoes_circ']]

# Adiciona cnpj_norm no df
df = df.merge(
    cnpj_empresa[['nome_itr','cnpj_norm']].rename(columns={'nome_itr':'ativo'}),
    on='ativo',
    how='left'
)

# Junta ações
df = df.merge(df_cap, on=['cnpj_norm','dt_refer'], how='left')
print(f"Com ações: {df['acoes_circ'].notna().sum()}/{len(df)}")

# ================================================================
# 8) CALCULA EV e Earnings Yield
# ================================================================

df['valor_mercado']   = df['preco'] * df['acoes_circ']
df['EV']              = df['valor_mercado'] + df['cap_investido'] - df['pl']
df['earnings_yield']  = df['ebit'] / df['EV']

# ================================================================
# RESULTADO FINAL
# ================================================================

df_final = df[[
    'ativo', 'ticker', 'dt_refer', 
    'preco', 'acoes_circ', 'valor_mercado',
    'ebit', 'cap_investido', 'pl', 'EV',
    'ROIC', 'earnings_yield', 'ROE', 'margem_liq', 'div_ebitda', 'ROA', 'giro_ativo', 'alavancagem'
]].copy()

print("\n" + "="*70)
print("RESULTADO FINAL")
print("="*70)
print(f"Total linhas:  {len(df_final)}")
print(f"Empresas:      {df_final['ativo'].nunique()}")
print(f"Tickers:       {df_final['ticker'].nunique()}")
print(f"Com EV:        {df_final['EV'].notna().sum()}")
print(f"Com EY:        {df_final['earnings_yield'].notna().sum()}")
print()
print(df_final.head(12).to_string(index=False))
print()

# Salva
df_final.to_excel('ibovespa_magic_formula_2022.xlsx', index=False)
print("Salvo: ibovespa_magic_formula_2022.xlsx")

Empresas no arquivo: 685
Total linhas (empresa × data): 2055

Tickers mapeados: 83/85
Empresas encontradas no ITR: 78/85

Linhas após filtro Ibovespa: 210
Empresas únicas: 70

Após remover cap_investido ≤ 0: 204 linhas

Buscando preços para 204 combinações ticker+data...

C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  20/204...

C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
$MOTV3.SA: possibly delisted; no price data found  (1d 2022-03-24 00:00:00 -> 2022-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1648090800, endDate = 1648782000")

1 Failed download:
['MOTV3.SA']: possibly delisted; no price data found  (1d 2022-03-24 00:00:00 -> 2022-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1648090800, endDate = 1648782000")
$MOTV3.SA: possibly delisted; no price data found  (1d 2022-06-23 00:00:00 -> 2022-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1655953200, endDate = 1656644400")

1 Failed download:
['MOTV3.SA']: possibly delisted; no price data found  (1d 2022-06-23 00:00:00 -> 2022-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1655953200, endDate = 1656644400")
$MOTV3.SA: possibly delisted; no price data found  (1d 2022-09-23 00:00:00 -> 2022-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1663902000, endDate = 1664593200")

1 Failed download:
['MOTV3.SA']: possibly delisted; no price data found  (1d 2022-09-23 00:00:00 -> 2022-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1663902000, endDate = 1664593200")
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  40/204...

C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  60/204...

C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
$EMBJ3.SA: possibly delisted; no price data found  (1d 2022-03-24 00:00:00 -> 2022-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1648090800, endDate = 1648782000")

1 Failed download:
['EMBJ3.SA']: possibly delisted; no price data found  (1d 2022-03-24 00:00:00 -> 2022-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1648090800, endDate = 1648782000")
$EMBJ3.SA: possibly delisted; no price data found  (1d 2022-06-23 00:00:00 -> 2022-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1655953200, endDate = 1656644400")

1 Failed download:
['EMBJ3.SA']: possibly delisted; no price data found  (1d 2022-06-23 00:00:00 -> 2022-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1655953200, endDate = 1656644400")
$EMBJ3.SA: possibly delisted; no price data found  (1d 2022-09-23 00:00:00 -> 2022-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1663902000, endDate = 1664593200")

1 Failed download:
['EMBJ3.SA']: possibly delisted; no price data found  (1d 2022-09-23 00:00:00 -> 2022-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1663902000, endDate = 1664593200")
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  80/204...

C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
$RENT4.SA: possibly delisted; no price data found  (1d 2022-03-24 00:00:00 -> 2022-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1648090800, endDate = 1648782000")

1 Failed download:
['RENT4.SA']: possibly delisted; no price data found  (1d 2022-03-24 00:00:00 -> 2022-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1648090800, endDate = 1648782000")

  100/204...

$RENT4.SA: possibly delisted; no price data found  (1d 2022-06-23 00:00:00 -> 2022-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1655953200, endDate = 1656644400")

1 Failed download:
['RENT4.SA']: possibly delisted; no price data found  (1d 2022-06-23 00:00:00 -> 2022-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1655953200, endDate = 1656644400")
$RENT4.SA: possibly delisted; no price data found  (1d 2022-09-23 00:00:00 -> 2022-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1663902000, endDate = 1664593200")

1 Failed download:
['RENT4.SA']: possibly delisted; no price data found  (1d 2022-09-23 00:00:00 -> 2022-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1663902000, endDate = 1664593200")
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  120/204...

C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  140/204...

C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  160/204...

C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
$NATU3.SA: possibly delisted; no price data found  (1d 2022-03-24 00:00:00 -> 2022-04-01 00:00:00)

1 Failed download:
['NATU3.SA']: possibly delisted; no price data found  (1d 2022-03-24 00:00:00 -> 2022-04-01 00:00:00)
$NATU3.SA: possibly delisted; no price data found  (1d 2022-06-23 00:00:00 -> 2022-07-01 00:00:00)

1 Failed download:
['NATU3.SA']: possibly delisted; no price data found  (1d 2022-06-23 00:00:00 -> 2022-07-01 00:00:00)
$NATU3.SA: possibly delisted; no price data found  (1d 2022-09-23 00:00:00 -> 2022-10-01 00:00:00)

1 Failed download:
['NATU3.SA']: possibly delisted; no price data found  (1d 2022-09-23 00:00:00 -> 2022-10-01 00:00:00)
$CYRE4.SA: possibly delisted; no price data found  (1d 2022-03-24 00:00:00 -> 2022-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1648090800, endDate = 1648782000")

1 Failed download:
['CYRE4.SA']: possibly delisted; no price data found  (1d 2022-03-24 00:00:00 -> 2022-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1648090800, endDate = 1648782000")
$CYRE4.SA: possibly delisted; no price data found  (1d 2022-06-23 00:00:00 -> 2022-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1655953200, endDate = 1656644400")

1 Failed download:
['CYRE4.SA']: possibly delisted; no price data found  (1d 2022-06-23 00:00:00 -> 2022-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1655953200, endDate = 1656644400")
$CYRE4.SA: possibly delisted; no price data found  (1d 2022-09-23 00:00:00 -> 2022-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1663902000, endDate = 1664593200")

1 Failed download:
['CYRE4.SA']: possibly delisted; no price data found  (1d 2022-09-23 00:00:00 -> 2022-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1663902000, endDate = 1664593200")

  180/204...

C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  200/204...

C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

Com preço: 189/204
Com ações: 204/204

======================================================================
RESULTADO FINAL
======================================================================
Total linhas:  204
Empresas:      68
Tickers:       68
Com EV:        189
Com EY:        189

            ativo ticker   dt_refer     preco  acoes_circ  valor_mercado      ebit  cap_investido          pl           EV     ROIC  earnings_yield       ROE  margem_liq  div_ebitda       ROA  giro_ativo  alavancagem
AXIA ENERGIA S.A.  AXIA6 2022-03-31 21.696053     1568931   3.403961e+07 1951613.0     98484725.0  78816099.0 5.370824e+07 0.019816        0.036337  0.034363  141.015412   11.759161  0.019468    0.000138     0.164964
AXIA ENERGIA S.A.  AXIA6 2022-06-30 28.447393     2196606   6.248772e+07 1323755.0    124822030.0 106712385.0 8.059736e+07 0.010605        0.016424  0.013096   17.000061   15.872120  0.008524    0.000501     0.128158
AXIA ENERGIA S.A.  AXIA6 2022-09-30 27.503204     2301228   6.329114e+07  324616.0    127952466.0 111495023.0 7.974859e+07 0.002537        0.004070 -0.000130   -0.384542   63.893893 -0.000087    0.000227     0.124660
    ENERGISA S.A. ENGI11 2022-03-31 36.976318  1810023555   6.692801e+10  719195.0     15097660.0   8915062.0 6.693419e+10 0.047636        0.000011  0.056777    8.561449    8.629324  0.028584    0.003339     0.350475
    ENERGISA S.A. ENGI11 2022-06-30 30.567390  1810870365   5.535358e+10  570868.0     16491511.0   9788823.0 5.536028e+10 0.034616        0.000010  0.093563   11.585104   11.789132  0.050034    0.004319     0.367662
    ENERGISA S.A. ENGI11 2022-09-30 32.555531  2039086540   6.638354e+10  696712.0     17925627.0  11665088.0 6.638980e+10 0.038867        0.000010  0.034472    5.028486    9.013314  0.021362    0.004248     0.333601
PORTO SEGURO S.A.  PSSA3 2022-03-31 16.889568      637851   1.077303e+07  134525.0      9196484.0   9296642.0 1.067287e+07 0.014628        0.012604  0.018835         inf    0.000000  0.017005    0.000000     0.000000
PORTO SEGURO S.A.  PSSA3 2022-06-30 14.517057      637851   9.259720e+06  174951.0      9347239.0   9409948.0 9.197011e+06 0.018717        0.019023  0.013963         inf    0.000000  0.012238    0.000000     0.000000
PORTO SEGURO S.A.  PSSA3 2022-09-30 17.772505      638023   1.133927e+07  220035.0      9839089.0   9953773.0 1.122458e+07 0.022363        0.019603  0.027400         inf    0.000000  0.023169    0.000000     0.000000
        RUMO S.A.  RAIL3 2022-03-31 17.494497  1851835864   3.239694e+10   73579.0     19247569.0  14706055.0 3.240148e+10 0.003823        0.000002 -0.004531   -0.350922   71.722992 -0.002925    0.008336     0.231681
        RUMO S.A.  RAIL3 2022-06-30 15.077779  1851965935   2.792353e+10  187679.0     18989925.0  14745863.0 2.792778e+10 0.009883        0.000007  0.002299    0.155967   27.939674  0.001478    0.009475     0.228594
        RUMO S.A.  RAIL3 2022-09-30 17.447546  1852355735   3.231906e+10  406098.0     19218874.0  15061025.0 3.232322e+10 0.021130        0.000013  0.020365    0.938416   13.000195  0.013146    0.014008     0.226266

Salvo: ibovespa_magic_formula_2022.xlsx

C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:165: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_14848\3968863164.py:192: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df_cap['dt_refer']   = pd.to_datetime(df_cap['DT_REFER'], dayfirst=True).dt.strftime('%Y-%m-%d')

Como a Magic Formula Original Funciona

Rankeia todas as ações pelo Earnings Yield (maior → melhor → ranking 1, 2, 3...)
Rankeia todas as ações pelo ROIC (maior → melhor → ranking 1, 2, 3...)
Soma os rankings (não os valores)
Seleciona as top 20-30 com menor ranking combinado