In [2]:
import pandas as pd

In [22]:
DATA_PRINCIPAL = ['2024-03-31', '2024-06-30', '2024-09-30']

## BPA --------- FEITO

In [3]:
df = pd.read_csv('BPA_2024.csv', sep=';', encoding='latin-1')
df=df[df['ORDEM_EXERC'] == 'ÚLTIMO']

In [4]:
df

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
1,00.000.000/0001-91,2024-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2024-03-31,1,Ativo Total,2.325630e+09,S
3,00.000.000/0001-91,2024-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2024-03-31,1.01,Caixa e Equivalentes de Caixa,8.231791e+07,S
5,00.000.000/0001-91,2024-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2024-03-31,1.01.01,Caixa,2.113006e+07,S
7,00.000.000/0001-91,2024-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2024-03-31,1.01.02,Aplicações de Liquidez,6.118785e+07,S
9,00.000.000/0001-91,2024-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2024-03-31,1.02,Ativos Financeiros,2.084500e+09,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288981,97.837.181/0001-47,2024-09-30,1,DEXCO S.A.,21091,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2024-09-30,1.02.04.01.04,Goodwill na Aquisição da Satipel em 2009,4.550300e+04,N
288983,97.837.181/0001-47,2024-09-30,1,DEXCO S.A.,21091,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2024-09-30,1.02.04.01.07,Goodwill de Empresa Incorporada em 2012,2.402000e+03,N
288985,97.837.181/0001-47,2024-09-30,1,DEXCO S.A.,21091,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2024-09-30,1.02.04.01.08,Goodwill - Cerâmica Urussanga,9.294400e+04,N
288987,97.837.181/0001-47,2024-09-30,1,DEXCO S.A.,21091,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2024-09-30,1.02.04.01.09,Goodwill - Massima Revestimentos Cerâmicos,6.110000e+03,N
288989,97.837.181/0001-47,2024-09-30,1,DEXCO S.A.,21091,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2024-09-30,1.02.04.01.10,Goodwill - Cecrisa Revestimentos Cerâmicos,1.684300e+05,N

In [5]:
df['DT_REFER'].unique().tolist()

['2024-03-31',
 '2024-06-30',
 '2024-09-30',
 '2024-12-31',
 '2024-05-31',
 '2024-08-31',
 '2024-11-30']

In [ ]:
lista_ativos = df['DENOM_CIA'].unique().tolist()
lista_final = []
data_refer = df['DT_REFER'].unique().tolist()
datas = df['DT_FIM_EXERC'].unique().tolist()
for ativo in lista_ativos:
    dfativo = df[df['DENOM_CIA']==ativo]
    
    caixa = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="1.01.01"')['VL_CONTA'].values
    ativo_total = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="1"')['VL_CONTA'].values
    

    if len(caixa) == 3 and len(ativo_total) == 3:
        dicio = {
            'ativo': ativo,
            
            f'caixa_{DATA_PRINCIPAL[0]}': caixa[0],
            f'caixa_{DATA_PRINCIPAL[1]}': caixa[1],
            f'caixa_{DATA_PRINCIPAL[2]}': caixa[2],
            
           

            f'ativo_total_{DATA_PRINCIPAL[0]}': ativo_total[0],
            f'ativo_total_{DATA_PRINCIPAL[1]}': ativo_total[1],
            f'ativo_total_{DATA_PRINCIPAL[2]}': ativo_total[2],
            

        
        }    
        lista_final.append(dicio)

In [24]:
df_bpa = pd.DataFrame(lista_final)
print(df_bpa.shape)
df_bpa.head()

(681, 7)

,ativo,caixa_2024-03-31,caixa_2024-06-30,caixa_2024-09-30,ativo_total_2024-03-31,ativo_total_2024-06-30,ativo_total_2024-09-30
0,BCO BRASIL S.A.,21130064.0,23608734.0,21137725.0,2.325630e+09,2.342403e+09,2.436861e+09
1,BRB BANCO DE BRASILIA S.A.,198509.0,206874.0,184914.0,4.895694e+07,5.296828e+07,5.545411e+07
2,AXIA ENERGIA S.A.,5599108.0,9268560.0,12297511.0,1.709004e+08,1.762083e+08,2.081541e+08
3,COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB,284631.0,311733.0,319477.0,1.108991e+06,1.065032e+06,1.095824e+06
4,CARAMURU ALIMENTOS S.A.,1242166.0,1027423.0,749284.0,6.650273e+06,6.763556e+06,6.066497e+06

## BPP ------------ Fazendo

In [25]:
df2 = pd.read_csv('BPP_2024.csv', sep=';', encoding='latin-1')
df2=df2[df2['ORDEM_EXERC'] == 'ÚLTIMO']
df2.head()

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
1,00.000.000/0001-91,2024-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2024-03-31,2,Passivo Total,2.325630e+09,S
3,00.000.000/0001-91,2024-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2024-03-31,2.01,Passivos Financeiros Avaliados ao Valor Justo ...,4.254728e+06,S
5,00.000.000/0001-91,2024-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2024-03-31,2.01.01,Instrumentos financeiros derivativos,4.254728e+06,N
7,00.000.000/0001-91,2024-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2024-03-31,2.02,Passivos Financeiros ao Custo Amortizado,2.078449e+09,S
9,00.000.000/0001-91,2024-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2024-03-31,2.02.01,Depósitos,2.078449e+09,S

In [26]:
lista_ativos = df2['DENOM_CIA'].unique().tolist()
lista_final = []
data_refer = df2['DT_REFER'].unique().tolist()
datas = df2['DT_FIM_EXERC'].unique().tolist()
for ativo in lista_ativos:
    dfativo = df2[df2['DENOM_CIA']==ativo]
    # datas = dfativo['DT_REFER'].unique().tolist() 
    divida_cp = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="2.01.04"')['VL_CONTA'].values
    divida_lp = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="2.02.01"')['VL_CONTA'].values
    pl = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="2.03"')['VL_CONTA'].values

    if len(divida_cp) == 3 and len(divida_lp) == 3 and len(pl) == 3:
        dicio = {
            'ativo': ativo,
            
            f'divida_cp_{DATA_PRINCIPAL[0]}': divida_cp[0],
            f'divida_cp_{DATA_PRINCIPAL[1]}': divida_cp[1],
            f'divida_cp_{DATA_PRINCIPAL[2]}': divida_cp[2],
            
            
            f'divida_lp_{DATA_PRINCIPAL[0]}': divida_lp[0],
            f'divida_lp_{DATA_PRINCIPAL[1]}': divida_lp[1],
            f'divida_lp_{DATA_PRINCIPAL[2]}': divida_lp[2],
        
            
            f'pl_{DATA_PRINCIPAL[0]}': pl[0],
            f'pl_{DATA_PRINCIPAL[1]}': pl[1],
            f'pl_{DATA_PRINCIPAL[2]}': pl[2]
        
        }    
        lista_final.append(dicio)

In [28]:
df_bpp = pd.DataFrame(lista_final)
print(df_bpp.shape)
df_bpp.head()

(669, 10)

,ativo,divida_cp_2024-03-31,divida_cp_2024-06-30,divida_cp_2024-09-30,divida_lp_2024-03-31,divida_lp_2024-06-30,divida_lp_2024-09-30,pl_2024-03-31,pl_2024-06-30,pl_2024-09-30
0,BRB BANCO DE BRASILIA S.A.,0.0,0.0,0.0,28607860.0,30525185.0,31316305.0,750432.0,753455.0,761042.0
1,AXIA ENERGIA S.A.,10206870.0,6967314.0,10321523.0,25439297.0,34397520.0,37803729.0,112582272.0,114094326.0,121252094.0
2,COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB,0.0,0.0,0.0,0.0,0.0,0.0,1051844.0,1027527.0,1075355.0
3,CARAMURU ALIMENTOS S.A.,1019117.0,1093432.0,1229257.0,2028514.0,2023778.0,1473802.0,1957068.0,2057339.0,2116102.0
4,AUREN OPERAÇÕES S.A.,1154348.0,1045225.0,1018927.0,3966426.0,4593918.0,4589638.0,2886408.0,2844324.0,2626967.0

## DRE ------------ Fazendo

In [29]:
df3 = pd.read_csv('DRE_2024.csv', sep=';', encoding='latin-1')
df3=df3[df3['ORDEM_EXERC'] == 'ÚLTIMO']

In [30]:
print(df3.shape)
df3.head(200)

(118620, 15)

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
1,00.000.000/0001-91,2024-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2024-01-01,2024-03-31,3.01,Receitas de Intermediação Financeira,64576794.00,S
3,00.000.000/0001-91,2024-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2024-01-01,2024-03-31,3.01.01,Operações de Crédito,36088218.00,N
5,00.000.000/0001-91,2024-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2024-01-01,2024-03-31,3.01.02,Operações de Arrendamento Mercantil,0.00,N
7,00.000.000/0001-91,2024-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2024-01-01,2024-03-31,3.01.03,Resultado de Operações com TVM,26051060.00,N
9,00.000.000/0001-91,2024-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2024-01-01,2024-03-31,3.01.04,Resultado de IFD,1155119.00,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,00.000.000/0001-91,2024-09-30,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2024-01-01,2024-09-30,3.10.02,Contribuições,0.00,N
393,00.000.000/0001-91,2024-09-30,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2024-07-01,2024-09-30,3.10.02,Contribuições,0.00,N
396,00.000.000/0001-91,2024-09-30,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2024-01-01,2024-09-30,3.11,Lucro ou Prejuízo Líquido do Período,26571881.00,S
397,00.000.000/0001-91,2024-09-30,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2024-07-01,2024-09-30,3.11,Lucro ou Prejuízo Líquido do Período,8902094.00,S
400,00.000.000/0001-91,2024-09-30,1,BCO BRASIL S.A.,1023,DF Individual - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2024-01-01,2024-09-30,3.99,Lucro por Ação (R$/Ação),4.65,N

In [31]:
lista_ativos = df3['DENOM_CIA'].unique().tolist()
lista_final = []
for ativo in lista_ativos:
    dfativo = df3[df3['DENOM_CIA']==ativo]

    # RECEITA LIQUIDA 3.01

    dfativo_3_01 = dfativo[dfativo['CD_CONTA']=='3.01']
    datas_unicas_ini = dfativo_3_01['DT_INI_EXERC'].unique().tolist()
    datas_unicas_fim = dfativo_3_01['DT_FIM_EXERC'].unique().tolist()

    receita_liquida_total = []
    if len(datas_unicas_ini) == 3 and len(datas_unicas_fim) == 3:
        for i in range(len(datas_unicas_ini)):
            data_ini = datas_unicas_ini[i]
            data_fim = datas_unicas_fim[i]
            # print(f'Para o ativo {ativo}, a Data de início é {data_ini} e a data de fim é {data_fim}.')
            receita_liquida = dfativo_3_01.query('DT_INI_EXERC==@data_ini and DT_FIM_EXERC==@data_fim')['VL_CONTA'].values
            receita_liquida_total.extend(receita_liquida)
    
    # EBIT 3.05

    dfativo_3_05 = dfativo[dfativo['CD_CONTA']=='3.05']
    datas_unicas_ini_3_05 = dfativo_3_05['DT_INI_EXERC'].unique().tolist()
    datas_unicas_fim_3_05 = dfativo_3_05['DT_FIM_EXERC'].unique().tolist() 
    ebit_total = []
    if len(datas_unicas_ini_3_05) == 3 and len(datas_unicas_fim_3_05) == 3:
        for i in range(len(datas_unicas_ini_3_05)):
            data_ini = datas_unicas_ini_3_05[i]
            data_fim = datas_unicas_fim_3_05[i]
            # print(f'Para o ativo {ativo}, a Data de início é {data_ini} e a data de fim é {data_fim}.')
            ebit = dfativo_3_05.query('DT_INI_EXERC==@data_ini and DT_FIM_EXERC==@data_fim')['VL_CONTA'].values
            ebit_total.extend(ebit)

    #  LUCRO LIQUIDO 3.11

    dfativo_3_11 = dfativo[dfativo['CD_CONTA']=='3.11']
    datas_unicas_ini_3_11 = dfativo_3_11['DT_INI_EXERC'].unique().tolist()
    datas_unicas_fim_3_11 = dfativo_3_11['DT_FIM_EXERC'].unique().tolist() 
    lucro_liquido_total = []
    if len(datas_unicas_ini_3_11) == 3  and len(datas_unicas_fim_3_11) == 3:
        for i in range(len(datas_unicas_ini_3_11)):
            data_ini = datas_unicas_ini_3_11[i]
            data_fim = datas_unicas_fim_3_11[i]
            # print(f'Para o ativo {ativo}, a Data de início é {data_ini} e a data de fim é {data_fim}.')
            lucro_liquido = dfativo_3_11.query('DT_INI_EXERC==@data_ini and DT_FIM_EXERC==@data_fim')['VL_CONTA'].values
            lucro_liquido_total.extend(lucro_liquido)

    # print(f'Ativo: {ativo}')
    # print(f'Receita Líquida: {receita_liquida_total}')
    # print(f'EBIT: {ebit_total}')
    # print(f'Lucro Líquido: {lucro_liquido_total}')
    # print('-----------------------------')

    if len(receita_liquida_total) == 3 and len(ebit_total) == 3 and len(lucro_liquido_total) == 3:  
        dicio ={
            'ativo': ativo,
            f'receita_liquida_{DATA_PRINCIPAL[0]}': receita_liquida_total[0],
            f'receita_liquida_{DATA_PRINCIPAL[1]}': receita_liquida_total[1],
            f'receita_liquida_{DATA_PRINCIPAL[2]}': receita_liquida_total[2],

            f'ebit_{DATA_PRINCIPAL[0]}': ebit_total[0],
            f'ebit_{DATA_PRINCIPAL[1]}': ebit_total[1],
            f'ebit_{DATA_PRINCIPAL[2]}': ebit_total[2],

            f'lucro_liquido_{DATA_PRINCIPAL[0]}': lucro_liquido_total[0],
            f'lucro_liquido_{DATA_PRINCIPAL[1]}': lucro_liquido_total[1],
            f'lucro_liquido_{DATA_PRINCIPAL[2]}': lucro_liquido_total[2]
        }
        lista_final.append(dicio)

In [33]:
df_dre = pd.DataFrame(lista_final)
print(df_dre.shape)
df_dre.head()

(688, 10)

,ativo,receita_liquida_2024-03-31,receita_liquida_2024-06-30,receita_liquida_2024-09-30,ebit_2024-03-31,ebit_2024-06-30,ebit_2024-09-30,lucro_liquido_2024-03-31,lucro_liquido_2024-06-30,lucro_liquido_2024-09-30
0,BCO BRASIL S.A.,64576794.0,69614825.0,61155117.0,8784024.0,10502570.0,9051520.0,8781639.0,8888148.0,8902094.0
1,BRB BANCO DE BRASILIA S.A.,1730096.0,1959461.0,1609499.0,-113027.0,51366.0,126849.0,-42922.0,50643.0,85980.0
2,AXIA ENERGIA S.A.,14662.0,14891.0,2617631.0,1142962.0,1554780.0,8699292.0,328051.0,1740304.0,7201919.0
3,COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB,31184.0,0.0,0.0,36137.0,24820.0,35463.0,43503.0,31036.0,47829.0
4,CARAMURU ALIMENTOS S.A.,1253276.0,2066121.0,2068175.0,-64074.0,318237.0,98801.0,-51379.0,100276.0,58757.0

In [34]:
print(df_bpa.info())
print(df_bpp.info())
print(df_dre.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 681 entries, 0 to 680
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ativo                   681 non-null    object
 1   caixa_2024-03-31        681 non-null    float64
 2   caixa_2024-06-30        681 non-null    float64
 3   caixa_2024-09-30        681 non-null    float64
 4   ativo_total_2024-03-31  681 non-null    float64
 5   ativo_total_2024-06-30  681 non-null    float64
 6   ativo_total_2024-09-30  681 non-null    float64
dtypes: float64(6), object(1)
memory usage: 37.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 669 entries, 0 to 668
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ativo                 669 non-null    object
 1   divida_cp_2024-03-31  669 non-null    float64
 2   divida_cp_2024-06-30  669 non-null    float64
 3   divida_cp_2024-09-30  669 non-null    float64
 4   divida_lp_2024-03-31  669 non-null    float64
 5   divida_lp_2024-06-30  669 non-null    float64
 6   divida_lp_2024-09-30  669 non-null    float64
 7   pl_2024-03-31         669 non-null    float64
 8   pl_2024-06-30         669 non-null    float64
 9   pl_2024-09-30         669 non-null    float64
dtypes: float64(9), object(1)
memory usage: 52.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 688 entries, 0 to 687
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ativo                       688 non-null    object
 1   receita_liquida_2024-03-31  688 non-null    float64
 2   receita_liquida_2024-06-30  688 non-null    float64
 3   receita_liquida_2024-09-30  688 non-null    float64
 4   ebit_2024-03-31             688 non-null    float64
 5   ebit_2024-06-30             688 non-null    float64
 6   ebit_2024-09-30             688 non-null    float64
 7   lucro_liquido_2024-03-31    688 non-null    float64
 8   lucro_liquido_2024-06-30    688 non-null    float64
 9   lucro_liquido_2024-09-30    688 non-null    float64
dtypes: float64(9), object(1)
memory usage: 53.9+ KB
None

In [35]:
df_final = df_bpa.merge(df_bpp, on="ativo", how="inner") \
           .merge(df_dre, on="ativo", how="inner")

print(df_bpa.shape)
print(df_bpp.shape)
print(df_dre.shape)
print('----')
print(df_final.shape)

(681, 7)
(669, 10)
(688, 10)
----
(669, 25)

In [42]:
df_final.to_excel('resultado/dados_final_2024.xlsx', index=False)

## ------ FIMM DA RASPAGEM

## _____________________________

## -------- INICIO DAS FORMULAS (MAGIC FORMULA E PIOTROSKI)

In [36]:
df_final.head()

,ativo,caixa_2024-03-31,caixa_2024-06-30,caixa_2024-09-30,ativo_total_2024-03-31,ativo_total_2024-06-30,ativo_total_2024-09-30,divida_cp_2024-03-31,divida_cp_2024-06-30,divida_cp_2024-09-30,...,pl_2024-09-30,receita_liquida_2024-03-31,receita_liquida_2024-06-30,receita_liquida_2024-09-30,ebit_2024-03-31,ebit_2024-06-30,ebit_2024-09-30,lucro_liquido_2024-03-31,lucro_liquido_2024-06-30,lucro_liquido_2024-09-30
0,BRB BANCO DE BRASILIA S.A.,198509.0,206874.0,184914.0,48956942.0,52968283.0,55454106.0,0.0,0.0,0.0,...,761042.0,1730096.0,1959461.0,1609499.0,-113027.0,51366.0,126849.0,-42922.0,50643.0,85980.0
1,AXIA ENERGIA S.A.,5599108.0,9268560.0,12297511.0,170900356.0,176208252.0,208154087.0,10206870.0,6967314.0,10321523.0,...,121252094.0,14662.0,14891.0,2617631.0,1142962.0,1554780.0,8699292.0,328051.0,1740304.0,7201919.0
2,COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB,284631.0,311733.0,319477.0,1108991.0,1065032.0,1095824.0,0.0,0.0,0.0,...,1075355.0,31184.0,0.0,0.0,36137.0,24820.0,35463.0,43503.0,31036.0,47829.0
3,CARAMURU ALIMENTOS S.A.,1242166.0,1027423.0,749284.0,6650273.0,6763556.0,6066497.0,1019117.0,1093432.0,1229257.0,...,2116102.0,1253276.0,2066121.0,2068175.0,-64074.0,318237.0,98801.0,-51379.0,100276.0,58757.0
4,AUREN OPERAÇÕES S.A.,90952.0,117298.0,96518.0,8731429.0,9162343.0,8984731.0,1154348.0,1045225.0,1018927.0,...,2626967.0,610667.0,588780.0,720844.0,128843.0,77075.0,58168.0,-2035.0,-36594.0,-45919.0

## Filtra só ibov, ta mto dificil limpar os dados de todas as empresas, quero andar mais pra frente 
## e depois voltamos e ampliamos

In [53]:
import pandas as pd
import numpy as np
import yfinance as yf

def normalizar_cnpj(cnpj):
    if pd.isna(cnpj):
        return None
    return str(cnpj).replace('.','').replace('-','').replace('/','').strip().zfill(14)

# ================================================================
# CONFIGURAÇÃO
# ================================================================

DATAS = DATA_PRINCIPAL

TICKERS_IBOV = [
    "VALE3", "ITUB4", "PETR4", "PETR3", "AXIA3", "BBDC4", "SBSP3", "B3SA3",
    "ITSA4", "BPAC11", "WEGE3", "BBAS3", "EMBJ3", "ABEV3", "EQTL3", "RENT3",
    "RDOR3", "ENEV3", "PRIO3", "VBBR3", "SUZB3", "RADL3", "AXIA7", "VIVT3",
    "UGPA3", "BBDC3", "GGBR4", "CPLE3", "CMIG4", "TIMS3", "TOTS3", "BBSE3",
    "RAIL3", "ENGI11", "AXIA6", "MOTV3", "KLBN11", "LREN3", "ALOS3", "MBRF3",
    "SANB11", "ASAI3", "EGIE3", "ISAE4", "CSAN3", "CSMG3", "MULT3", "CXSE3",
    "SMFT3", "TAEE11", "PSSA3", "CPFE3", "CMIN3", "BRAV3", "CYRE3", "GOAU4",
    "FLRY3", "NATU3", "HYPE3", "COGN3", "CURY3", "CSNA3", "IGTI11", "BRAP4",
    "DIRR3", "IRBR3", "POMO4", "MGLU3", "MRVE3", "VIVA3", "AURE3", "SLCE3",
    "YDUQ3", "AZZA3", "RECV3", "USIM5", "HAPV3", "CEAB3", "BRKM5", "BEEF3",
    "RENT4", "VAMO3", "CYRE4", "PCAR3", "RAIZ4",
]

# ================================================================
# 1) CARREGA dados_final_2025.xlsx e transforma em formato longo
# ================================================================

# df_wide = pd.read_excel('resultado/dados_final_2024.xlsx')
df_wide = df_final
print(f"Empresas no arquivo: {len(df_wide)}")

# Transforma de wide para long (uma linha por empresa por data)
rows = []
for _, row in df_wide.iterrows():
    for data in DATAS:
        rows.append({
            'ativo':         row['ativo'],
            'dt_refer':      data,
            'caixa':         row[f'caixa_{data}'],
            'ativo_total':   row[f'ativo_total_{data}'],
            'divida_cp':     row[f'divida_cp_{data}'],
            'divida_lp':     row[f'divida_lp_{data}'],
            'pl':            row[f'pl_{data}'],
            'receita':       row[f'receita_liquida_{data}'],
            'ebit':          row[f'ebit_{data}'],
            'lucro':         row[f'lucro_liquido_{data}'],
        })

df = pd.DataFrame(rows)
print(f"Total linhas (empresa × data): {len(df)}")

# ================================================================
# 2) MAPEIA ticker → nome da empresa
# ================================================================

# Carrega mapeamento B3
df_mapa = pd.read_excel('../mapeamento_ticker.xlsx')

def empresa_tem_ticker(todos_tickers: str, ticker: str) -> bool:
    if pd.isna(todos_tickers):
        return False
    return ticker in [t.strip() for t in str(todos_tickers).split(',')]

# Para cada ticker do Ibovespa, busca o nome da empresa
ticker_para_nome = {}
for ticker in TICKERS_IBOV:
    match = df_mapa[df_mapa['todos_tickers'].apply(
        lambda x: empresa_tem_ticker(x, ticker)
    )]
    if not match.empty:
        ticker_para_nome[ticker] = match.iloc[0]['nome']

print(f"\nTickers mapeados: {len(ticker_para_nome)}/{len(TICKERS_IBOV)}")

# Inverte: nome → ticker
nome_para_ticker = {v: k for k, v in ticker_para_nome.items()}

# ================================================================
# 3) CRUZA nome do ITR com nome do mapeamento B3
# ================================================================

# Carrega CNPJ do ITR
df_itr = pd.read_csv('BPA_2024.csv', sep=';', encoding='latin1')
cnpj_empresa = df_itr[['CNPJ_CIA','DENOM_CIA']].drop_duplicates()
cnpj_empresa.columns = ['cnpj','nome_itr']
cnpj_empresa['cnpj_norm'] = cnpj_empresa['cnpj'].apply(normalizar_cnpj)

# CNPJ do mapeamento B3
df_mapa['cnpj_norm'] = df_mapa['cnpj'].apply(normalizar_cnpj)
cnpj_b3 = df_mapa[['cnpj_norm','nome']].drop_duplicates()
cnpj_b3.columns = ['cnpj_norm','nome_b3']

# Cruza: cnpj → nome_itr + nome_b3
mapa_completo = cnpj_empresa.merge(cnpj_b3, on='cnpj_norm', how='inner')

# Para cada nome_b3 do Ibovespa, pega o nome_itr correspondente
ibov_nomes = {}
for ticker in TICKERS_IBOV:
    if ticker in ticker_para_nome:
        nome_b3 = ticker_para_nome[ticker]
        match = mapa_completo[mapa_completo['nome_b3'] == nome_b3]
        if not match.empty:
            ibov_nomes[ticker] = match.iloc[0]['nome_itr']

print(f"Empresas encontradas no ITR: {len(ibov_nomes)}/{len(TICKERS_IBOV)}")

# ================================================================
# 4) FILTRA df só para empresas do Ibovespa
# ================================================================

nomes_itr_ibov = list(ibov_nomes.values())
df = df[df['ativo'].isin(nomes_itr_ibov)].copy()
print(f"\nLinhas após filtro Ibovespa: {len(df)}")
print(f"Empresas únicas: {df['ativo'].nunique()}")

# Adiciona ticker
nome_itr_para_ticker = {v: k for k, v in ibov_nomes.items()}
df['ticker'] = df['ativo'].map(nome_itr_para_ticker)

# ================================================================
# 5) CALCULA indicadores
# ================================================================

df['divida_bruta']   = df['divida_cp'] + df['divida_lp']
df['divida_liquida'] = df['divida_bruta'] - df['caixa']
df['cap_investido']  = df['pl'] + df['divida_liquida']

df['ROIC']        = df['ebit'] / df['cap_investido']
df['ROE']         = df['lucro'] / df['pl']
df['margem_liq']  = df['lucro'] / df['receita']
df['div_ebitda']  = df['divida_bruta'] / df['ebit']  # proxy EBITDA≈EBIT
df['ROA']         = df['lucro'] / df['ativo_total']

# Remove cap_investido negativo
df = df[df['cap_investido'] > 0].reset_index(drop=True)

print(f"\nApós remover cap_investido ≤ 0: {len(df)} linhas")

# ================================================================
# 6) BUSCA preço histórico
# ================================================================

def get_preco(ticker: str, dt_refer: str):
    try:
        data_fim = pd.Timestamp(dt_refer)
        data_ini = data_fim - pd.Timedelta(days=7)
        hist = yf.download(
            ticker + ".SA",
            start=data_ini,
            end=data_fim + pd.Timedelta(days=1),
            progress=False,
            auto_adjust=True
        )
        if hist.empty:
            return None
        return float(hist["Close"].iloc[-1])
    except Exception:
        return None

combos = df[['ticker','dt_refer']].drop_duplicates()
print(f"\nBuscando preços para {len(combos)} combinações ticker+data...")

precos = {}
for i, row in combos.iterrows():
    key = (row['ticker'], row['dt_refer'])
    precos[key] = get_preco(row['ticker'], row['dt_refer'])
    if (i+1) % 20 == 0:
        print(f"  {i+1}/{len(combos)}...")

df['preco'] = df.apply(lambda r: precos.get((r['ticker'], r['dt_refer'])), axis=1)
print(f"Com preço: {df['preco'].notna().sum()}/{len(df)}")

# ================================================================
# 7) BUSCA número de ações
# ================================================================

df_cap = pd.read_csv(
    'itr_cia_aberta_composicao_capital_2024.csv',
    sep=';', encoding='latin1', dtype={'CNPJ_CIA': str}
)
df_cap['cnpj_norm']  = df_cap['CNPJ_CIA'].apply(normalizar_cnpj)
df_cap['acoes_circ'] = df_cap['QT_ACAO_TOTAL_CAP_INTEGR'] - df_cap['QT_ACAO_TOTAL_TESOURO']
df_cap['dt_refer']   = pd.to_datetime(df_cap['DT_REFER'], dayfirst=True).dt.strftime('%Y-%m-%d')
df_cap = df_cap.sort_values('VERSAO', ascending=False).drop_duplicates(subset=['cnpj_norm','dt_refer'])
df_cap = df_cap[['cnpj_norm','dt_refer','acoes_circ']]

# Adiciona cnpj_norm no df
df = df.merge(
    cnpj_empresa[['nome_itr','cnpj_norm']].rename(columns={'nome_itr':'ativo'}),
    on='ativo',
    how='left'
)

# Junta ações
df = df.merge(df_cap, on=['cnpj_norm','dt_refer'], how='left')
print(f"Com ações: {df['acoes_circ'].notna().sum()}/{len(df)}")

# ================================================================
# 8) CALCULA EV e Earnings Yield
# ================================================================

df['valor_mercado']   = df['preco'] * df['acoes_circ']
df['EV']              = df['valor_mercado'] + df['cap_investido'] - df['pl']
df['earnings_yield']  = df['ebit'] / df['EV']

# ================================================================
# RESULTADO FINAL
# ================================================================

df_final = df[[
    'ativo', 'ticker', 'dt_refer', 
    'preco', 'acoes_circ', 'valor_mercado',
    'ebit', 'cap_investido', 'pl', 'EV',
    'ROIC', 'earnings_yield', 'ROE', 'margem_liq', 'div_ebitda', 'ROA'
]].copy()

print("\n" + "="*70)
print("RESULTADO FINAL")
print("="*70)
print(f"Total linhas:  {len(df_final)}")
print(f"Empresas:      {df_final['ativo'].nunique()}")
print(f"Tickers:       {df_final['ticker'].nunique()}")
print(f"Com EV:        {df_final['EV'].notna().sum()}")
print(f"Com EY:        {df_final['earnings_yield'].notna().sum()}")
print()
print(df_final[['ativo','ticker','dt_refer','earnings_yield','ROIC']].head(12).to_string(index=False))
print()

# Salva
df_final.to_excel('ibovespa_magic_formula_2024.xlsx', index=False)
print("Salvo: ibovespa_magic_formula_2024.xlsx")

Empresas no arquivo: 669
Total linhas (empresa × data): 2007

Tickers mapeados: 83/85
Empresas encontradas no ITR: 78/85

Linhas após filtro Ibovespa: 210
Empresas únicas: 70

Após remover cap_investido ≤ 0: 206 linhas

Buscando preços para 206 combinações ticker+data...

C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  20/206...

C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
$MOTV3.SA: possibly delisted; no price data found  (1d 2024-03-24 00:00:00 -> 2024-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1711249200, endDate = 1711940400")

1 Failed download:
['MOTV3.SA']: possibly delisted; no price data found  (1d 2024-03-24 00:00:00 -> 2024-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1711249200, endDate = 1711940400")
$MOTV3.SA: possibly delisted; no price data found  (1d 2024-06-23 00:00:00 -> 2024-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1719111600, endDate = 1719802800")

1 Failed download:
['MOTV3.SA']: possibly delisted; no price data found  (1d 2024-06-23 00:00:00 -> 2024-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1719111600, endDate = 1719802800")
$MOTV3.SA: possibly delisted; no price data found  (1d 2024-09-23 00:00:00 -> 2024-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1727060400, endDate = 1727751600")

1 Failed download:
['MOTV3.SA']: possibly delisted; no price data found  (1d 2024-09-23 00:00:00 -> 2024-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1727060400, endDate = 1727751600")
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  40/206...

C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  60/206...

C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
$EMBJ3.SA: possibly delisted; no price data found  (1d 2024-03-24 00:00:00 -> 2024-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1711249200, endDate = 1711940400")

1 Failed download:
['EMBJ3.SA']: possibly delisted; no price data found  (1d 2024-03-24 00:00:00 -> 2024-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1711249200, endDate = 1711940400")
$EMBJ3.SA: possibly delisted; no price data found  (1d 2024-06-23 00:00:00 -> 2024-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1719111600, endDate = 1719802800")

1 Failed download:
['EMBJ3.SA']: possibly delisted; no price data found  (1d 2024-06-23 00:00:00 -> 2024-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1719111600, endDate = 1719802800")
$EMBJ3.SA: possibly delisted; no price data found  (1d 2024-09-23 00:00:00 -> 2024-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1727060400, endDate = 1727751600")

1 Failed download:
['EMBJ3.SA']: possibly delisted; no price data found  (1d 2024-09-23 00:00:00 -> 2024-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1727060400, endDate = 1727751600")
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  80/206...

C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
$RENT4.SA: possibly delisted; no price data found  (1d 2024-03-24 00:00:00 -> 2024-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1711249200, endDate = 1711940400")

1 Failed download:
['RENT4.SA']: possibly delisted; no price data found  (1d 2024-03-24 00:00:00 -> 2024-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1711249200, endDate = 1711940400")

  100/206...

$RENT4.SA: possibly delisted; no price data found  (1d 2024-06-23 00:00:00 -> 2024-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1719111600, endDate = 1719802800")

1 Failed download:
['RENT4.SA']: possibly delisted; no price data found  (1d 2024-06-23 00:00:00 -> 2024-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1719111600, endDate = 1719802800")
$RENT4.SA: possibly delisted; no price data found  (1d 2024-09-23 00:00:00 -> 2024-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1727060400, endDate = 1727751600")

1 Failed download:
['RENT4.SA']: possibly delisted; no price data found  (1d 2024-09-23 00:00:00 -> 2024-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1727060400, endDate = 1727751600")
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  120/206...

C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  140/206...

C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  160/206...

C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
$NATU3.SA: possibly delisted; no price data found  (1d 2024-03-24 00:00:00 -> 2024-04-01 00:00:00)

1 Failed download:
['NATU3.SA']: possibly delisted; no price data found  (1d 2024-03-24 00:00:00 -> 2024-04-01 00:00:00)

  180/206...

$NATU3.SA: possibly delisted; no price data found  (1d 2024-06-23 00:00:00 -> 2024-07-01 00:00:00)

1 Failed download:
['NATU3.SA']: possibly delisted; no price data found  (1d 2024-06-23 00:00:00 -> 2024-07-01 00:00:00)
$NATU3.SA: possibly delisted; no price data found  (1d 2024-09-23 00:00:00 -> 2024-10-01 00:00:00)

1 Failed download:
['NATU3.SA']: possibly delisted; no price data found  (1d 2024-09-23 00:00:00 -> 2024-10-01 00:00:00)
$CYRE4.SA: possibly delisted; no price data found  (1d 2024-03-24 00:00:00 -> 2024-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1711249200, endDate = 1711940400")

1 Failed download:
['CYRE4.SA']: possibly delisted; no price data found  (1d 2024-03-24 00:00:00 -> 2024-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1711249200, endDate = 1711940400")
$CYRE4.SA: possibly delisted; no price data found  (1d 2024-06-23 00:00:00 -> 2024-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1719111600, endDate = 1719802800")

1 Failed download:
['CYRE4.SA']: possibly delisted; no price data found  (1d 2024-06-23 00:00:00 -> 2024-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1719111600, endDate = 1719802800")
$CYRE4.SA: possibly delisted; no price data found  (1d 2024-09-23 00:00:00 -> 2024-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1727060400, endDate = 1727751600")

1 Failed download:
['CYRE4.SA']: possibly delisted; no price data found  (1d 2024-09-23 00:00:00 -> 2024-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1727060400, endDate = 1727751600")
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  200/206...

C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_18284\3303327912.py:189: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df_cap['dt_refer']   = pd.to_datetime(df_cap['DT_REFER'], dayfirst=True).dt.strftime('%Y-%m-%d')

Com preço: 191/206
Com ações: 206/206

======================================================================
RESULTADO FINAL
======================================================================
Total linhas:  206
Empresas:      69
Tickers:       69
Com EV:        191
Com EY:        191

            ativo ticker   dt_refer  earnings_yield      ROIC
AXIA ENERGIA S.A.  AXIA6 2024-03-31        0.011749  0.008014
AXIA ENERGIA S.A.  AXIA6 2024-06-30        0.016676  0.010635
AXIA ENERGIA S.A.  AXIA6 2024-09-30        0.084939  0.055381
    ENERGISA S.A. ENGI11 2024-03-31        0.000011  0.037959
    ENERGISA S.A. ENGI11 2024-06-30        0.000006  0.018084
    ENERGISA S.A. ENGI11 2024-09-30        0.000006  0.020887
PORTO SEGURO S.A.  PSSA3 2024-03-31        0.036171  0.051927
PORTO SEGURO S.A.  PSSA3 2024-06-30        0.000031  0.043089
PORTO SEGURO S.A.  PSSA3 2024-09-30        0.032134  0.050918
        RUMO S.A.  RAIL3 2024-03-31        0.000012  0.023806
        RUMO S.A.  RAIL3 2024-06-30       -0.000044 -0.091527
        RUMO S.A.  RAIL3 2024-09-30        0.000023  0.042862

Salvo: ibovespa_magic_formula_2024.xlsx

Como a Magic Formula Original Funciona

Rankeia todas as ações pelo Earnings Yield (maior → melhor → ranking 1, 2, 3...)
Rankeia todas as ações pelo ROIC (maior → melhor → ranking 1, 2, 3...)
Soma os rankings (não os valores)
Seleciona as top 20-30 com menor ranking combinado