In [2]:
import pandas as pd

In [6]:
DATA_PRINCIPAL = ['2023-03-31', '2023-06-30', '2023-09-30']

## BPA --------- FEITO

In [3]:
df = pd.read_csv('bpa-2023.csv', sep=';', encoding='latin-1')
df=df[df['ORDEM_EXERC'] == 'ÚLTIMO']

In [4]:
df

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
1,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2023-03-31,1,Ativo Total,2.139737e+09,S
3,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2023-03-31,1.01,Caixa e Equivalentes de Caixa,6.064200e+07,S
5,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2023-03-31,1.01.01,Caixa,1.976983e+07,S
7,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2023-03-31,1.01.02,Aplicações de Liquidez,4.087218e+07,S
9,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2023-03-31,1.02,Ativos Financeiros,1.922386e+09,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285521,97.837.181/0001-47,2023-09-30,1,DEXCO S.A.,21091,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2023-09-30,1.02.04.01.04,Goodwill na Aquisição da Satipel em 2009,4.550300e+04,N
285523,97.837.181/0001-47,2023-09-30,1,DEXCO S.A.,21091,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2023-09-30,1.02.04.01.05,Goodwill de Empresa Incorporada em 2010,0.000000e+00,N
285525,97.837.181/0001-47,2023-09-30,1,DEXCO S.A.,21091,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2023-09-30,1.02.04.01.06,Goodwill de Empresa Incorporada em 2011,0.000000e+00,N
285527,97.837.181/0001-47,2023-09-30,1,DEXCO S.A.,21091,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2023-09-30,1.02.04.01.07,Goodwill de Empresa Incorporada em 2012,2.402000e+03,N
285529,97.837.181/0001-47,2023-09-30,1,DEXCO S.A.,21091,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2023-09-30,1.02.04.01.08,Goodwill de Empresa Incorporada em 2014,0.000000e+00,N

In [5]:
df['DT_REFER'].unique().tolist()

['2023-03-31',
 '2023-06-30',
 '2023-09-30',
 '2023-12-31',
 '2023-05-31',
 '2023-08-31',
 '2023-11-30']

In [7]:
lista_ativos = df['DENOM_CIA'].unique().tolist()
lista_final = []
data_refer = df['DT_REFER'].unique().tolist()
datas = df['DT_FIM_EXERC'].unique().tolist()
for ativo in lista_ativos:
    dfativo = df[df['DENOM_CIA']==ativo]
    
    caixa = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="1.01.01"')['VL_CONTA'].values
    ativo_total = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="1"')['VL_CONTA'].values
    

    if len(caixa) == 3 and len(ativo_total) == 3:
        dicio = {
            'ativo': ativo,
            
            f'caixa_{DATA_PRINCIPAL[0]}': caixa[0],
            f'caixa_{DATA_PRINCIPAL[1]}': caixa[1],
            f'caixa_{DATA_PRINCIPAL[2]}': caixa[2],
            
           

            f'ativo_total_{DATA_PRINCIPAL[0]}': ativo_total[0],
            f'ativo_total_{DATA_PRINCIPAL[1]}': ativo_total[1],
            f'ativo_total_{DATA_PRINCIPAL[2]}': ativo_total[2],
            

        
        }    
        lista_final.append(dicio)

In [8]:
df_bpa = pd.DataFrame(lista_final)
print(df_bpa.shape)
df_bpa.head()

(690, 7)

,ativo,caixa_2023-03-31,caixa_2023-06-30,caixa_2023-09-30,ativo_total_2023-03-31,ativo_total_2023-06-30,ativo_total_2023-09-30
0,BCO BRASIL S.A.,19769828.0,18574583.0,20153644.0,2.139737e+09,2.124392e+09,2.270914e+09
1,BRB BANCO DE BRASILIA S.A.,215199.0,198821.0,231497.0,4.137989e+07,4.537458e+07,4.727356e+07
2,AXIA ENERGIA S.A.,8536113.0,5605564.0,11043427.0,1.692107e+08,1.650723e+08,1.704976e+08
3,COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB,314961.0,217045.0,257338.0,1.114230e+06,1.040635e+06,1.085379e+06
4,CARAMURU ALIMENTOS S.A.,677678.0,389470.0,522797.0,8.608682e+06,7.995148e+06,7.347580e+06

## BPP ------------ Fazendo

In [13]:
df2 = pd.read_csv('bpp-2023.csv', sep=';', encoding='latin-1')
df2=df2[df2['ORDEM_EXERC'] == 'ÚLTIMO']
df2.head(60)

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
1,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2,Passivo Total,2.139737e+09,S
3,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.01,Passivos Financeiros Avaliados ao Valor Justo ...,5.208515e+06,S
5,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.01.01,Instrumentos financeiros derivativos,5.208515e+06,N
7,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.02,Passivos Financeiros ao Custo Amortizado,1.900355e+09,S
9,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.02.01,Depósitos,1.900355e+09,S
11,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.02.01.01,Recursos de instituições financeiras,8.060429e+08,N
13,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.02.01.02,Recursos de clientes,7.167760e+08,N
15,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.02.01.03,Recursos de emissões de títulos e valores mobi...,2.400656e+08,N
17,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.02.01.06,Outros passivos financeiros,1.374705e+08,N
19,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.02.02,Captações no Mercado Aberto,0.000000e+00,S
21,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.02.03,Recursos Mercado Interfinanceiro,0.000000e+00,S
23,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.02.04,Outras Captações,0.000000e+00,S
25,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.03,Provisões,2.562849e+07,S
27,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.04,Passivos Fiscais,1.635677e+07,S
29,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.05,Outros Passivos,3.362891e+07,S
31,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.05.01,Capital Social Realizado,0.000000e+00,N
33,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.05.02,Reservas de Capital,0.000000e+00,N
35,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.05.03,Reservas de Reavaliação,0.000000e+00,N
37,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.05.04,Reservas de Lucro,0.000000e+00,N
39,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.05.05,Ajustes de Avaliação Patrimonial,0.000000e+00,N
41,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.05.06,Lucros/Prejuízos Acumulados,0.000000e+00,N
43,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.06,Passivos sobre Ativos Não Correntes a Venda e ...,0.000000e+00,S
45,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.06.01,Passivos sobre Ativos Não Correntes a Venda,0.000000e+00,S
47,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.06.02,Passivos sobre Ativos de Operações Descontinuadas,0.000000e+00,S
49,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.07,Patrimônio Líquido,1.585597e+08,S
51,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.07.01,Capital Social Realizado,9.000002e+07,S
53,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.07.02,Reservas de Capital,1.406118e+06,S
55,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.07.02.01,Ágio na Emissão de Ações,0.000000e+00,S
57,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.07.02.02,Reserva Especial de Ágio na Incorporação,0.000000e+00,S
59,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.07.02.03,Alienação de Bônus de Subscrição,0.000000e+00,S
61,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.07.02.04,Opções Outorgadas,0.000000e+00,S
63,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.07.02.05,Ações em Tesouraria,0.000000e+00,S
65,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.07.03,Reservas de Reavaliação,0.000000e+00,S
67,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.07.04,Reservas de Lucros,6.702077e+07,S
69,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.07.04.01,Reserva Legal,1.177764e+07,S
71,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.07.04.02,Reserva Estatutária,5.550961e+07,S
73,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.07.04.03,Reserva para Contingências,0.000000e+00,S
75,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.07.04.04,Reserva de Lucros a Realizar,0.000000e+00,S
77,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.07.04.05,Reserva de Retenção de Lucros,0.000000e+00,S
79,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.07.04.06,Reserva Especial para Dividendos Não Distribuídos,0.000000e+00,S
81,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.07.04.07,Reserva de Incentivos Fiscais,0.000000e+00,S
83,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.07.04.08,Dividendo Adicional Proposto,0.000000e+00,S
85,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.07.04.09,Ações em Tesouraria,-2.664710e+05,S
87,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.07.05,Lucros/Prejuízos Acumulados,8.403715e+06,S
89,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.07.06,Ajustes de Avaliação Patrimonial,0.000000e+00,S
91,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.07.07,Ajustes Acumulados de Conversão,0.000000e+00,S
93,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-03-31,2.07.08,Outros Resultados Abrangentes,-8.270960e+06,S
95,00.000.000/0001-91,2023-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-06-30,2,Passivo Total,2.124392e+09,S
97,00.000.000/0001-91,2023-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-06-30,2.01,Passivos Financeiros Avaliados ao Valor Justo ...,5.289398e+06,S
99,00.000.000/0001-91,2023-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-06-30,2.01.01,Instrumentos financeiros derivativos,5.289398e+06,N
101,00.000.000/0001-91,2023-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-06-30,2.02,Passivos Financeiros ao Custo Amortizado,1.885279e+09,S
103,00.000.000/0001-91,2023-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-06-30,2.02.01,Depósitos,1.885279e+09,S
105,00.000.000/0001-91,2023-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-06-30,2.02.01.01,Recursos de instituições financeiras,7.371131e+08,N
107,00.000.000/0001-91,2023-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-06-30,2.02.01.02,Recursos de clientes,7.347885e+08,N
109,00.000.000/0001-91,2023-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-06-30,2.02.01.03,Recursos de emissões de títulos e valores mobi...,2.598944e+08,N
111,00.000.000/0001-91,2023-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-06-30,2.02.01.06,Outros passivos financeiros,1.534833e+08,N
113,00.000.000/0001-91,2023-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-06-30,2.02.02,Captações no Mercado Aberto,0.000000e+00,S
115,00.000.000/0001-91,2023-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-06-30,2.02.03,Recursos Mercado Interfinanceiro,0.000000e+00,S
117,00.000.000/0001-91,2023-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-06-30,2.02.04,Outras Captações,0.000000e+00,S
119,00.000.000/0001-91,2023-06-30,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2023-06-30,2.03,Provisões,2.551822e+07,S

In [10]:
lista_ativos = df2['DENOM_CIA'].unique().tolist()
lista_final = []
data_refer = df2['DT_REFER'].unique().tolist()
datas = df2['DT_FIM_EXERC'].unique().tolist()
for ativo in lista_ativos:
    dfativo = df2[df2['DENOM_CIA']==ativo]
    # datas = dfativo['DT_REFER'].unique().tolist() 
    divida_cp = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="2.01.04"')['VL_CONTA'].values
    divida_lp = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="2.02.01"')['VL_CONTA'].values
    pl = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="2.03"')['VL_CONTA'].values

    if len(divida_cp) == 3 and len(divida_lp) == 3 and len(pl) == 3:
        dicio = {
            'ativo': ativo,
            
            f'divida_cp_{DATA_PRINCIPAL[0]}': divida_cp[0],
            f'divida_cp_{DATA_PRINCIPAL[1]}': divida_cp[1],
            f'divida_cp_{DATA_PRINCIPAL[2]}': divida_cp[2],
            
            
            f'divida_lp_{DATA_PRINCIPAL[0]}': divida_lp[0],
            f'divida_lp_{DATA_PRINCIPAL[1]}': divida_lp[1],
            f'divida_lp_{DATA_PRINCIPAL[2]}': divida_lp[2],
        
            
            f'pl_{DATA_PRINCIPAL[0]}': pl[0],
            f'pl_{DATA_PRINCIPAL[1]}': pl[1],
            f'pl_{DATA_PRINCIPAL[2]}': pl[2]
        
        }    
        lista_final.append(dicio)

In [14]:
df_bpp = pd.DataFrame(lista_final)
print(df_bpp.shape)
df_bpp.head()

(676, 10)

,ativo,divida_cp_2023-03-31,divida_cp_2023-06-30,divida_cp_2023-09-30,divida_lp_2023-03-31,divida_lp_2023-06-30,divida_lp_2023-09-30,pl_2023-03-31,pl_2023-06-30,pl_2023-09-30
0,BRB BANCO DE BRASILIA S.A.,0.0,0.0,0.0,23375563.0,27133185.0,27614721.0,695970.0,709321.0,716163.0
1,AXIA ENERGIA S.A.,3865902.0,11718021.0,12214276.0,21713435.0,12704707.0,19437824.0,110884116.0,111401840.0,113118115.0
2,COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB,0.0,0.0,0.0,0.0,0.0,0.0,1029470.0,1003463.0,1045455.0
3,CARAMURU ALIMENTOS S.A.,2152145.0,2111092.0,1580429.0,1600727.0,1526022.0,1371686.0,1837795.0,1916559.0,2048489.0
4,NEUMARKT TRADE AND FINANCIAL CENTER S/A,0.0,0.0,0.0,74158.0,74158.0,74158.0,-73435.0,-73468.0,-73684.0

## DRE ------------ Fazendo

In [15]:
df3 = pd.read_csv('dre-2023.csv', sep=';', encoding='latin-1')
df3=df3[df3['ORDEM_EXERC'] == 'ÚLTIMO']

In [16]:
print(df3.shape)
df3.head(200)

(81714, 15)

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
1,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2023-01-01,2023-03-31,3.01,Receitas de Intermediação Financeira,65909746.0,S
3,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2023-01-01,2023-03-31,3.01.01,Receita de Juros,65909746.0,N
5,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2023-01-01,2023-03-31,3.02,Despesas de Intermediação Financeira,-44693912.0,S
7,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2023-01-01,2023-03-31,3.02.01,Despesa de Juros,-44693912.0,N
9,00.000.000/0001-91,2023-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2023-01-01,2023-03-31,3.03,Resultado Bruto de Intermediação Financeira,21215834.0,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,00.000.208/0001-00,2023-03-31,4,BRB BANCO DE BRASILIA S.A.,14206,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2023-01-01,2023-03-31,3.04.07,Outras Despesas Operacionais,-69555.0,S
393,00.000.208/0001-00,2023-03-31,4,BRB BANCO DE BRASILIA S.A.,14206,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2023-01-01,2023-03-31,3.04.08,Resultado da Equivalência Patrimonial,0.0,S
395,00.000.208/0001-00,2023-03-31,4,BRB BANCO DE BRASILIA S.A.,14206,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2023-01-01,2023-03-31,3.05,Resultado antes dos Tributos sobre o Lucro,-189866.0,S
397,00.000.208/0001-00,2023-03-31,4,BRB BANCO DE BRASILIA S.A.,14206,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2023-01-01,2023-03-31,3.06,Imposto de Renda e Contribuição Social sobre o...,97259.0,S
399,00.000.208/0001-00,2023-03-31,4,BRB BANCO DE BRASILIA S.A.,14206,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2023-01-01,2023-03-31,3.06.01,Corrente,-6129.0,S

In [17]:
lista_ativos = df3['DENOM_CIA'].unique().tolist()
lista_final = []
for ativo in lista_ativos:
    dfativo = df3[df3['DENOM_CIA']==ativo]

    # RECEITA LIQUIDA 3.01

    dfativo_3_01 = dfativo[dfativo['CD_CONTA']=='3.01']
    datas_unicas_ini = dfativo_3_01['DT_INI_EXERC'].unique().tolist()
    datas_unicas_fim = dfativo_3_01['DT_FIM_EXERC'].unique().tolist()

    receita_liquida_total = []
    if len(datas_unicas_ini) == 3 and len(datas_unicas_fim) == 3:
        for i in range(len(datas_unicas_ini)):
            data_ini = datas_unicas_ini[i]
            data_fim = datas_unicas_fim[i]
            # print(f'Para o ativo {ativo}, a Data de início é {data_ini} e a data de fim é {data_fim}.')
            receita_liquida = dfativo_3_01.query('DT_INI_EXERC==@data_ini and DT_FIM_EXERC==@data_fim')['VL_CONTA'].values
            receita_liquida_total.extend(receita_liquida)
    
    # EBIT 3.05

    dfativo_3_05 = dfativo[dfativo['CD_CONTA']=='3.05']
    datas_unicas_ini_3_05 = dfativo_3_05['DT_INI_EXERC'].unique().tolist()
    datas_unicas_fim_3_05 = dfativo_3_05['DT_FIM_EXERC'].unique().tolist() 
    ebit_total = []
    if len(datas_unicas_ini_3_05) == 3 and len(datas_unicas_fim_3_05) == 3:
        for i in range(len(datas_unicas_ini_3_05)):
            data_ini = datas_unicas_ini_3_05[i]
            data_fim = datas_unicas_fim_3_05[i]
            # print(f'Para o ativo {ativo}, a Data de início é {data_ini} e a data de fim é {data_fim}.')
            ebit = dfativo_3_05.query('DT_INI_EXERC==@data_ini and DT_FIM_EXERC==@data_fim')['VL_CONTA'].values
            ebit_total.extend(ebit)

    #  LUCRO LIQUIDO 3.11

    dfativo_3_11 = dfativo[dfativo['CD_CONTA']=='3.11']
    datas_unicas_ini_3_11 = dfativo_3_11['DT_INI_EXERC'].unique().tolist()
    datas_unicas_fim_3_11 = dfativo_3_11['DT_FIM_EXERC'].unique().tolist() 
    lucro_liquido_total = []
    if len(datas_unicas_ini_3_11) == 3  and len(datas_unicas_fim_3_11) == 3:
        for i in range(len(datas_unicas_ini_3_11)):
            data_ini = datas_unicas_ini_3_11[i]
            data_fim = datas_unicas_fim_3_11[i]
            # print(f'Para o ativo {ativo}, a Data de início é {data_ini} e a data de fim é {data_fim}.')
            lucro_liquido = dfativo_3_11.query('DT_INI_EXERC==@data_ini and DT_FIM_EXERC==@data_fim')['VL_CONTA'].values
            lucro_liquido_total.extend(lucro_liquido)

    # print(f'Ativo: {ativo}')
    # print(f'Receita Líquida: {receita_liquida_total}')
    # print(f'EBIT: {ebit_total}')
    # print(f'Lucro Líquido: {lucro_liquido_total}')
    # print('-----------------------------')

    if len(receita_liquida_total) == 3 and len(ebit_total) == 3 and len(lucro_liquido_total) == 3:  
        dicio ={
            'ativo': ativo,
            f'receita_liquida_{DATA_PRINCIPAL[0]}': receita_liquida_total[0],
            f'receita_liquida_{DATA_PRINCIPAL[1]}': receita_liquida_total[1],
            f'receita_liquida_{DATA_PRINCIPAL[2]}': receita_liquida_total[2],

            f'ebit_{DATA_PRINCIPAL[0]}': ebit_total[0],
            f'ebit_{DATA_PRINCIPAL[1]}': ebit_total[1],
            f'ebit_{DATA_PRINCIPAL[2]}': ebit_total[2],

            f'lucro_liquido_{DATA_PRINCIPAL[0]}': lucro_liquido_total[0],
            f'lucro_liquido_{DATA_PRINCIPAL[1]}': lucro_liquido_total[1],
            f'lucro_liquido_{DATA_PRINCIPAL[2]}': lucro_liquido_total[2]
        }
        lista_final.append(dicio)

In [18]:
df_dre = pd.DataFrame(lista_final)
print(df_dre.shape)
df_dre.head()

(442, 10)

,ativo,receita_liquida_2023-03-31,receita_liquida_2023-06-30,receita_liquida_2023-09-30,ebit_2023-03-31,ebit_2023-06-30,ebit_2023-09-30,lucro_liquido_2023-03-31,lucro_liquido_2023-06-30,lucro_liquido_2023-09-30
0,BCO BRASIL S.A.,65909746.0,66896468.0,70840719.0,9082479.0,11777514.0,11301474.0,7290982.0,9092514.0,8841647.0
1,BRB BANCO DE BRASILIA S.A.,1663470.0,1011899.0,1939832.0,-189866.0,331901.0,-93822.0,-93027.0,210886.0,-31507.0
2,AXIA ENERGIA S.A.,9209833.0,9245530.0,8781430.0,3986877.0,5697633.0,3890393.0,405963.0,1618904.0,1476587.0
3,COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB,92560.0,82536.0,85877.0,60475.0,51625.0,54749.0,64842.0,51609.0,55322.0
4,CARAMURU ALIMENTOS S.A.,1491584.0,2015271.0,2100656.0,31747.0,27761.0,209900.0,19756.0,78764.0,131930.0

In [19]:
print(df_bpa.info())
print(df_bpp.info())
print(df_dre.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ativo                   690 non-null    object
 1   caixa_2023-03-31        690 non-null    float64
 2   caixa_2023-06-30        690 non-null    float64
 3   caixa_2023-09-30        690 non-null    float64
 4   ativo_total_2023-03-31  690 non-null    float64
 5   ativo_total_2023-06-30  690 non-null    float64
 6   ativo_total_2023-09-30  690 non-null    float64
dtypes: float64(6), object(1)
memory usage: 37.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 676 entries, 0 to 675
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ativo                 676 non-null    object
 1   divida_cp_2023-03-31  676 non-null    float64
 2   divida_cp_2023-06-30  676 non-null    float64
 3   divida_cp_2023-09-30  676 non-null    float64
 4   divida_lp_2023-03-31  676 non-null    float64
 5   divida_lp_2023-06-30  676 non-null    float64
 6   divida_lp_2023-09-30  676 non-null    float64
 7   pl_2023-03-31         676 non-null    float64
 8   pl_2023-06-30         676 non-null    float64
 9   pl_2023-09-30         676 non-null    float64
dtypes: float64(9), object(1)
memory usage: 52.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ativo                       442 non-null    object
 1   receita_liquida_2023-03-31  442 non-null    float64
 2   receita_liquida_2023-06-30  442 non-null    float64
 3   receita_liquida_2023-09-30  442 non-null    float64
 4   ebit_2023-03-31             442 non-null    float64
 5   ebit_2023-06-30             442 non-null    float64
 6   ebit_2023-09-30             442 non-null    float64
 7   lucro_liquido_2023-03-31    442 non-null    float64
 8   lucro_liquido_2023-06-30    442 non-null    float64
 9   lucro_liquido_2023-09-30    442 non-null    float64
dtypes: float64(9), object(1)
memory usage: 34.7+ KB
None

In [20]:
df_final = df_bpa.merge(df_bpp, on="ativo", how="inner") \
           .merge(df_dre, on="ativo", how="inner")

print(df_bpa.shape)
print(df_bpp.shape)
print(df_dre.shape)
print('----')
print(df_final.shape)

(690, 7)
(676, 10)
(442, 10)
----
(423, 25)

In [21]:
df_final.to_excel('resultado/dados_final_2023.xlsx', index=False)

## ------ FIMM DA RASPAGEM

## _____________________________

## -------- INICIO DAS FORMULAS (MAGIC FORMULA E PIOTROSKI)

In [25]:
print(df_final.shape)
df_final.head()

(423, 25)

,ativo,caixa_2023-03-31,caixa_2023-06-30,caixa_2023-09-30,ativo_total_2023-03-31,ativo_total_2023-06-30,ativo_total_2023-09-30,divida_cp_2023-03-31,divida_cp_2023-06-30,divida_cp_2023-09-30,...,pl_2023-09-30,receita_liquida_2023-03-31,receita_liquida_2023-06-30,receita_liquida_2023-09-30,ebit_2023-03-31,ebit_2023-06-30,ebit_2023-09-30,lucro_liquido_2023-03-31,lucro_liquido_2023-06-30,lucro_liquido_2023-09-30
0,BRB BANCO DE BRASILIA S.A.,215199.0,198821.0,231497.0,41379888.0,45374575.0,47273557.0,0.0,0.0,0.0,...,716163.0,1663470.0,1011899.0,1939832.0,-189866.0,331901.0,-93822.0,-93027.0,210886.0,-31507.0
1,AXIA ENERGIA S.A.,8536113.0,5605564.0,11043427.0,169210749.0,165072265.0,170497628.0,3865902.0,11718021.0,12214276.0,...,113118115.0,9209833.0,9245530.0,8781430.0,3986877.0,5697633.0,3890393.0,405963.0,1618904.0,1476587.0
2,COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB,314961.0,217045.0,257338.0,1114230.0,1040635.0,1085379.0,0.0,0.0,0.0,...,1045455.0,92560.0,82536.0,85877.0,60475.0,51625.0,54749.0,64842.0,51609.0,55322.0
3,CARAMURU ALIMENTOS S.A.,677678.0,389470.0,522797.0,8608682.0,7995148.0,7347580.0,2152145.0,2111092.0,1580429.0,...,2048489.0,1491584.0,2015271.0,2100656.0,31747.0,27761.0,209900.0,19756.0,78764.0,131930.0
4,AUREN OPERAÇÕES S.A.,378.0,412.0,1234.0,8962647.0,8890894.0,8879092.0,459575.0,550714.0,537930.0,...,2803102.0,686246.0,671778.0,808695.0,225677.0,170795.0,217217.0,67672.0,37356.0,101346.0

## ------------

In [27]:
import pandas as pd
import numpy as np
import yfinance as yf

def normalizar_cnpj(cnpj):
    if pd.isna(cnpj):
        return None
    return str(cnpj).replace('.','').replace('-','').replace('/','').strip().zfill(14)

# ================================================================
# CONFIGURAÇÃO
# ================================================================

DATAS = DATA_PRINCIPAL

TICKERS_IBOV = [
    "VALE3", "ITUB4", "PETR4", "PETR3", "AXIA3", "BBDC4", "SBSP3", "B3SA3",
    "ITSA4", "BPAC11", "WEGE3", "BBAS3", "EMBJ3", "ABEV3", "EQTL3", "RENT3",
    "RDOR3", "ENEV3", "PRIO3", "VBBR3", "SUZB3", "RADL3", "AXIA7", "VIVT3",
    "UGPA3", "BBDC3", "GGBR4", "CPLE3", "CMIG4", "TIMS3", "TOTS3", "BBSE3",
    "RAIL3", "ENGI11", "AXIA6", "MOTV3", "KLBN11", "LREN3", "ALOS3", "MBRF3",
    "SANB11", "ASAI3", "EGIE3", "ISAE4", "CSAN3", "CSMG3", "MULT3", "CXSE3",
    "SMFT3", "TAEE11", "PSSA3", "CPFE3", "CMIN3", "BRAV3", "CYRE3", "GOAU4",
    "FLRY3", "NATU3", "HYPE3", "COGN3", "CURY3", "CSNA3", "IGTI11", "BRAP4",
    "DIRR3", "IRBR3", "POMO4", "MGLU3", "MRVE3", "VIVA3", "AURE3", "SLCE3",
    "YDUQ3", "AZZA3", "RECV3", "USIM5", "HAPV3", "CEAB3", "BRKM5", "BEEF3",
    "RENT4", "VAMO3", "CYRE4", "PCAR3", "RAIZ4",
]

# ================================================================
# 1) CARREGA dados_final_2025.xlsx e transforma em formato longo
# ================================================================

# df_wide = pd.read_excel('resultado/dados_final_2024.xlsx')
df_wide = df_final
print(f"Empresas no arquivo: {len(df_wide)}")

# Transforma de wide para long (uma linha por empresa por data)
rows = []
for _, row in df_wide.iterrows():
    for data in DATAS:
        rows.append({
            'ativo':         row['ativo'],
            'dt_refer':      data,
            'caixa':         row[f'caixa_{data}'],
            'ativo_total':   row[f'ativo_total_{data}'],
            'divida_cp':     row[f'divida_cp_{data}'],
            'divida_lp':     row[f'divida_lp_{data}'],
            'pl':            row[f'pl_{data}'],
            'receita':       row[f'receita_liquida_{data}'],
            'ebit':          row[f'ebit_{data}'],
            'lucro':         row[f'lucro_liquido_{data}'],
        })

df = pd.DataFrame(rows)
print(f"Total linhas (empresa × data): {len(df)}")

# ================================================================
# 2) MAPEIA ticker → nome da empresa
# ================================================================

# Carrega mapeamento B3
df_mapa = pd.read_excel('../mapeamento_ticker.xlsx')

def empresa_tem_ticker(todos_tickers: str, ticker: str) -> bool:
    if pd.isna(todos_tickers):
        return False
    return ticker in [t.strip() for t in str(todos_tickers).split(',')]

# Para cada ticker do Ibovespa, busca o nome da empresa
ticker_para_nome = {}
for ticker in TICKERS_IBOV:
    match = df_mapa[df_mapa['todos_tickers'].apply(
        lambda x: empresa_tem_ticker(x, ticker)
    )]
    if not match.empty:
        ticker_para_nome[ticker] = match.iloc[0]['nome']

print(f"\nTickers mapeados: {len(ticker_para_nome)}/{len(TICKERS_IBOV)}")

# Inverte: nome → ticker
nome_para_ticker = {v: k for k, v in ticker_para_nome.items()}

# ================================================================
# 3) CRUZA nome do ITR com nome do mapeamento B3
# ================================================================

# Carrega CNPJ do ITR
df_itr = pd.read_csv('bpp-2023.csv', sep=';', encoding='latin1')
cnpj_empresa = df_itr[['CNPJ_CIA','DENOM_CIA']].drop_duplicates()
cnpj_empresa.columns = ['cnpj','nome_itr']
cnpj_empresa['cnpj_norm'] = cnpj_empresa['cnpj'].apply(normalizar_cnpj)

# CNPJ do mapeamento B3
df_mapa['cnpj_norm'] = df_mapa['cnpj'].apply(normalizar_cnpj)
cnpj_b3 = df_mapa[['cnpj_norm','nome']].drop_duplicates()
cnpj_b3.columns = ['cnpj_norm','nome_b3']

# Cruza: cnpj → nome_itr + nome_b3
mapa_completo = cnpj_empresa.merge(cnpj_b3, on='cnpj_norm', how='inner')

# Para cada nome_b3 do Ibovespa, pega o nome_itr correspondente
ibov_nomes = {}
for ticker in TICKERS_IBOV:
    if ticker in ticker_para_nome:
        nome_b3 = ticker_para_nome[ticker]
        match = mapa_completo[mapa_completo['nome_b3'] == nome_b3]
        if not match.empty:
            ibov_nomes[ticker] = match.iloc[0]['nome_itr']

print(f"Empresas encontradas no ITR: {len(ibov_nomes)}/{len(TICKERS_IBOV)}")

# ================================================================
# 4) FILTRA df só para empresas do Ibovespa
# ================================================================

nomes_itr_ibov = list(ibov_nomes.values())
df = df[df['ativo'].isin(nomes_itr_ibov)].copy()
print(f"\nLinhas após filtro Ibovespa: {len(df)}")
print(f"Empresas únicas: {df['ativo'].nunique()}")

# Adiciona ticker
nome_itr_para_ticker = {v: k for k, v in ibov_nomes.items()}
df['ticker'] = df['ativo'].map(nome_itr_para_ticker)

# ================================================================
# 5) CALCULA indicadores
# ================================================================

df['divida_bruta']   = df['divida_cp'] + df['divida_lp']
df['divida_liquida'] = df['divida_bruta'] - df['caixa']
df['cap_investido']  = df['pl'] + df['divida_liquida']

df['ROIC']        = df['ebit'] / df['cap_investido']
df['ROE']         = df['lucro'] / df['pl']
df['margem_liq']  = df['lucro'] / df['receita']
df['div_ebitda']  = df['divida_bruta'] / df['ebit']  # proxy EBITDA≈EBIT
df['ROA']         = df['lucro'] / df['ativo_total']

# Remove cap_investido negativo
df = df[df['cap_investido'] > 0].reset_index(drop=True)

print(f"\nApós remover cap_investido ≤ 0: {len(df)} linhas")

# ================================================================
# 6) BUSCA preço histórico
# ================================================================

def get_preco(ticker: str, dt_refer: str):
    try:
        data_fim = pd.Timestamp(dt_refer)
        data_ini = data_fim - pd.Timedelta(days=7)
        hist = yf.download(
            ticker + ".SA",
            start=data_ini,
            end=data_fim + pd.Timedelta(days=1),
            progress=False,
            auto_adjust=True
        )
        if hist.empty:
            return None
        return float(hist["Close"].iloc[-1])
    except Exception:
        return None

combos = df[['ticker','dt_refer']].drop_duplicates()
print(f"\nBuscando preços para {len(combos)} combinações ticker+data...")

precos = {}
for i, row in combos.iterrows():
    key = (row['ticker'], row['dt_refer'])
    precos[key] = get_preco(row['ticker'], row['dt_refer'])
    if (i+1) % 20 == 0:
        print(f"  {i+1}/{len(combos)}...")

df['preco'] = df.apply(lambda r: precos.get((r['ticker'], r['dt_refer'])), axis=1)
print(f"Com preço: {df['preco'].notna().sum()}/{len(df)}")

# ================================================================
# 7) BUSCA número de ações
# ================================================================

df_cap = pd.read_csv(
    'itr_cia_aberta_composicao_capital_2023.csv',
    sep=';', encoding='latin1', dtype={'CNPJ_CIA': str}
)
df_cap['cnpj_norm']  = df_cap['CNPJ_CIA'].apply(normalizar_cnpj)
df_cap['acoes_circ'] = df_cap['QT_ACAO_TOTAL_CAP_INTEGR'] - df_cap['QT_ACAO_TOTAL_TESOURO']
df_cap['dt_refer']   = pd.to_datetime(df_cap['DT_REFER'], dayfirst=True).dt.strftime('%Y-%m-%d')
df_cap = df_cap.sort_values('VERSAO', ascending=False).drop_duplicates(subset=['cnpj_norm','dt_refer'])
df_cap = df_cap[['cnpj_norm','dt_refer','acoes_circ']]

# Adiciona cnpj_norm no df
df = df.merge(
    cnpj_empresa[['nome_itr','cnpj_norm']].rename(columns={'nome_itr':'ativo'}),
    on='ativo',
    how='left'
)

# Junta ações
df = df.merge(df_cap, on=['cnpj_norm','dt_refer'], how='left')
print(f"Com ações: {df['acoes_circ'].notna().sum()}/{len(df)}")

# ================================================================
# 8) CALCULA EV e Earnings Yield
# ================================================================

df['valor_mercado']   = df['preco'] * df['acoes_circ']
df['EV']              = df['valor_mercado'] + df['cap_investido'] - df['pl']
df['earnings_yield']  = df['ebit'] / df['EV']

# ================================================================
# RESULTADO FINAL
# ================================================================

df_final = df[[
    'ativo', 'ticker', 'dt_refer', 
    'preco', 'acoes_circ', 'valor_mercado',
    'ebit', 'cap_investido', 'pl', 'EV',
    'ROIC', 'earnings_yield', 'ROE', 'margem_liq', 'div_ebitda', 'ROA'
]].copy()

print("\n" + "="*70)
print("RESULTADO FINAL")
print("="*70)
print(f"Total linhas:  {len(df_final)}")
print(f"Empresas:      {df_final['ativo'].nunique()}")
print(f"Tickers:       {df_final['ticker'].nunique()}")
print(f"Com EV:        {df_final['EV'].notna().sum()}")
print(f"Com EY:        {df_final['earnings_yield'].notna().sum()}")
print()
print(df_final[['ativo','ticker','dt_refer','earnings_yield','ROIC']].head(12).to_string(index=False))
print()

# Salva
df_final.to_excel('ibovespa_magic_formula_2023.xlsx', index=False)
print("Salvo: ibovespa_magic_formula_2023.xlsx")

Empresas no arquivo: 423
Total linhas (empresa × data): 1269

Tickers mapeados: 83/85
Empresas encontradas no ITR: 78/85

Linhas após filtro Ibovespa: 195
Empresas únicas: 65

Após remover cap_investido ≤ 0: 195 linhas

Buscando preços para 195 combinações ticker+data...

C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  20/195...

C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
$MOTV3.SA: possibly delisted; no price data found  (1d 2023-03-24 00:00:00 -> 2023-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1679626800, endDate = 1680318000")

1 Failed download:
['MOTV3.SA']: possibly delisted; no price data found  (1d 2023-03-24 00:00:00 -> 2023-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1679626800, endDate = 1680318000")
$MOTV3.SA: possibly delisted; no price data found  (1d 2023-06-23 00:00:00 -> 2023-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1687489200, endDate = 1688180400")

1 Failed download:
['MOTV3.SA']: possibly delisted; no price data found  (1d 2023-06-23 00:00:00 -> 2023-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1687489200, endDate = 1688180400")
$MOTV3.SA: possibly delisted; no price data found  (1d 2023-09-23 00:00:00 -> 2023-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1695438000, endDate = 1696129200")

1 Failed download:
['MOTV3.SA']: possibly delisted; no price data found  (1d 2023-09-23 00:00:00 -> 2023-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1695438000, endDate = 1696129200")
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  40/195...

C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  60/195...

C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
$EMBJ3.SA: possibly delisted; no price data found  (1d 2023-03-24 00:00:00 -> 2023-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1679626800, endDate = 1680318000")

1 Failed download:
['EMBJ3.SA']: possibly delisted; no price data found  (1d 2023-03-24 00:00:00 -> 2023-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1679626800, endDate = 1680318000")
$EMBJ3.SA: possibly delisted; no price data found  (1d 2023-06-23 00:00:00 -> 2023-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1687489200, endDate = 1688180400")

1 Failed download:
['EMBJ3.SA']: possibly delisted; no price data found  (1d 2023-06-23 00:00:00 -> 2023-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1687489200, endDate = 1688180400")
$EMBJ3.SA: possibly delisted; no price data found  (1d 2023-09-23 00:00:00 -> 2023-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1695438000, endDate = 1696129200")

1 Failed download:
['EMBJ3.SA']: possibly delisted; no price data found  (1d 2023-09-23 00:00:00 -> 2023-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1695438000, endDate = 1696129200")
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  80/195...

C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
$RENT4.SA: possibly delisted; no price data found  (1d 2023-03-24 00:00:00 -> 2023-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1679626800, endDate = 1680318000")

1 Failed download:
['RENT4.SA']: possibly delisted; no price data found  (1d 2023-03-24 00:00:00 -> 2023-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1679626800, endDate = 1680318000")
$RENT4.SA: possibly delisted; no price data found  (1d 2023-06-23 00:00:00 -> 2023-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1687489200, endDate = 1688180400")

1 Failed download:
['RENT4.SA']: possibly delisted; no price data found  (1d 2023-06-23 00:00:00 -> 2023-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1687489200, endDate = 1688180400")
$RENT4.SA: possibly delisted; no price data found  (1d 2023-09-23 00:00:00 -> 2023-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1695438000, endDate = 1696129200")

1 Failed download:
['RENT4.SA']: possibly delisted; no price data found  (1d 2023-09-23 00:00:00 -> 2023-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1695438000, endDate = 1696129200")
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  100/195...

C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  120/195...

C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  140/195...

C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  160/195...

C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
$NATU3.SA: possibly delisted; no price data found  (1d 2023-03-24 00:00:00 -> 2023-04-01 00:00:00)

1 Failed download:
['NATU3.SA']: possibly delisted; no price data found  (1d 2023-03-24 00:00:00 -> 2023-04-01 00:00:00)
$NATU3.SA: possibly delisted; no price data found  (1d 2023-06-23 00:00:00 -> 2023-07-01 00:00:00)

1 Failed download:
['NATU3.SA']: possibly delisted; no price data found  (1d 2023-06-23 00:00:00 -> 2023-07-01 00:00:00)
$NATU3.SA: possibly delisted; no price data found  (1d 2023-09-23 00:00:00 -> 2023-10-01 00:00:00)

1 Failed download:
['NATU3.SA']: possibly delisted; no price data found  (1d 2023-09-23 00:00:00 -> 2023-10-01 00:00:00)
$CYRE4.SA: possibly delisted; no price data found  (1d 2023-03-24 00:00:00 -> 2023-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1679626800, endDate = 1680318000")

1 Failed download:
['CYRE4.SA']: possibly delisted; no price data found  (1d 2023-03-24 00:00:00 -> 2023-04-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1679626800, endDate = 1680318000")
$CYRE4.SA: possibly delisted; no price data found  (1d 2023-06-23 00:00:00 -> 2023-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1687489200, endDate = 1688180400")

1 Failed download:
['CYRE4.SA']: possibly delisted; no price data found  (1d 2023-06-23 00:00:00 -> 2023-07-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1687489200, endDate = 1688180400")
$CYRE4.SA: possibly delisted; no price data found  (1d 2023-09-23 00:00:00 -> 2023-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1695438000, endDate = 1696129200")

1 Failed download:
['CYRE4.SA']: possibly delisted; no price data found  (1d 2023-09-23 00:00:00 -> 2023-10-01 00:00:00) (Yahoo error = "Data doesn't exist for startDate = 1695438000, endDate = 1696129200")
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

  180/195...

C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])

Com preço: 180/195
Com ações: 195/195

======================================================================
RESULTADO FINAL
======================================================================
Total linhas:  195
Empresas:      65
Tickers:       65
Com EV:        180
Com EY:        180

            ativo ticker   dt_refer  earnings_yield     ROIC
AXIA ENERGIA S.A.  AXIA6 2023-03-31        0.058757 0.031165
AXIA ENERGIA S.A.  AXIA6 2023-06-30        0.068563 0.043754
AXIA ENERGIA S.A.  AXIA6 2023-09-30        0.049323 0.029092
    ENERGISA S.A. ENGI11 2023-03-31        0.000023 0.084107
    ENERGISA S.A. ENGI11 2023-06-30        0.000017 0.068897
    ENERGISA S.A. ENGI11 2023-09-30        0.000021 0.079716
PORTO SEGURO S.A.  PSSA3 2023-03-31        0.033528 0.039474
PORTO SEGURO S.A.  PSSA3 2023-06-30        0.039452 0.054006
PORTO SEGURO S.A.  PSSA3 2023-09-30        0.060466 0.075770
        RUMO S.A.  RAIL3 2023-03-31        0.000021 0.035772
        RUMO S.A.  RAIL3 2023-06-30        0.000023 0.046705
        RUMO S.A.  RAIL3 2023-09-30        0.000031 0.062400

Salvo: ibovespa_magic_formula_2023.xlsx

C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:162: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return float(hist["Close"].iloc[-1])
C:\Users\joaon\AppData\Local\Temp\ipykernel_21480\223939216.py:189: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df_cap['dt_refer']   = pd.to_datetime(df_cap['DT_REFER'], dayfirst=True).dt.strftime('%Y-%m-%d')

Como a Magic Formula Original Funciona

Rankeia todas as ações pelo Earnings Yield (maior → melhor → ranking 1, 2, 3...)
Rankeia todas as ações pelo ROIC (maior → melhor → ranking 1, 2, 3...)
Soma os rankings (não os valores)
Seleciona as top 20-30 com menor ranking combinado